fix-adopt-pageurl-tag-in-all-wagtail-admin-url-usage
wagtail/wagtail pull request #10157
Opened 2023-02-25 17:01 UTC by satvikvash

Fixes #10125 

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

2023-02-25 22:44 UTC, lb- commented on wagtail/admin/templates/wagtailadmin/chooser/tables/page_title_cell.html
> +                <a class="choose-page" href="#{{ page.id|unlocalize }}" data-id="{{ page.id|unlocalize }}" data-title="{{ page.title }}" data-admin-title="{{ page.get_admin_display_title }}" data-url
```suggestion
                <a class="choose-page" href="#{{ page.id|unlocalize }}" data-id="{{ page.id|unlocalize }}" data-title="{{ page.title }}" data-admin-title="{{ page.get_admin_display_title }}" data-url="{% pageurl page %}" data-parent-id="{{ page.get_parent.id|unlocalize }}" data-edit-url="{% url 'wagtailadmin_pages:edit' page.id %}">{{ value }}</a>
```

2023-02-25 22:44 UTC, lb- commented on wagtail/admin/templates/wagtailadmin/chooser/tables/page_title_cell.html
> +                <a class="choose-page" href="#{{ page.id|unlocalize }}" data-id="{{ page.id|unlocalize }}" data-title="{{ page.title }}" data-admin-title="{{ page.get_admin_display_title }}" data-url
No need to use the `as` syntax if you're just wanting to output the value of the template tag.

2023-02-26 01:41 UTC, lb- requested changes

2023-02-26 01:41 UTC, lb- commented on wagtail/admin/templates/wagtailadmin/shared/page_status_tag_new.html
> +    <a href="{% pageurl page as page_url %}" target="_blank" rel="noreferrer"
```suggestion
    <a href="{% pageurl page %}" target="_blank" rel="noreferrer"
```

Same here - we do not need to use the `as` if just putting the result straight into the template output.

2023-02-26 01:44 UTC, lb- commented
@satvikvash  great start here, I have not validated locally, please be sure to work out where each of these scenarios are used and manually check they work. It may also help in reviewing to put a list of these example pages within the admin for testing.

Have a look at the failing tests also `wagtail.admin.tests.pages.test_edit_page.TestPageEdit` (check the CI results).

@zerolab  - may need your insights here, it appears that this test is failing because there are now 43 queries run instead of the previous 41 so just want to confirm that maybe this PR is using the template tag wrong or our assumptions about it being more performant have some nuance to consider.

2023-02-26 17:04 UTC, zerolab commented
It looks like we are hitting the https://github.com/wagtail/wagtail/blob/845b731d13d13fc078dc8a7e055b9532f4e9aa55/wagtail/models/__init__.py#L2133-L2136 use case as [`pageurl` passes the request](https://github.com/wagtail/wagtail/blob/845b731d13d13fc078dc8a7e055b9532f4e9aa55/wagtail/templatetags/wagtailcore_tags.py#L29), but that doesn't have the site cached yet 🤔

2023-02-26 17:38 UTC, zerolab commented
@lb- just tested with #10018 and that solves the query discrepancy issue.

perhaps we leave `wagtail/admin/templates/wagtailadmin/shared/page_status_tag_new.html` as `{{ page.url }}` with a note about it.

Did a poor man's debug print in Site.find_for_request, and it looks like nothing else triggers it which is interesting

2023-03-01 05:09 UTC, satvikvash commented
Hi @lb- I have made all changes as suggested and have also tested them. Could you please re review it and suggest any further changes?

2023-03-01 11:50 UTC, lb- commented
@zerolab  based on your comments above with #10018 making this better, I think we probably merge in as is.

I will take another look tomorrow and if all the other testing passed I will probably merge this in.

Thanks @satvikvash  so far looking good but need to do another full review.

2023-03-17 21:06 UTC, lb- approved these changes
This is working great, I will make two tweaks (as per comment) and merge in.

2023-03-17 21:06 UTC, lb- commented on wagtail/admin/templates/wagtailadmin/shared/page_status_tag.html
>      {% status page.status_string hidden_label=status_hidden_label %}
Not an issue with your PR but I noticed that `status_hidden_label` will never be anything in this branch, so I will pull this variable up into the parent scope (above the if statement) in this PR.

2023-03-17 21:06 UTC, lb- commented on wagtail/admin/templates/wagtailadmin/shared/page_status_tag.html
> +        {% status page.status_string url=page_url title=status_title hidden_label=status_hidden_label classname="primary" attrs='target="_blank" rel="noreferrer"' %}
```suggestion
        {% status page.status_string url=page_url title=_("Visit the live page") hidden_label=status_hidden_label classname="primary" attrs='target="_blank" rel="noreferrer"' %}
```

As per discussion on #10126 - I will refine this to use a more convenient approach for passing in a translation to a template tag variable.

2023-03-17 21:35 UTC, merged