update leftover status-tag usage to status template tag
wagtail/wagtail pull request #10154
Opened 2023-02-25 13:19 UTC by HimanshuGarg47

This PR addresses this issue #10129

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

2023-02-25 13:28 UTC, salty-ivy commented
make sure you install the code liniting package that wagtail use, it reindents your code so you don't get those silly indentation errors as your CI failures.

additionally for part 2 as you would be dealing with changes in CSS classes and their implementations.  after the changes 
make sure you run `npm run build`.

2023-02-25 16:15 UTC, salty-ivy commented
@HimanshuGarg47 please read the comment above the test failures are because of incorrect indentation and spacing. 
That's why I recommended you to use make lint.

2023-02-25 17:00 UTC, HimanshuGarg47 commented
> 
Make lint is giving below error
![image](https://user-images.githubusercontent.com/78200614/221369762-5ee6cce8-2c6c-45e4-8b67-a7e6c8fb8b7c.png)

2023-02-25 17:08 UTC, salty-ivy commented
You just need to install the package using `pre-commit install `

2023-02-25 17:10 UTC, salty-ivy commented
Checkout https://docs.wagtail.org/en/stable/contributing/developing.html#automatically-lint-and-code-format-on-commits

2023-02-26 08:51 UTC, lb- requested changes
Looks good somfsr except for the translation usage. Please ensure you double check usage in the bakerydemo. 

Thanks for keeping at this.

2023-02-26 08:51 UTC, lb- commented on wagtail/admin/templates/wagtailadmin/shared/workflow_history/detail.html
> +                                                    {% blocktrans trimmed with action='{% status task_state.get_status_display classname="primary" %}'|safe at=task_state.finished_at %}
Same here with the translation usage.

2023-02-26 08:52 UTC, lb- commented
@HimanshuGarg47 once the fixes are applied and the CI is passing - please feel free to mark this as ready (no -draft) and add a comment it's ready for a review.

2023-03-17 20:38 UTC, lb- approved these changes
Tested all these scenarios and they work great, thanks so much @HimanshuGarg47 

I will rebase and get this merged in

2023-03-17 21:10 UTC, merged