ChooserWidget: Trigger manually change event when input.value is set
wagtail/wagtail pull request #10187
Opened 2023-03-05 09:52 UTC by gsakkis

Fixes #10186

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

2023-03-06 02:08 UTC, lb- reviewed
Should these events bubble? So that they emulate actual change events?

Or would a custom event name be suitable for what you need?

2023-03-06 06:10 UTC, gsakkis commented
Yes they should emulate actual change events; as mentioned in #10186, django-smart-selects [sets a handler on the change event](https://github.com/jazzband/django-smart-selects/blob/master/smart_selects/static/smart-selects/admin/js/chainedfk.js#L89).

2023-03-06 20:47 UTC, lb- requested changes
Haven't tested yet but as noted, this should probably bubble.

2023-03-06 20:47 UTC, lb- commented on client/src/components/ChooserWidget/index.js
> +    this.input.dispatchEvent(new Event("change"));
```suggestion
    this.input.dispatchEvent(new Event("change", { bubbles: true }));
```

2023-03-06 20:47 UTC, lb- commented on client/src/components/ChooserWidget/index.js
> +    this.input.dispatchEvent(new Event("change"));
```suggestion
    this.input.dispatchEvent(new Event("change", { bubbles: true }));
```

2023-03-07 07:22 UTC, gsakkis commented on client/src/components/ChooserWidget/index.js
> +    this.input.dispatchEvent(new Event("change"));
Done

2023-03-07 07:22 UTC, gsakkis commented on client/src/components/ChooserWidget/index.js
> +    this.input.dispatchEvent(new Event("change"));
Done

2023-03-11 04:54 UTC, lb- approved these changes
Looking good, I have tested before and after and can see that choosers now correctly fire a `'change'` event.

Really appreciate this change. I have run the formatter and will push up a rebase of this to merge in.

I will add you to the contributors list as 'George Sakkis' but let me know if you want a different name listed.

### Some validation screenshots

<img width="1024" alt="Screenshot 2023-03-11 at 2 52 29 pm" src="https://user-images.githubusercontent.com/1396140/224465653-397a8469-f4dd-4b67-ba58-5c6c0d3011f5.png">
<img width="1470" alt="Screenshot 2023-03-11 at 2 51 53 pm" src="https://user-images.githubusercontent.com/1396140/224465657-ae9a99e4-4758-44c7-b479-1a68b180632a.png">

2023-03-11 05:57 UTC, merged