ReferenceIndex model registration
wagtail/wagtail pull request #10339
Opened 2023-04-17 10:39 UTC by dkirkham

Fixes #9731, supercedes #9936

This PR proposes an alternative way to configure the models that are indexed by the [ReferenceIndex](https://docs.wagtail.org/en/latest/advanced_topics/reference_index.html) system. Instead of indexing all models including non-Wagtail-related models by default, this alternative requires models to be specifically registered.

In this implementation, models subclassed from Wagtail `AbstractPage`, `AbstractImage` and `AbstractDocument` models, including the default `Page`, `Image` and `Document` models, are by default indexed, as are models registered as Snippets and with ModelAdmin. The developer can exclude these models as desired, and register their own models via an app.ready() hook, as suggested in @gasman's [comment](https://github.com/wagtail/wagtail/issues/9731#issuecomment-1416244639).

This implementation is a draft. All the existing tests pass without change, however some further tests are probably warranted and the documentation will need to be updated. I am submitting this at this stage to get feedback on the overall approach which I describe below, and to get the reports from the full CI testing.

As this is likely to be considered a breaking change, @gasman expressed a desire to get this into the 5.0 release, I'd appreciate a fairly swift initial review so I can make appropriate changes including the tests and documentation. Feedback on suitable additional tests and possible deprecations would also be useful.

## Approach

Here are the key changes:
- `ReferenceIndex.model_is_indexable()` is no longer being called for every updated model instance. Instead, it is used to form `ReferenceIndex._indexed_models` which stores the models that need to be tracked via Django's `post_save` signal, and which are to be indexed. This list is formed using the new `ReferenceIndex.register_model()` method, which is for instance called in `wagtail.apps.WagtailAppConfig.ready()` for the default model types. Other apps can use the same technique to register their models as required. Note that `model_is_indexable()` still checks the `wagtail_reference_index_ignore` attribute to disable indexing where required.
- a new `ReferenceIndex.is_indexed()` method replaces `ReferenceIndex.model_is_indexable()` to provide a public interface to lookup the `_indexed_models` cached information.
- in `wagtail.signal_handlers` the `post_save` and `post_delete` signals are used as before, but only the necessary models are being tracked (using `sender=`), to remove the impact on non-Wagtail apps and models.
- Snippet and ModelAdmin model registration has been added.
- there is a new management command `show_references_index` which shows which models are indexed and how many index records are currently in the database.

## Existing Tests

As mentioned, the existing tests all pass without change, although it was necessary to register one model explicitly, `PageChooserModel`.

Below I've documented the models that are no longer being tracked within  `testapp` in case there are models anyone believes should be indexed by default:

```
wagtail.contrib.redirects.models.Redirect
wagtail.test.testapp.models.RelatedGenericRelation
wagtail.test.testapp.models.CustomFormPageSubmission
wagtail.test.testapp.models.EventPageChooserModel
wagtail.test.testapp.models.SnippetChooserModel
wagtail.test.testapp.models.SnippetChooserModelWithCustomPrimaryKey
wagtail.test.testapp.models.JSONStreamModel
wagtail.test.testapp.models.JSONMinMaxCountStreamModel
wagtail.test.testapp.models.JSONBlockCountsStreamModel
wagtail.test.testapp.models.ImportantPagesSiteSetting
wagtail.test.testapp.models.ImportantPagesGenericSetting
wagtail.test.testapp.models.SimpleTask
wagtail.test.search.models.Character
wagtail.test.i18n.models.TestNonParentalChildObject
wagtail.test.streamfield_migrations.models.SampleModel
wagtail.contrib.search_promotions.models.QueryDailyHits
wagtail.contrib.search_promotions.models.SearchPromotion
wagtail.contrib.forms.models.FormSubmission
wagtail.models.sites.Site
wagtail.models.collections.CollectionViewRestriction
wagtail.models.collections.GroupCollectionPermission
wagtail.models.GroupPagePermission
wagtail.models.PageViewRestriction
wagtail.models.WorkflowPage
wagtail.models.WorkflowContentType
wagtail.models.Task
wagtail.models.Workflow
wagtail.models.GroupApprovalTask
wagtail.models.WorkflowState
wagtail.models.TaskState
django.contrib.admin.models.LogEntry
django.contrib.auth.models.Permission
```

_Please check the following:_

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [x] Run `make lint` from the Wagtail root.
-   [x] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] ~~For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]~~
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [x] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

2023-04-18 10:04 UTC, gasman requested changes
Thanks @dkirkham! I'm afraid this bit of work fell off the radar a bit when planning the 5.0 release, and we're due to put the release candidate out tomorrow - but I think this is in a good enough state that I'd be keen to try and get this over the line today / tomorrow.

2023-04-18 10:13 UTC, dkirkham commented on wagtail/models/reference_index.py
> +    # which are being indexed
Happy to adjust the terminology... tracked means we are listening to the post_save/post_delete signal where there is a ParentalKey to the model that is actually indexed. I'll expand the comment.

2023-04-18 11:26 UTC, dkirkham commented on wagtail/apps.py
> +        from wagtail.images.models import AbstractImage
I've confirmed the tests continue to work if I register `wagtail.images.get_image_model()` and `wagtail.documents.get_document_model()` within the corresponding apps.

`rebuild_references_index` starts with `ReferenceIndex.objects.all().delete()` so I think that addresses your last concern.

2023-04-18 11:27 UTC, dkirkham commented
Thanks @gasman. Assuming there are no further coding concerns, I'll work on the documentation now. I doubt I will get to any additional tests tonight.

2023-04-18 13:22 UTC, dkirkham commented
I've prepared the documentation @gasman, including a one-line entry in the new features section - of course, you might consider this a fix or maintenance.

Realistically, this is all I can do on this tonight. Happy for you to take this forward today, and I can resume and develop some tests later tomorrow.

2023-04-19 09:56 UTC, dkirkham commented
I've added a test for the new management command `show_references_index`.

I believe the existing tests adequately exercise the refactored code.

So should be good for a final review.

2023-04-19 17:40 UTC, gasman requested changes
Thanks again @dkirkham! A couple of further changes which I'll pick up myself...

2023-04-19 17:40 UTC, gasman commented on docs/advanced_topics/reference_index.md
> +A model can be registered for reference indexing by adding code to the model's `app.py`:
```suggestion
A model can be registered for reference indexing by adding code to `apps.py` in the app where the model is defined:
```

2023-04-19 17:40 UTC, gasman commented on wagtail/models/reference_index.py
> +    _indexed_models = {}
I think it might be clearer to represent this as two sets: one for tracked models and one for indexed models.

2023-04-19 19:10 UTC, gasman commented
Rebased at #10364

2023-04-19 19:10 UTC, closed without merging