Update tailwind.config.js
wagtail/wagtail pull request #10484
Opened 2023-05-25 14:27 UTC by rgs258

This changes the zIndex to be compatible with bootstrap's sidebar while allowing the userbar to show above the accessibility menu. Thank you @fourfridays for the issue!

Fixes #10471

_Please check the following:_

-   [ Probably ] Do the tests still pass?[^1]
-   [ Yes ] Does the code comply with the style guide?
    -   [ Skipped ] Run `make lint` from the Wagtail root.
-   [ N/A ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ Skipped ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ N/A ] **Please list the exact browser and operating system versions you tested**:
    -   [ N/A ] **Please list which assistive technologies [^3] you tested**:
-   [ N/A ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

2023-06-03 00:33 UTC, lb- commented
Not sure on this change, maybe it's best to try to ensure the userbar modal usage styles are different from the Wagtail admin ones. 

This global change constrains us in the admin and could cause other cascading z-index issues. 

Maybe we can either override the z-index for dialog in the userbar or use a different approach to ensure that the dialog html sits inside the userbar z-index and/or revisit another way to adjust the stacking context. 

Finally, there is no way for us to know what z-index is used in the styles of websites that use Wagtail, so we could look at the documentation and advise that the Dom location consider this.

2023-06-04 09:57 UTC, laymonage requested changes
As noted by @lb- above, the best way to change this would be to add the z-index only for `.w-dialog--userbar`:

https://github.com/wagtail/wagtail/blob/9b0294c9657dc952f0d31ab3a00a1c3970fc02d4/client/scss/components/_userbar.scss#L244-L248

2023-06-05 19:09 UTC, rgs258 commented
Hey folks, 

@lb-  and @laymonage  I'm not a tailwind expert and so won't stand by my changes :). That said, I do believe that Wagtail has an error in that the accessibility tooltips are in the hundreds z range and the userbar is 9999. The userbar works well with bootstrap out of the box while the accessibility tooltips categorically do not. While my exact change might not be the precise change that is needed, something to address https://github.com/wagtail/wagtail/issues/10471 is needed to round out this functionality.

I'm closing this issue and we're working around this issue in our css overrides for now. I hope https://github.com/wagtail/wagtail/issues/10471 can get taken up in 5.1 so that we can pull out our workaround css.

2023-06-05 19:09 UTC, closed without merging

2023-06-05 22:44 UTC, lb- commented
@rgs258 thanks, sorry for the confusing description, the main goal is to avoid a change to all the main admin styles for fixing something that's only needed in the userbar scope. Within the admin we intentionally try to avoid very high z-index ranges as there is usually a better way to solve those problems.

I have submitted a PR here and if you don't mind checking this and hopefully this approach will solve the problem https://github.com/wagtail/wagtail/pull/10514