Add clearer "expanded" state indicator for side panel toggles. Fix #9174
wagtail/wagtail pull request #10546
Opened 2023-06-12 07:37 UTC by thibaudcolas

Fixes #9174, with a few additional changes:

- Refactors those button and icon classes so we avoid duplicating them everywhere they’re used. Django Templates allows referencing variables defined in a parent template.
- Make sure the buttons are the same width as height to match the designs (40x50 -> 50x50)
- Add the new "expanded" state indicator, making sure its toggling doesn’t disrupt the buttons’ layout.

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

2023-06-12 08:08 UTC, thibaudcolas commented on wagtail/admin/templates/wagtailadmin/shared/headers/slim_header.html
> +{% fragment as nav_icon_button_classes %}w-w-slim-header w-h-slim-header w-bg-transparent w-border-transparent w-border-y-2 w-box-border w-py-3 w-px-3 w-flex w-justify-center w-items-center w-outline
Before-after diff for ref – I’ve added `w-w-slim-header w-border-transparent w-border-y-2 expanded:w-border-b-current hover:expanded:w-border-b-transparent`, and also `expanded:w-text-text-label` is now set all the time.

Full diff:

```diff
- w-h-slim-header w-bg-transparent w-box-border w-py-3 w-px-3 w-flex w-justify-center w-items-center w-outline-offset-inside w-text-text-meta w-transition hover:w-transform hover:w-scale-110 hover:w-text-text-label focus:w-text-text-label
+ w-w-slim-header w-h-slim-header w-bg-transparent w-border-transparent w-border-y-2 w-box-border w-py-3 w-px-3 w-flex w-justify-center w-items-center w-outline-offset-inside w-text-text-meta w-transition hover:w-transform hover:w-scale-110 hover:w-text-text-label focus:w-text-text-label expanded:w-text-text-label expanded:w-border-b-current hover:expanded:w-border-b-transparent
```

2023-06-12 08:12 UTC, thibaudcolas commented on wagtail/admin/templates/wagtailadmin/shared/side_panel_toggles.html
> +        class="{{ nav_icon_button_classes }}"
Note this `expanded:w-text-text-label` and other "expanded" styles are now applied to all slim header "nav icon buttons", which includes the link to the History page. The classes do nothing on those `a` tags but I thought we might as well add them there for simplicity.

2023-06-12 08:12 UTC, thibaudcolas commented on client/src/tokens/objectStyles.js
> +  2: '0.125rem', // 2px
We have quite a few 2px borders already but apparently only in Sass where we don’t check the variety of border widths.

2023-06-14 09:13 UTC, lb- requested changes
@thibaudcolas looking good, only issue I have with this is that now the user now gets no instant feedback when using a mouse and clicking a button.

What happens is that the hover state (showing the tooltip) also hides the little selected bar at the bottom of the icon. So in some cases when you click the button it feels like nothing has actually happened. I know the sidebar opens but to me this feels like a something we should address so that the hover & selected state still looks more like the plain selected state.

| selected | selected & hover |
|-|-|
| <img width="104" alt="Screenshot 2023-06-14 at 7 11 41 pm" src="https://github.com/wagtail/wagtail/assets/1396140/83be3204-941b-4dc8-b948-ab59db5c2198"> | <img width="87" alt="Screenshot 2023-06-14 at 7 11 37 pm" src="https://github.com/wagtail/wagtail/assets/1396140/220d039a-d311-4464-be11-a78ef4e9dccb"> |

**Other validation screenshots - looking great**

Top to bottom - Firefox, Safari & Chrome

<img width="1077" alt="Screenshot 2023-06-14 at 7 09 28 pm" src="https://github.com/wagtail/wagtail/assets/1396140/b41121a6-c0d1-4168-934e-f7a3417b2337">

<img width="945" alt="Screenshot 2023-06-14 at 7 08 46 pm" src="https://github.com/wagtail/wagtail/assets/1396140/b9d3a44a-d002-4d8f-9434-0f9b4c201502">

2023-06-14 09:36 UTC, laymonage commented
Good points @lb-, I raised this with Thibaud and Ben (our designer) yesterday and we decided to keep the border even if it's hovered. There are a few minor tweaks that need to be done as well, particularly around the scale-up effect on hover, e.g. making sure only the icon (and not the border) gets scaled up.

2023-06-15 06:35 UTC, thibaudcolas commented
Good point! I’ve updated the implementation accordingly, with the "hover" and "expanded" states now completely independent (and thus stacking when both are in play):

![hover-9174](https://github.com/wagtail/wagtail/assets/877585/b8d30bde-3006-4f24-a2a6-c3744978321f)

2023-06-15 09:19 UTC, laymonage approved these changes
Looks good and tested it on Chrome 114, Firefox 114, and Safari 16.5.

The latest changes suggest that we haven't addressed the "keep scaled-up icon when expanded" behaviour, but I tried and couldn't get `group-expanded` to work. I think we can revisit this later. I can merge it for you but I'll leave it for now in case you want to give it a try. Thanks!

2023-06-15 14:49 UTC, thibaudcolas commented
@laymonage yes, I chose to _not_ do this as it does nothing towards fixing #9174 and I’m not clear on the rationale to keep icons scaled in this "expanded" state.

I’ll discuss this with @benenright at the next available opportunity. If we do make that change, I’d prefer to also do it in other places this "scale up" effect is used at the same time. And refactor the code so we don’t duplicate those hover effects.

2023-06-15 14:53 UTC, merged

2023-06-15 15:22 UTC, thibaudcolas commented
Merged and cherry-picked to `stable/5.0.x`.