feat: add marking for LTS releases
wagtail/wagtail pull request #10550
Opened 2023-06-12 14:50 UTC by souzathg

Fixes #10508

Adds marking to LTS releases in the docs, as requested in this issue.
I added the markings by changing the title of the files. 
Please don't hesitate to suggest any changes.

_Please check the following:_

-   [X] For new features: Has the documentation been updated accordingly?

2023-06-12 15:02 UTC, gasman requested changes
Thanks @souzathg!

2023-06-12 16:42 UTC, souzathg commented on docs/releases/0.8.rst
>  =========================
Ah, ok! Thanks for pointing that out!
As soon as it's done, I'll reply again.

2023-06-12 16:46 UTC, souzathg commented on docs/releases/0.8.rst
>  =========================
I increased the length of the lines, as requested 😄

2023-06-13 09:38 UTC, gasman approved these changes
Thanks - all looks good to me!

2023-06-13 09:43 UTC, gasman commented
Merged in ce620bf57b66576fe4c0cc1ed58e1a0f6e9fbeb8.

2023-06-13 09:43 UTC, closed without merging