Clean up and update deployment page
wagtail/wagtail pull request #10574
Opened 2023-06-19 16:16 UTC by RealOrangeOne

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

This cleans out some very old, potentially out of scope content, and makes way for the page being much easier to contribute to and extend in future.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

2023-06-19 16:48 UTC, Scotchester reviewed
Nice cleanup, Jake! Found a typo and have one other minor comment.

2023-06-19 16:48 UTC, Scotchester commented on docs/advanced_topics/deploying.md
> +Here are some examples for deployments on a few hosting platforms. This is not a complete list of platforms where Heroku can run, nor is it necessarily the only way to run Wagtail there.
```suggestion
Here are some examples for deployments on a few hosting platforms. This is not a complete list of platforms where Wagtail can run, nor is it necessarily the only way to run Wagtail there.
```

2023-06-19 17:18 UTC, Scotchester commented on docs/advanced_topics/deploying.md
> +- [wagtail.org source code](https://github.com/wagtail/wagtail.org)
Yeah, a separate note explaining why we suggest people look at it would be great.

2023-06-21 10:02 UTC, lb- requested changes

2023-06-21 10:02 UTC, lb- commented on docs/advanced_topics/deploying.md
> +- [wagtail.org source code](https://github.com/wagtail/wagtail.org)
We also have the third party tutorials page, maybe we can just add these links to that page.

Then add two links, one to the third party tutorials page and another to the Awesome Wagtail section (if we have one) for this stuff.

2023-06-28 11:23 UTC, lb- approved these changes
Looks good to me.

2023-07-01 06:35 UTC, merged