Adding the value as a call argument to Block.get_template
wagtail/wagtail pull request #10711
Opened 2023-07-23 17:23 UTC by goutnet

At the moment, the `Block.get_template` call only accept  the context as argument. When called in a dynamic context, there is no easy/clean way to access the current value of the block… 

When called from the render call, the value is received by render but not passed along to the get_template function.

Adding this patch allows the Block to decide the template used based on the actual block value (or the value of one of its fields).

Change is trivial (adding a parameter to get_template). I added it before the context argument to keep the API consistent, but this introduce a potential compatibility change for sites that would already override/call get_template with an argument.

Let me know your thoughts

2023-07-25 21:07 UTC, lb- commented
Thanks @goutnet - I've flagged for a review. As per Slack this won't get I to the 5.1 Release as it's already in Release Candidate.

2023-07-26 08:22 UTC, gasman requested changes
Thanks @goutnet! This looks like a sensible change.

We do need to preserve backwards compatibility here, so that it doesn't break existing projects that use `get_template`. I'd suggest using the [`accepts_kwarg`](https://github.com/wagtail/wagtail/blob/a6a91e1a014912c6f7f65cc367c099e9338c8906/wagtail/coreutils.py#L171-L180) helper function within `render` to check whether `get_template` accepts a `value` argument before calling it - if it doesn't, we should raise a [RemovedInWagtail60Warning](https://github.com/wagtail/wagtail/blob/a6a91e1a014912c6f7f65cc367c099e9338c8906/wagtail/utils/deprecation.py#L5) and call it with just the context argument. We can then remove that additional check in a later release, once people have had chance to update their code.

2023-07-26 08:24 UTC, goutnet commented
looks very sensible, let me do just that :)

2023-07-26 20:17 UTC, lb- commented
@goutnet please can you add some tests to cover this new functionality also, this way it doesn't accidentally get removed in a future release.

2023-10-05 11:35 UTC, lb- commented
How are you going @goutnet  - are you still up for following this up with the suggested changes and unit tests?

2023-10-05 14:29 UTC, goutnet commented
Yes, it got out of my priority list, but I should send an update

2023-10-14 08:51 UTC, goutnet commented
@gasman : done

2023-10-14 09:21 UTC, goutnet commented
it doesn't look like the pipeline failure are related, or did I miss something?

2023-10-14 09:23 UTC, goutnet commented
> @goutnet please can you add some tests to cover this new functionality also, this way it doesn't accidentally get removed in a future release.

make sense, will add that next once @gasman gives me a green light on the current implementation.

2023-10-14 17:12 UTC, goutnet commented
> How are you going @goutnet - are you still up for following this up with the suggested changes and unit tests?

tests and modification  submitted, and the branch now passes all tests successfuly.

Please let me know :)

2023-10-16 20:35 UTC, gasman commented
Thanks @goutnet - all looks good to me! Have merged in 7d2c2a5e6d85d6d1c11061f4de540f37bd03d5ab, with a small tweak to the tests so that we're testing both the old and new method signatures. (I realised that the old test for `get_template` wasn't really testing the functionality at all - it was just defining a method, without even the right signature, and testing that we could call it...)

2023-10-16 20:35 UTC, closed without merging

2023-10-16 23:49 UTC, goutnet commented
Thanks!