Fix chooser buttons focus color is too dark in dark mode
wagtail/wagtail pull request #11288
Opened 2023-11-29 11:09 UTC by rohitsrma

Fixes #10875

**Before**

![Screenshot (41)](https://github.com/wagtail/wagtail/assets/111359305/4f5f0907-2beb-4506-9864-b42ae6c18c7a)

**After**

![image](https://github.com/wagtail/wagtail/assets/111359305/b8ca422c-fb9f-4b74-bd31-be74b614fff2)

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

2023-11-29 21:58 UTC, lb- requested changes
Great start @rohitsrma  - but a bit more is needed here to get this over the line.

See my comment inline.

2023-11-30 19:11 UTC, rohitsrma commented on client/scss/components/_chooser.scss
> +    color: theme('colors.text-button-outline-default');
Thanks, @lb- -, for the detailed suggestions. I initially thought we needed the same color for hover/focus with an outline, as shown in the `proposed hover state` in the issue. I apologize for the misunderstanding.

So, to use `teal`, do we first need to add it in https://github.com/wagtail/wagtail/blob/b7beb36df6bc89e6152eae6c7d2dabaee7bd660a/client/src/tokens/colors.js
 
I can't see it already defined in the file. Please correct me if I am wrong.

2023-11-30 19:44 UTC, lb- commented on client/scss/components/_chooser.scss
> +    color: theme('colors.text-button-outline-default');
Teal is the secondary colour. I think we have a secondary-400.

https://github.com/wagtail/wagtail/blob/b7beb36df6bc89e6152eae6c7d2dabaee7bd660a/client/src/tokens/colors.js#L139

2023-11-30 20:48 UTC, rohitsrma commented on client/scss/components/_chooser.scss
> +    color: theme('colors.text-button-outline-default');
Sorry for not clarifying earlier. When I mentioned `teal` I was referring to `teal-200 and 100`. I think it is not currently defined in the file.

2023-11-30 21:15 UTC, lb- commented on client/scss/components/_chooser.scss
> +    color: theme('colors.text-button-outline-default');
Ahh yep. Good call - these shades will probably be needed yes. Thanks for checking.

2023-12-01 11:17 UTC, rohitsrma commented
Thanks @lb- , I have made some changes. Could you please take a look?

2024-01-23 02:11 UTC, lb- approved these changes
@rohitsrma thank you for this.

It looks like https://github.com/wagtail/wagtail/pull/11463 from @thibaudcolas has come in on top and actually resolved a few of these added variables.

Even then though, this still does not fix the problem as the chooser buttons are either the exactly same colour (after #11463) on hover or in your PR still to dark.

For the sake of a solution I will push up a change to your PR that just makes the choosre hover/focus colour use `color: theme('colors.text-link-hover');`

This makes it the same value on light mode (`var(--w-color-secondary-400)`) but means we can use a might lighter colour in dark mode. `var(--w-color-secondary-75)`.

@thibaudcolas  please feel free to do another update if you think this is the wrong way to go.

## Before (with changes from #11463 )

| Dark | Light |
|-|-|
| <img width="549" alt="Screenshot 2024-01-23 at 12 09 49 pm" src="https://github.com/wagtail/wagtail/assets/1396140/8da23bde-3d5d-44b3-9319-6c94a219e54c"> | <img width="549" alt="Screenshot 2024-01-23 at 12 09 33 pm" src="https://github.com/wagtail/wagtail/assets/1396140/089d58b7-f37d-4188-9c25-32a170876e83"> |

## After

| Dark | Light (no change) |
|-|-|
| <img width="616" alt="Screenshot 2024-01-23 at 12 07 51 pm" src="https://github.com/wagtail/wagtail/assets/1396140/89b7fd5f-c3c9-471d-8293-8da534df16a2"> | <img width="600" alt="Screenshot 2024-01-23 at 12 08 08 pm" src="https://github.com/wagtail/wagtail/assets/1396140/2991a6be-057a-42ec-b964-5079990c829f"> |

2024-01-23 02:30 UTC, merged