add way to set default ordering for child pages in wagtail
wagtail/wagtail pull request #11290
Opened 2023-11-29 17:07 UTC by smark-1

Add a way to set the default sort options for all child pages in the wagtail page view.

for example, in the bakerydemo BreadsIndexPage I can now add:

```
class BreadsIndexPage(Page):
   ...
   # defaults to -latest_revision_created_at
   default_order = ''ord" # can be all the valid orderings ('title', 'live', '-live', '-title', ...)
   
   # or can set method get_default_order() for more control
   def get_default_order(self):
      """"
      orders the children of the page by ord (allows reordering the page) if less then 20 child pages
      if 20 or more pages use the default setting
      """
       if Page.objects.child_of(self).count() < 20:
           return 'ord'
       return '-latest_revision_created_at'
 
```

It is possible that there is a way to do it in wagtail already, but I was not able to find it looking through the docs.

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

2023-12-05 18:42 UTC, smark-1 commented
@gasman
I added tests and docs? What else needs to be changed?

2023-12-05 20:46 UTC, lb- commented on wagtail/models/__init__.py
> +    default_order = "-latest_revision_created_at"
Just a small one - could we move this up alongside other class properties?

Maybe just after

```
max_count_per_parent = None
```

2023-12-05 20:48 UTC, lb- commented
@smark-1 this is looking solid now & I have marked as needs review.

Thanks for adding tests & docs.

2023-12-05 22:03 UTC, lb- requested changes
This looks good and works well.

I recommend we rename this whole thing to `get_admin_default_ordering` and `admin_default_ordering` for the attribute.

This aligns with the `get_admin_display_title` approach and helps us differentiate between what's shown in the admin and other queries that may be made on pages.

Additionally, the Page listing index (and Django index views) use the full name `ordering` not `order` so let's use that.

If you could do a rework of this PR with the suggested changes (feel free to tweak) and then the renaming of the methods/attributes (including in docs) I think this would be pretty much good to go.

2023-12-05 22:03 UTC, lb- commented on wagtail/admin/views/pages/listing.py
> +        use it for the default ordering of the child pages
```suggestion
        Use the parent Page's `get_admin_default_ordering` method.
```

Let's keep this short and sweet, no need to re-write what the method is doing, we could even avoid this docstring probably but happy to have it here.

2023-12-06 08:14 UTC, lb- approved these changes
This is looking and working great, thank you @smark-1 

I have one more docs suggestion but will merge this when I rebase.

I will force push to your branch with the commits squashed and with release notes but will wait until a few more UK time-zone team come online in case they have any strong opinions on the naming.

We should be pretty good to go though. We really appreciate you taking the time to document and write tests for this. A pretty awesome first contribution.

I will add you to the contributors list as `Shlomo Markowitz` but please advise if you want a different name listed.

2023-12-06 20:50 UTC, merged

2023-12-06 20:50 UTC, lb- commented
Thank you @smark-1 - this is a really great feature.