Display warning when multiple users edit page
wagtail/wagtail pull request #11355
Opened 2023-12-18 13:10 UTC by NXPY123

Fixes #2565 

Displays warning "Overwriting changes by another user." in confirmation message when saving changes in draft of a page.

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For new features: Has the documentation been updated accordingly?

2024-01-21 03:52 UTC, lb- requested changes
Thanks @NXPY123 - I think this seems good in principle. 

A few suggestions. 

1. We'll need to maybe use a more unique field name for this, something like page_revision_id - just avoids issues where that field may exist on a model named revision 
2. I'd recommend using a warning message instead of success when this scenario happens
3. There'll need to be some unit tests to support this work
4. It might be nice to add a link to the page's revision listing in the message

I'll flag this as needs work, I think once this parts are done there can be a full review from there. 

Thank you!

2024-01-31 02:28 UTC, NXPY123 commented
I'm having a little trouble with making the test. When I do this:
```python
def test_page_edit_post_warns_overwriting_changes(self):
        ## Login as a user with edit permissions and edit the page
        latest_revision = self.child_page.get_latest_revision()
        # Create a new revision
        self.child_page.title = "I've been edited!"
        revision1 = self.child_page.save_revision(previous_revision=latest_revision)
        revision1.publish(previous_revision=latest_revision)
        # Create a new user
        user2 = self.create_superuser(username="user2", password="pass2")
        self.login(username="user2", password="pass2")
        self.child_page.title = "I've been edited again!"
        revision2 = self.child_page.save_revision(previous_revision=latest_revision)
        response = revision2.publish(previous_revision=latest_revision)
```

The id of the latest revision of the page is still the same as the one before `revision1`. But when I print the latest revision it is updated to the new one. Is the ID of the latest revision not updated when we do `save_revision()` and `publish()`? Also is this what happens when we click `Save Draft`? Because the warning seems to be displayed on the local server but it doesn't seem to work in the test.

2024-02-29 11:10 UTC, lb- commented
Thanks @NXPY123  - I think for now we may need to put this on hold.

There is active roadmap development for auto-locking https://github.com/wagtail/roadmap/issues/41 and it seems that there would be a bit of overlap with this (especially how the revision ID is used).

For now I will have to flag this as needs decision until others in the core team are available to see whether this can be adopted as is or instead a different approach is needed.

It's up to you if you want to keep this PR open or close and we can put a note on the issue & roadmap item with this initial implementation idea.

Thanks again for your awesome contributions, I know you added a comment to the original issue before you raised this.

See https://github.com/wagtail/roadmap/issues/41

2024-07-19 12:22 UTC, thibaudcolas commented
👋 we’re ready to proceed with this. We’ve gone back and forth a lot on auto-locking, and ended up switching to an implementation that is 100% compatible with what’s proposed in #2565 and in progress in this pull request.

2025-03-08 05:47 UTC, lb- commented
New PR up to replace this https://github.com/wagtail/wagtail/pull/12839

Thanks for the original work here @NXPY123

2025-03-08 05:47 UTC, closed without merging