Allow admin backend login URL to be customised
wagtail/wagtail pull request #11415
Opened 2024-01-04 16:36 UTC by NXPY123

Resolves #10882 Allows admin backend login URL to be customised

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [x] Run `make lint` from the Wagtail root.
-   [x] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For new features: Has the documentation been updated accordingly?

2024-01-04 17:07 UTC, gasman requested changes
Thanks @NXPY123! I'm satisfied that this is the right approach.

I'd suggest naming the setting `WAGTAILADMIN_LOGIN_URL` rather than `WAGTAILADMIN_USER_LOGIN_URL` - all logins are user logins, so the word 'user' isn't really adding any value here. (I see we do have existing settings with names like `WAGTAILADMIN_USER_LOGIN_FORM`, but I think those were just following the pattern of `WAGTAIL_USER_EDIT_FORM`, where the word "user" is meaningful.)

This setting then just needs documenting in https://github.com/wagtail/wagtail/blob/main/docs/reference/settings.md#user-management.

2024-01-05 12:07 UTC, NXPY123 commented
That does make sense! I've made the changes, can you please review them again? I put the documentation under the User Management section and I'm not sure if it's the right place.

2024-01-16 23:56 UTC, gasman commented
Thanks @NXPY123! Merged in 3faeabb4d7afea3c1a0e18635cf70be5f9011aaf - have just made a minor tweak to the documentation wording to remove the mention of `wagtailadmin_login` (a Wagtail site dev generally won't have any reason to work directly with the admin URL routes, so that reference won't be meaningful to them).

2024-01-16 23:56 UTC, closed without merging

2024-01-17 03:46 UTC, NXPY123 commented
Was the PR merged? It's showing it was closed with unmerged commits.

2024-01-17 04:36 UTC, lb- commented
@NXPY123 yes it was merged. It just was merged via git directly instead of using the GitHub merge feature. 

See https://github.com/wagtail/wagtail/commit/3faeabb4d7afea3c1a0e18635cf70be5f9011aaf

2024-01-17 05:32 UTC, NXPY123 commented
Oh okayy got it! Thanks 🙌