updated the anchor sizes
wagtail/wagtail pull request #11443
Opened 2024-01-11 08:18 UTC by nandini584

Fixes 

#11411 fixed the size of anchors to 24*24
Added the width and height to ```w-panel__anchor--suffix```

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

2024-01-17 22:04 UTC, lb- requested changes
@nandini584 sorry but this is not quite right.

1. You are adding height/widths to the anchor when they are set to display: none, this means that the size change will never be used.
2. This appears to adjust the anchor but the buttons are also too small.

Here's the recommended change, I have not fully tested but encourage you to do test this also and add screenshots to your updated PR.

Here we change the anchor AND the toggles sizing to be one size across mobile and desktop, removing the need for the breakpoint.

<img width="836" alt="Screenshot 2024-01-18 at 8 03 17 am" src="https://github.com/wagtail/wagtail/assets/1396140/c03db6e6-34c6-4d5c-ae5c-856bfcbd2e72">

2024-01-18 08:22 UTC, nandini584 commented
Thanks for the review, I will do the changes.

2024-01-18 17:05 UTC, nandini584 commented
![Screenshot 2024-01-18 221810](https://github.com/wagtail/wagtail/assets/117419442/d5e8cdb9-122f-45c3-b99e-64daec89345b)

I have updated the PR as per the changes you recommended and tested it out.

2024-01-19 02:01 UTC, lb- requested changes
Thanks. Please can you clean up the original approach also. Just add new commits that remove the original changes, no need for a new PR.

2024-01-19 02:01 UTC, lb- commented on client/scss/components/_panel.scss
> +    width: $header-anchor-size;
As per previous feedback, adding sizes here when we do not show it is not required. Please remove these width and height properties.

2024-01-19 02:01 UTC, lb- commented on client/scss/components/forms/_nested-panel.scss
> +    height: $header-anchor-size;
Same here. This is a display none override for a specific breakpoint, adding width and height here will do nothing. Please remove.

2024-01-19 02:01 UTC, lb- commented on client/scss/components/forms/_nested-panel.scss
> +$header-anchor-size: theme('spacing.4');
```suggestion
```

Should not be required.

2024-01-20 11:45 UTC, lb- approved these changes
Thanks @nandini584  this change fixes the problem, I will remove the unwanted changes when I merge this in.

Just a reminder to keep a detailed eye on changes and the original issue when submitting a PR. If you have not validated the original bug and fully understand it before making a code change, it will be really hard for you to know if you have fixed it.

## Validation screenshots

### Before `20x20`

<img width="1567" alt="Screenshot 2024-01-20 at 9 43 32 pm" src="https://github.com/wagtail/wagtail/assets/1396140/93937132-3ed1-4f8e-88b5-1a46f07b00fd">

### After `24x24`

<img width="1566" alt="Screenshot 2024-01-20 at 9 43 47 pm" src="https://github.com/wagtail/wagtail/assets/1396140/82c69b90-be02-4284-817f-8a17a1927344">

2024-01-20 12:01 UTC, merged

2024-01-22 06:37 UTC, nandini584 commented
Thankyou so much, I will keep this in mind, Is there any thing else left in the PR?

2024-01-22 06:47 UTC, lb- commented
Thanks @nandini584  I just realised I did not delete the variable `$header-button-size-mobile` from the top of `client/scss/components/_panel.scss`

Would you mind doing a new PR that just removes it.

While this will not cause an error it's nice to remove unused variables, sorry I missed it when I was cleaning up the PR.

2024-01-22 07:11 UTC, nandini584 commented
Sure I will do it...