fix: enum eslint error
wagtail/wagtail pull request #11519
Opened 2024-01-23 14:12 UTC by kituuu

Fixes #...

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

2024-01-23 16:28 UTC, gasman commented
Hi @kituuu - thanks for the PR.
Can you give some more details about the reasoning for this change, please? It looks like this is just moving the instruction for ignoring the `no-shadow` rule, from OrderableController.ts to .eslintrc.js where it's less meaningful.

2024-01-23 16:37 UTC, kituuu commented
Yesterday @lb- asked me to check for an eslint rules check as it failed for Direction enum. He asked me to make changes in eslint rules  to pass the eslint test without the ignore comment on oderablecontroller. If there's a better way please let me know.

2024-01-23 20:02 UTC, lb- requested changes
Thanks @kituuu - however as per comments from @gasman this is just moving the 'ignoring' around. 

My understanding was that we would just disable the no show rule for .ts files only and enable the ts lint equivalent

See https://github.com/typescript-eslint/typescript-eslint/issues/2483#issuecomment-687095358

We have this package already 
https://github.com/wagtail/wagtail/blob/e1693ee5db1f34d6c31fd3f643b53365b44c2087/package.json#L72


I anticipate we would need a new overrides block for TS. 

For example...

```
overrides: [
    // Rules that are for TypeScript files only
    {
      files: ['.ts'],
      rules: {
```

2024-01-23 20:04 UTC, lb- commented
Also. When you get a chance can you update the description to something a bit more detailed. The idea of the template content is to help guide this. 

The description is an important part to help reviewers understand what you're doing and why.

Thanks again for wanting to help here, hopefully when this is all working it will mean that we can easily use Enums in all TS code.

2024-01-23 21:04 UTC, kituuu commented
Sure, I will look into this. And make the desired changes ASAP.

2024-02-02 21:23 UTC, lb- approved these changes
Thank you @kituuu this works geat.

Just a reminder to run Prettier locally, the `"` should be changed to `'`, I can fix this up when I merge though.

Additionally, I will move the new rule to the top of the rule overrides.

Thank you for processing this.

2024-02-02 21:35 UTC, merged