Fix Links of RichTextField in CustomImage
wagtail/wagtail pull request #11571
Opened 2024-02-01 20:03 UTC by elhussienalmasri

Fixes #11421 , Fixes #10377
these two issues  are  same ,
these issues just because draftail `RichTextField ` not have access to ` chooserUrls` and other scripts inside` _editor_js.html`  to complete its initialization(this issue not only for Links but also for others widget chooser like Documents  ), so this error occur
Before:

![Before](https://github.com/wagtail/wagtail/assets/90080237/f1ad0c92-ec22-4bc5-ae13-2e2fda5449f0)

now `RichTextField` simply have access to ` _editor_js.html`  and could have `Links` and other choosers like `Documents`  and `Images ` as show below
After:  

![After](https://github.com/wagtail/wagtail/assets/90080237/8c4d22a8-3063-475d-aaac-9819ecb0b623)

_Please check the following:_

-   ✅ Do the tests still pass?[^1]
-   ✅ Does the code comply with the style guide?
    -   ✅ Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

2024-02-01 22:51 UTC, lb- requested changes
This fixes the images edit view (thank you!). This fixes the problem for editing existing images but has a few gaps.

Can you look at a similar fix for the following files as part of this PR;

1. Multiple add image (the drag & drop images) `wagtail/images/templates/wagtailimages/multiple/add.html`
2. Single add image (a standalone view, rarely used as it needs a manual URL entering but should be updated) `wagtail/images/templates/wagtailimages/images/add.html`
3. Maybe: Similar changes for custom documents (or that could be a separate PR).

## Additional context

I think that we are trying to avoid bringing in all these globals and config overrides to every single page - see https://github.com/wagtail/wagtail/issues/2936 - However, I do not see another way to fix this problem at this time.

We are also actively exploring better approaches to just window.[global] values everywhere because it causes hard to debug problems and also is not CSP compliant. See https://github.com/wagtail/wagtail/issues/9771 & another open PR https://github.com/wagtail/wagtail/pull/11166

We may also take a different tact with chooser URLs though, ideas welcome (add a comment on #9771 ).

2024-02-01 22:56 UTC, lb- commented
Maybe it's worth trying to fix this properly and look at a different way to get the chooser URLs into the right widgets without relying on globals.

@elhussienalmasri let me know if you are up for this?

I can raise an issue specific to this with a few pointers.

@gasman  - maybe that `register_setting` Python API approach or a more refined global js config approach. Discussed on https://github.com/wagtail/wagtail/issues/9771

2024-02-01 23:21 UTC, elhussienalmasri commented
Thanks for replay @lb-  , yes I just see `_editor_js.html` in more than file and make like it and not see #2936 .
so I just have one question if the problem only related to `chooserUrls` , or related to other `scripts` 
in `_editor_js.html`.
so if only related to `chooserUrls` , might send it to frontend and include other scripts in `wagtailimages/images/edit.html`.
and only include it if the customImage has `RichTextField` .

2024-02-02 04:26 UTC, elhussienalmasri commented
there is simple solution may solve #2936  , and also the other gabs of this PR ,
 if there is base template or a template that `RichTextField` in all pages have access to ,
 so simply enclude `_editor_js.html` in one file and remove the remaining .
 I don ,t try this solution may solve or not .

2024-02-02 08:58 UTC, lb- commented
OK, here's some results of an initial investigation.

* It looks like the chooserUrls global is only used by Draftail, when choosers are in StreamField blocks OR plain widgets, the URL is provided from Python to the element (either via a data attribute or Telepath values).
* We could look at passing some options (with the chooser URLs) from Python down through to Draftail via wagtail/admin/rich_text/editors/draftail/__init__.py (see `get_context` and also `js_args` in the Telepath adaptor.
* Pretty sure all choosers now use the base chooser viewset (wagtail/admin/viewsets/chooser.py), so we could extend that class' `on_register` method to maybe set up some way to have a Python register of chooser URLs.
* The draftail options would get this value, pass it to `initEditor` -> client/src/components/Draftail/index.js
* Then in each Draftail's Modal Workflow source (e.g. DocumentModalWorkflowSource), we would somehow read the chooser URL options.

Just dumping here for feedback from @gasman  or @thibaudcolas  - If this is not suitable for some reason let me know.

I can then do a bit more digging and raise a new issue to remove the need for `window.chooserUrls` globals, which will also be a big win for future CSP compliance.

2024-02-02 14:26 UTC, elhussienalmasri commented
Great , I will start working on this smart solution.

2024-02-05 00:52 UTC, lb- commented
@elhussienalmasri - issue raised https://github.com/wagtail/wagtail/issues/11586

2024-02-05 05:33 UTC, elhussienalmasri commented
just my update on this issue , already this issue solved and the gabs of this issue like
 Multiple add image and also the the problem of  used ` _editor_js.html` every where ,
just as I said include  ` _editor_js.html` in  base template , but really I don ,t know if 
` _editor_js.html` included in base template good or not , just this solution will decrease the 
numbers the usage of  ` _editor_js.html`  but may be page not used `RichTextField` and still 
 ` _editor_js.html` exist , but this problem just check if page used `RichTextField` . if used include ` _editor_js.html` ,
 else not include it. but I don ,t know the other reason may good or not.
but if this solution not suitable for 
any reason just to solve the gabs of this issue like Multiple add image  just include  ` _editor_js.html` in the template as 
this solution. 
I will return to this issue asap after the another issue.

2024-02-05 23:01 UTC, lb- commented
Thanks @gasman  - that helps a lot. I have added your comment to the new issue raised https://github.com/wagtail/wagtail/issues/11586#issuecomment-1928459700

2024-02-05 23:35 UTC, elhussienalmasri commented
Thanks @gasman  , sure I will follow this valuable instructions ,
with also valuable instructions from @lb- .

2024-02-18 20:49 UTC, lb- commented
Closing this in favour of the newer approach in https://github.com/wagtail/wagtail/issues/11586

2024-02-18 20:49 UTC, closed without merging