Fix - Ensure that modal tabs width are not impacted by side panel opening
wagtail/wagtail pull request #11703
Opened 2024-02-28 10:35 UTC by lb-

This bug was reported in Slack, it appears that https://github.com/wagtail/wagtail/pull/11150 introduced a regression where the side panel opening would cause the tab-content within modals to also be impacted.

https://wagtailcms.slack.com/archives/C81FGJR2S/p1708033342014629
<img width="965" alt="Screenshot 2024-02-28 at 8 34 54 pm" src="https://github.com/wagtail/wagtail/assets/1396140/1356e4aa-c277-4199-b69a-9e6d59ec3853">

Ideally we would better isolate these classes but for now here's a simple fix to this problem.

Note: The extra padding on the table columns is unrelated, probably needs to be fixed also but I will flag that in a different thread.

## To reproduce the bug

1. Open any page editing view
2. Open a wide side panel (e.g. the preview panel)
3. Open a chooser modal, one with tabs in it such as the links chooser
4. Observe the content is not the full width of the modal
5. Close the chooser, close the side panel and then re-open the chooser
6. Observe the content is now the full width of the modal

## Screenshots

### Before

<img width="1652" alt="Screenshot 2024-02-28 at 8 25 56 pm" src="https://github.com/wagtail/wagtail/assets/1396140/fc6db5b1-01e6-46ba-a1b5-fb856fdbad4e">

### After

<img width="1650" alt="Screenshot 2024-02-28 at 8 29 21 pm" src="https://github.com/wagtail/wagtail/assets/1396140/000dba0d-3844-4eb6-b305-024f48b07a14">

2024-02-28 12:56 UTC, laymonage requested changes
Thanks! While this does fix the issue, it seems there might be a better approach to fix this. I've added details in the comments.

2024-02-28 20:36 UTC, lb- commented
Thanks @laymonage much better, I have applied your recommendation but with a slightly different approach, nesting things inside the `w-form-width` for easier maintenance. We use a similar approach, using `at-root` for items relating to the slim header.

2024-02-29 11:14 UTC, lb- commented
As per convo with Thibaud/Sage - we should try to align this with our updated Sass usage guidelines https://docs.wagtail.org/en/stable/contributing/ui_guidelines.html#sass-usage - keep Sass features to a minimum.

2024-02-29 11:25 UTC, lb- commented
Updated @laymonage

2024-02-29 11:37 UTC, laymonage approved these changes

2024-02-29 11:41 UTC, laymonage approved these changes
Tested on Chrome 121, Firefox 123, and Safari 17.3.1 on macOS 14.3.1 and this does fix the issue. I love that this now works for snippets too! I also didn't notice any issues with the scheduled publishing dialog (which is teleported to be inside the `<form>`), so I think we're all good here. Thanks!

2024-02-29 11:52 UTC, merged

2024-02-29 11:55 UTC, laymonage commented
- `main`: 07d6acf
- `stable/6.0.x`: 6c9589ff94b94ee2416917d147143023c73a0572

2024-03-01 07:28 UTC, lb- commented
Thanks