Fixes #11888/spacing issue in ListBlock nested blocks
wagtail/wagtail pull request #11934
Opened 2024-05-07 17:43 UTC by TARishabh

_Please describe the problem you're fixing here. Include the issue number, if applicable._
Resolves #11888

This PR addresses the spacing problem encountered in ListBlock when dealing with nested blocks. It ensures that the spacing between nested blocks is consistent, thereby improving clarity and visual presentation.

Changes Made:
- Removed margin-bottom in CSS styles to maintain consistent spacing

Testing:
- Tested the fix locally to ensure proper spacing behavior
- Ran existing unit tests to verify no regressions

Please review and merge. Thank you!

2024-05-08 08:46 UTC, TARishabh commented
Before:

![wagtail_problem](https://github.com/wagtail/wagtail/assets/127947846/bb060599-610b-418f-90a7-19c9eac8bd03)

![wagtail_problem2](https://github.com/wagtail/wagtail/assets/127947846/2bc278a6-e66d-4d2c-ac00-bcc3e1ed7daf)

After:
![wagtail_fixed](https://github.com/wagtail/wagtail/assets/127947846/8282c054-7828-43bc-bfad-244a91afbe15)

now there is no extra spacing over the button

2024-09-28 06:55 UTC, TARishabh commented
@lb- PTAL !

2024-11-29 22:54 UTC, lb- requested changes
@TARishabh  I think this could use a bit more work, I have a suggestion but try to look at other ways we could maybe refine the styling here.
Removing the gap under the help block makes the help block feel way too close to the content.

2024-11-29 22:54 UTC, lb- commented on client/src/components/StreamField/StreamField.scss
> -  margin-bottom: theme('spacing.6');
@TARishabh  this kind of helps but does not really fix the problem.

I would recommend we only 'reduce' this value, maybe to spacing.4 or spacing.3

Instead we should try to find a way to make the list block items have a margin under them I think.

Maybe if you adjust this file
https://github.com/wagtail/wagtail/blob/839193ff3c9381e35e39cc12f199c414d2684526/client/src/components/StreamField/blocks/ListBlock.js#L99-L101

with something like this

```diff
--      <div class="${h(this.blockDef.meta.classname || '')}">
++      <div class="${['w-mb-6', h(this.blockDef.meta.classname || '')].filter(Boolean).join(' ')}">
```

Then with these two suggestions we get a nicer visual gap between the ListBlock items.


<img width="1800" alt="Screenshot 2024-11-30 at 8 53 35 AM" src="https://github.com/user-attachments/assets/d306ec40-2983-4a78-be1f-a81fc5d39c92">

2025-01-14 09:58 UTC, thibaudcolas approved these changes
Thank you! This is the correct line to change, and @lb-’s comment to only reduce the spacing rather than remove it makes sense to me, so I think we can approve and merge with that change.

For future ref – this `.c-sf-help` code seems like it could be removed with a bit more work. It looks like we would get the same spacing as other help text by just converting StreamField’s rendering to use `<p class="help">` rather than `<div class="help">`.

2025-01-14 10:00 UTC, merged