Add admin urls to docs - #11963
wagtail/wagtail pull request #11965
Opened 2024-05-21 00:21 UTC by smark-1

This adds documentation about getting URLs for some of the most common admin views #11963.
Snippets pages and Images are all documented slightly differently. I am not sure which is the best design.

2024-06-18 01:09 UTC, smark-1 reviewed
I removed the bullet points

2024-06-27 08:23 UTC, zerolab requested changes
A few tidy ups neeeded, then I think this is good to go.

Aside: see https://wagtail--11965.org.readthedocs.build/en/11965/extending/admin_views.html#adminurlfinder for the rendered view

2024-06-27 08:23 UTC, zerolab commented on docs/extending/admin_views.md
> +```{code-block} python
```suggestion
```python
```

2024-06-27 08:23 UTC, zerolab commented on docs/extending/admin_views.md
> +In python you can use `MySnippet.get_url_name(view_name)` to get the name of the snippet view.
```suggestion
In Python, you can use `MySnippet.get_url_name(view_name)` to get the name of the snippet view.
```

2024-06-27 08:23 UTC, zerolab commented on docs/extending/admin_views.md
> +```{code-block} html
```suggestion
```html+django
```

2024-06-27 08:23 UTC, zerolab commented on docs/extending/admin_views.md
> +For example linking the BreadTypeSnippet in the bakery demo would look like this
```suggestion
For example linking the `BreadTypeSnippet` in the bakery demo would look like this
```

2024-06-27 08:23 UTC, zerolab commented on docs/extending/admin_views.md
> +In a template the snippets url names by default are wagtailsnippets_{app_label}_{model_name}:{list/edit/inspect/copy/delete}
```suggestion
In a template the snippets url names by default are `wagtailsnippets_{app_label}_{model_name}:{list/edit/inspect/copy/delete}`
```

2024-06-27 08:23 UTC, zerolab commented on docs/extending/admin_views.md
> +```html
```suggestion

```html+django
```

2024-06-27 08:23 UTC, zerolab commented on docs/extending/admin_views.md
> +```html
```suggestion

```html+django
```

2024-06-27 08:23 UTC, zerolab commented on docs/extending/admin_views.md
> +```html
```suggestion

```html+django
```

2024-06-27 08:23 UTC, zerolab commented on docs/extending/admin_views.md
> +```html
```suggestion
```html+django
```

2024-06-27 08:23 UTC, zerolab commented on docs/extending/admin_views.md
> +```html
```suggestion+django
```html
```

2024-06-27 08:23 UTC, zerolab commented on docs/extending/admin_views.md
> +```html
```suggestion
```html+django
```

2024-06-27 08:23 UTC, zerolab commented on docs/extending/admin_views.md
> +```html
```suggestion
```html+django
```

2024-06-27 08:23 UTC, zerolab commented on docs/extending/admin_views.md
> +```html
```suggestion
```html+django
```

2024-06-27 08:23 UTC, zerolab commented on docs/extending/admin_views.md
> +```html
```suggestion

```html+django
```

2024-06-27 08:23 UTC, zerolab commented on docs/extending/admin_views.md
> +```html
```suggestion
```html+django
```

2024-06-27 16:49 UTC, smark-1 reviewed
update copy page docs

2024-06-27 18:15 UTC, zerolab commented on docs/extending/admin_views.md
> +For example linking the `BreadTypeSnippet` in the bakery demo would look like this
How about this?

```suggestion

### Snippets

We will use `BreadTypeSnippet` from the [Wagtail Bakery demo](https://github.com/wagtail/bakerydemo/) as an example.

In Python, you can use {meth}`~wagtail.admin.viewsets.base.ViewSet.get_url_name` to get the name of the snippet view URL. (e.g. `BreadTypeSnippet.get_url_name("list")`)


In templates, the snippet URL names follow the following pattern: `wagtailsnippets_{app_label}_{model_name}:{list/edit/inspect/copy/delete}`

So the `BreadTypeSnippet` URLs would look like:
```

2024-06-27 18:56 UTC, zerolab approved these changes
LGTM. Thank you @smark-1

2024-07-06 04:47 UTC, lb- commented
@zerolab - I'll try to merge this. 

@saevarom - let us know if you want to hold until you have reviewed also.

2024-07-08 20:38 UTC, merged