doc: fix pdf export
wagtail/wagtail pull request #12076
Opened 2024-06-21 13:13 UTC by roipoussiere

Documentation export in pdf was not working. This PR fix this by:

- removing the sphinx build option `-W` (a.k.a `--fail-on-warning`) in conf.py in order to continue the build even if the documentation contains warnings (see #11972) __*__;
- using Xelatex engine in order to support the unicode characters included in the doc;
- configuring the builder to use png images as fallback, since gif images are not supported by the LaTeX engine;
- adding png fallback images for each gif images.

__*__: I also remove the unnecessary `--keep-going`, these two options are opposite.

2024-06-21 16:04 UTC, gasman commented
Thanks @roipoussiere! Just to highlight that the build errors have been addressed in #12044 which is currently awaiting review, so if that gets approved we won't need to remove the `-W` flag.

2024-06-21 16:08 UTC, laymonage reviewed
Thanks for the PR! I haven't fully reviewed it but I just wanted to flag how this relates to #11972, just in case you're wondering if this PR does not get reviewed soon.

2024-06-21 16:08 UTC, laymonage commented on docs/Makefile
> -SPHINXOPTS    = -W --keep-going -n -jauto
I'm pretty sure we want to keep this in the future, so it fails loudly when we have legitimate errors. As you pointed out, we have #11972 to track this, and there's an open PR to fix it in #12044. That being said, I need to review that PR soon before I can review yours, so we can fix both problems. Will do when I find the time... 🙂

2024-07-09 13:38 UTC, roipoussiere commented
Thanks for the review. I added the `--fail-on-warning` sphinx option in the commit.

2024-07-18 23:33 UTC, gasman requested changes

2024-07-18 23:33 UTC, gasman commented on docs/Makefile
> +SPHINXOPTS    = --fail-on-warning -n -jauto
This change is causing the HTML build to fail on my machine:

```sh
$ make html
sphinx-build -b html -d _build/doctrees  --fail-on-warning -n -jauto . _build/html
usage: sphinx-build [OPTIONS] SOURCEDIR OUTPUTDIR [FILENAMES...]
sphinx-build: error: unrecognized arguments: --fail-on-warning
make: *** [html] Error 2
```

2024-07-18 23:37 UTC, gasman commented on docs/Makefile
> +SPHINXOPTS    = --fail-on-warning -n -jauto
Looks like the long option was added in Sphinx 7.3, so this just needs a version bump in setup.py.

2024-07-19 00:31 UTC, gasman commented
Merged in 5a8c33f34a36a038ab8cdaedddf19fe4d5750cf5 (with Sphinx version bump to >=7.3 added).

@roipoussiere - I've added you to the contributors list as "Nathanaël" - let me know if you'd like this changed to a full name.

2024-07-19 00:31 UTC, closed without merging

2024-07-26 08:41 UTC, roipoussiere commented
Thanks! If it's not too late you can add my last name as well (Nathanaël Jourdane) for consistency with other contributors in the list.

2024-07-26 09:35 UTC, gasman commented
No problem! Updated in efc419a3a1 (main) and fe9a2c493f8479e82adc80797137b723f2ce95a3 (stable/6.2.x).