Modified max-width
wagtail/wagtail pull request #12336
Opened 2024-09-18 17:07 UTC by Shreshth-Srivastava

Fixes #12299

The input field was overflowing its parent wrapper which made the design asymmetrical. To fix this, I changed "width: auto" to "max-width: 100%;".

2024-09-19 17:38 UTC, thibaudcolas commented
Thank you @Shreshth-Srivastava, could you expand on how you’ve tested this and maybe share a screenshot of the results?

I see in the issue the suggestion was to _add_ `max-width: 100%`, not replace `width: auto` with it.

2024-09-19 19:30 UTC, Shreshth-Srivastava commented
Tests:

1. Default

![Default](https://github.com/user-attachments/assets/12dd5891-4c73-4e4e-a833-75f7c52377a2)

2. Not using width and max-width

![1](https://github.com/user-attachments/assets/2a1e2bef-0de7-4070-8e1f-9a47461e1145)

3. Only using max-width:

![2](https://github.com/user-attachments/assets/ce9df2d1-d956-41f8-afec-26c17eeb7dbb)

4. Using both width and max-width:

![3](https://github.com/user-attachments/assets/09c7fca4-331b-44a4-bada-4dc68be0efa0)

2024-09-21 15:03 UTC, Rohit-Singh-01 commented
so the issue is resolved ?? why is it still open ??

2024-09-23 14:32 UTC, laymonage requested changes
Thanks, but this has the same problem as #12318.

2024-09-23 14:32 UTC, laymonage commented on client/scss/components/forms/_input-text.scss
> +    max-width: 100%;
Same as https://github.com/wagtail/wagtail/pull/12318#discussion_r1761315074,

This forces all date/time fields to always take up the full width of the parent, which is not what we want:

<img width="1168" alt="image" src="https://github.com/user-attachments/assets/d6905c78-af91-400b-91fe-fecbbd1e5080">

The issue's description specifically says **adding** `max-width`, not replacing the existing `width: auto`.

2024-09-23 14:32 UTC, closed without merging

2024-09-23 14:32 UTC, laymonage commented
Closing as invalid - please feel free to open a new PR with the changes as requested.