Update _dropdown.scss
wagtail/wagtail pull request #12365
Opened 2024-09-26 19:03 UTC by Ishwari8104

Action buttons are easy to miss in list views for high contrast mode issue

2024-09-26 19:24 UTC, laymonage requested changes
Thanks for the PR!

2024-09-26 19:24 UTC, laymonage commented on client/scss/components/_dropdown.scss
> +}
This is currently throwing a syntax error due to the extraneous closing curly brace.

```suggestion
```

Also, could you add some screenshots to verify the issue you are fixing?

2024-09-29 06:11 UTC, lb- commented
<img width="668" alt="Screenshot 2024-09-29 at 4 10 58 pm" src="https://github.com/user-attachments/assets/75919c28-fe46-4f22-8450-ff71913432b9">

I can confirm this issue exists, see the '...' button toggle.

2024-09-29 06:27 UTC, lb- commented
@Ishwari8104  thanks for flagging this, I opted for a simpler fix (just adding a 2px transparent border), this will ensure the border gets colours for high contrast mode.

**Screenshot after fix**


<img width="623" alt="Screenshot 2024-09-29 at 4 19 34 pm" src="https://github.com/user-attachments/assets/ebd3a954-8c6f-4477-a0a7-2e1da0574ac8">


I have added you to the contributors list, I could not find a name so have used `Ishwari8104`, let me know if you want a different name listed.

A few suggestions for future PRs

1. Have a full read through our first contribution guide, it covers a lot of common learning items that can help your PRs https://docs.wagtail.org/en/stable/contributing/first_contribution_guide.html
2. We strongly recommend including a screenshot of the problem you encountered (especially if it's a UI/ High contrast item), this makes reviewing way faster for us.
3. Always be sure to check the linting / formatting locally before doing a PR, it will help the code run through the CI fully.

However, we understand it's a big codebase to get your head around so well done on finding the place to fix this and submit your first contribution to Wagtail.

Thanks for making things better for high contrast users.

2024-09-29 06:27 UTC, lb- approved these changes

2024-09-29 06:37 UTC, merged