Fix column width overflow in document chooser for long filenames
wagtail/wagtail pull request #12390
Opened 2024-10-03 17:21 UTC by Sumitsh28

This PR addresses issue [#12357](https://github.com/wagtail/wagtail/issues/12357), where long filenames without spaces cause the column widths of the document chooser table to stretch, making it difficult to read the document titles, especially on narrower browser windows.

### Steps to Reproduce: 
  1. Upload a document with a long filename (without spaces).
  2. Edit a page that uses the document chooser.
  3. Open the document chooser modal in a narrow browser window.
  4. Observe that the table columns are stretched due to long filenames.

### Before 
![Screenshot - 2024-10-03T224331 059](https://github.com/user-attachments/assets/d809b3a1-fed7-46e6-8a09-ec8d423c220a)

### After
![Screenshot - 2024-10-03T224536 953](https://github.com/user-attachments/assets/23708cfe-ba6d-476c-8412-d07a95e349ba)

2024-10-04 09:28 UTC, lb- commented
Thanks for adding screenshots

2024-10-10 20:21 UTC, gasman requested changes
Thanks @Sumitsh28! According to https://developer.mozilla.org/en-US/docs/Web/CSS/word-break, `word-break: break-word` is deprecated, and it sounds like `overflow-wrap: anywhere` is the new preferred way to achieve the same thing - could you give that a try, please?

2024-10-10 21:00 UTC, lb- commented
We probably should add this to our Stylelint checks at some point. I will raise an issue.

2024-10-20 12:35 UTC, gasman commented
Superseded by #12430 and #12431.

2024-10-20 12:35 UTC, closed without merging