'reference/12435 minor update in the text for the highlighted section as code'
wagtail/wagtail pull request #12438
Opened 2024-10-21 14:42 UTC by Srishti-j18

Fixed #12435 
- [x] Used double backticks everywhere on `wagtail/wagtail/models/_init_.py` so that text appears highlighted as code.

2024-10-21 15:24 UTC, thibaudcolas commented
@Srishti-j18 thank you for giving this a go. There are a lot more changes here than your PR description suggests. Please take a moment to review your own submission before opening a pull request, or mark it as draft if you’re not sure.

2024-10-21 15:28 UTC, Srishti-j18 commented
Hi @thibaudcolas,

I raised two pull requests for this issue and completed the other five tasks in that separate pull request (https://github.com/wagtail/wagtail/pull/12437).

2024-10-21 15:37 UTC, laymonage commented
> I raised two pull requests for this issue and completed the other five tasks in that separate pull request (#12437). I created a separate pull request for the sixth task because it may require some changes if needed.

If that's the case, then the branches should be completely separate, i.e. the branch for this PR should not contain the changes for that other PR. It looks like the changes in this PR can be applied separately from that other one, so it should be possible to make this branch independent.

2024-10-21 17:04 UTC, Srishti-j18 commented
> > I raised two pull requests for this issue and completed the other five tasks in that separate pull request (#12437). I created a separate pull request for the sixth task because it may require some changes if needed.
> 
> If that's the case, then the branches should be completely separate, i.e. the branch for this PR should not contain the changes for that other PR. It looks like the changes in this PR can be applied separately from that other one, so it should be possible to make this branch independent.

My bad, I have removed the changes from this PR that overlapped with the other PR.
Kindly review both my PRs: [#12437](https://github.com/wagtail/wagtail/pull/12437) and [#12438](https://github.com/wagtail/wagtail/pull/12438) for the issue: [#12435](https://github.com/wagtail/wagtail/issues/12435).
Apologies for the confusion.

2024-10-27 21:53 UTC, lb- requested changes
@Srishti-j18  thanks for this, I will rebase and merge with a few fixes.

Please note that the format for the Python DocStrings is RST, and adding double backticks is important for formatting values as `pre` text.

however, your PR included a lot of additional double backticks for things such as 

```
:meth:``
:attr:``
```

This is incorrect, and will actually break the formatting.

I know it's a bit confusing compared to Markdown, but in the future be sure to build your docs locally and check your changes before preparing a PR.

Thank you though for getting this updated, I will clean up and merge shortly.

2024-10-27 21:55 UTC, lb- commented on wagtail/models/__init__.py
> +                    "The ``PASSWORD_REQUIRED_TEMPLATE`` setting is deprecated - use ``WAGTAIL_PASSWORD_REQUIRED_TEMPLATE`` instead.",
No need to add double backticks to errors/warnings, this goes straight to stdout/console and is not needing to be formatted.

2024-10-27 22:21 UTC, lb- approved these changes
Thanks for getting this started @Srishti-j18  - looking much better now.

![Screenshot 2024-10-28 at 8 21 08 AM](https://github.com/user-attachments/assets/fb576109-4e4c-43a9-9614-c2ca10b950f8)

2024-10-27 22:34 UTC, merged

2024-10-28 17:20 UTC, Srishti-j18 commented
> @Srishti-j18 thanks for this, I will rebase and merge with a few fixes.
> 
> Please note that the format for the Python DocStrings is RST, and adding double backticks is important for formatting values as `pre` text.
> 
> however, your PR included a lot of additional double backticks for things such as
> 
> ```
> :meth:``
> :attr:``
> ```
> 
> This is incorrect, and will actually break the formatting.
> 
> I know it's a bit confusing compared to Markdown, but in the future be sure to build your docs locally and check your changes before preparing a PR.
> 
> Thank you though for getting this updated, I will clean up and merge shortly.

Apologies for not checking it before making the PR. In the future, I'll keep that in mind.