Updated wagtail keyboard shortcuts for comments
wagtail/wagtail pull request #12679
Opened 2024-12-08 21:50 UTC by dhruvipatel14

_Please describe the problem you're fixing here. Include the issue number, if applicable._

Updated wagtail keyboard shortcuts for comments with reference to this discussion: https://github.com/wagtail/wagtail/discussions/12050/#discussioncomment-11489664

**Shortcuts before changes** 

This is also applicable if comments are not enabled

![comment_not_enabled](https://github.com/user-attachments/assets/5e642876-10cd-4dd1-8b60-199af9351760)

**Shortcuts after changes**

If comments are enabled then actions will be updated.

![comments_enabled](https://github.com/user-attachments/assets/d96128b8-c455-448c-a6e1-f5ceed673b9b)

In addition, I’ve made the following changes:
1. Added a separate method to retrieve keyboard shortcuts based on the user’s device.
2. Added a separate method to get Wagtail actions, which returns shortcuts based on specific conditions.
3. Added tests.

2025-03-08 05:05 UTC, lb- requested changes
@dhruvipatel14 looking good as a first pass, thank you for putting this PR together.

I have a recommendation for a different approach for managing the abstraction of the 'keyboard labels generation'.

Alternatively, maybe update this PR to focus on the minimal viable changes to add comments, this way we do not need to discuss the abstraction.

It's up to you though, I see where you are trying to improve the code here & thank you. We just need to balance that with the need for changes that are easy to follow & review.

I would love to see us get the added shortcuts documented (for comments), let us know how you want to proceed.

2025-03-08 05:05 UTC, lb- commented on wagtail/admin/templatetags/wagtailadmin_tags.py
> +def get_keyboard_key_by_user_agent(user_agent):
I would recommend we pull this out a bit further and bring it into the admin utils file.

In addition, let's simplify the attribute access names as it's quite difficult to quickly parse visually with the `a/b` format.

In doing this we can probably give the util the full responsibility to read the headers from the provided requests, allowing future enhancements if needed for translations.

Finally, let's return an object that can be accessed as an attribute instead of dict property access. This will enhance the static typing and visual usage when nesting within f string generation.

Here's a proposed update, this would be added to `wagtail/admin/utils.py` and then imported/tested standalone from there. I have also tried to merge everything into one dict generation, instead of two objects, making it easier to avoid bugs when updating things.

```py
import re
from types import SimpleNamespace

# other imports

# other utils

def get_keyboard_key_labels_from_request(request):
    """
    Returns an instance of SimpleNamespace based on the user's keyboard layout
    based on the User-Agent header in the request.

    These are intentionally not translated, as they are key labels that are assumed
    to be consistent across all languages.
    """

    user_agent = request.headers.get("User-Agent", "")
    is_mac_os = re.search(r"Mac|iPod|iPhone|iPad", user_agent)

    labels = {
        "ALT": "⌥" if is_mac_os else "Alt",
        "CMD": "⌘" if is_mac_os else "Ctrl",
        "CTRL": "⌃" if is_mac_os else "Ctrl",  # this is a bit nuanced, not sure how best to set this up
        "DEL": "Delete",
        "ENTER": "Return",
        "ESC": "Esc",
        "SHIFT": "Shift",
        "TAB": "Tab",
    }

    return SimpleNamespace(**labels)
```


We would then use this in the template tag like so...

```py
KEYS = get_keyboard_key_labels_from_request(request)
(_("Copy"), f'{KEYS.CMD} + c'),
```

2025-03-08 05:05 UTC, lb- commented on wagtail/admin/templatetags/wagtailadmin_tags.py
> +def get_wagtail_keyboard_actions(keyboard_keys):
I recommend we just keep this logic within the flow of the existing code, it's a bit messy bring this out only.

I am sure we can abstract things better later if the need arises, pulling out the key label mapping is good enough for now.

Also, minor nitpick, when creating the variable we should keep the tense.

```py
    comments_enable = get_comments_enabled()
```

Should be

```py
    comments_enabled = get_comments_enabled()
```

2025-03-08 20:14 UTC, dhruvipatel14 commented
@lb —Thanks for reviewing this PR. I’ll work on the requested changes and update you.

2025-03-13 22:18 UTC, closed without merging

2025-03-13 22:29 UTC, lb- commented
No problems, feel free to reach out on Slack if you need a hand. Working with git can be a bit tricky and a learning curve. 

Please also cross reference this PR on your new PR and add a comment here then also. Just helps the team track previous comments.

2025-03-13 22:55 UTC, dhruvipatel14 commented
I have incorporated the suggestions in the new PR: https://github.com/wagtail/wagtail/pull/12968

Pardon me for the mess.