Update FieldPanel documentation to encourage use of strings in panel definition
wagtail/wagtail pull request #12697
Opened 2024-12-16 02:08 UTC by unyimeudemy

### Fixes: [#12655](https://github.com/wagtail/wagtail/issues/12655)

### Description: 
This PR updates the [Your first Wagtail](https://docs.wagtail.org/en/stable/getting_started/tutorial.html) site documentation to encourage new developers to define fields as strings instead of using the FieldPanel or InlinePanel object. It also updates the [panel](https://docs.wagtail.org/en/stable/reference/pages/panels.html) documentation to encourage users define fields as strings in panels.

2025-01-02 18:23 UTC, gasman requested changes
Thanks @unyimeudemy! This is pretty close - just needs some changes to the point where we introduce the panel classes.

2025-01-02 18:23 UTC, gasman commented on docs/getting_started/tutorial.md
>          InlinePanel('gallery_images', label="Gallery images"),
`InlinePanel` can be replaced with a plain string too, so we should do that here (i.e. just add `"gallery_images"` to the list). It's not an exact replacement (we lose the label, so the items will be labelled as "Blog page gallery image 1", "Blog page gallery image 2" etc), but it means we avoid introducing the topic of panel classes at the same time as other tricky concepts.

2025-01-02 18:23 UTC, gasman commented on docs/getting_started/tutorial.md
> +Migrate your database by running `python manage.py makemigrations` and `python manage.py migrate`, and then go to your [admin interface](https://guide.wagtail.org/en-latest/concepts/wagtail-interface
Let's avoid saying that things don't look very good. I think we could say:

> Notice that the list of authors is presented as a multiple select box. This is the default representation for a multiple choice field - however, users often find a set of checkboxes to be more familiar and easier to work with.

2025-01-02 18:23 UTC, gasman commented on docs/getting_started/tutorial.md
> +Well, you can improve this by specifying the author field as a panel object of type FieldPanel. This will allow you to pass in the widget argument to change the default look of the list of authors. E
I think it's a bit confusing to suggest replacing _all_ the fields with FieldPanel - people will be wondering why you'd do that when a plain string works. Maybe it'd be better to say:

> We can do this by replacing the definition of `"authors"` in `content_panels` with a `FieldPanel` object. `FieldPanel("authors")` is equivalent to writing `"authors"`, but allows passing additional optional arguments such as `widget`:

Then keep everything else as strings, except for `authors`. (Remember to update the code comment to highlight the fact that we're adding an import for `FieldPanel` in this step.)

2025-01-02 18:23 UTC, gasman commented on docs/_static/images/tutorial/author-list-beautify.png
Please could you recreate these screenshots using the light mode theme, for consistency with the existing screenshots?

2025-01-02 19:00 UTC, unyimeudemy commented
Thank you very much, @gasman. I'll get started on it right away.

2025-01-04 23:13 UTC, unyimeudemy commented on docs/getting_started/tutorial.md
> +# Your first Wagtail site
Done

2025-01-04 23:13 UTC, unyimeudemy commented on docs/getting_started/tutorial.md
> +    content_panels = Page.content_panels + ["body"]
done

2025-01-04 23:13 UTC, unyimeudemy commented on docs/getting_started/tutorial.md
>          InlinePanel('gallery_images', label="Gallery images"),
Done

2025-01-04 23:14 UTC, unyimeudemy commented on docs/getting_started/tutorial.md
> +Migrate your database by running `python manage.py makemigrations` and `python manage.py migrate`, and then go to your [admin interface](https://guide.wagtail.org/en-latest/concepts/wagtail-interface
Done

2025-01-04 23:14 UTC, unyimeudemy commented on docs/getting_started/tutorial.md
> +Well, you can improve this by specifying the author field as a panel object of type FieldPanel. This will allow you to pass in the widget argument to change the default look of the list of authors. E
Done

2025-01-04 23:14 UTC, unyimeudemy commented on docs/_static/images/tutorial/author-list-beautify.png
Done

2025-01-04 23:17 UTC, unyimeudemy commented
Hi @gasman,
All feedback has been implemented. Please let me know if there’s anything else I should address.

Thank you.

2025-01-05 09:23 UTC, unyimeudemy commented on docs/getting_started/tutorial.md
> +    content_panels = Page.content_panels + ["body"]
done

2025-01-06 23:46 UTC, gasman commented
Thanks @unyimeudemy - great work! Have made a few tweaks in f9debd9084ebde44d4c57f8a82dd5628a8958a10 from working through the tutorial, and merged in a2407c002770ab7f50997d37571de3cf43f0d455.

2025-01-06 23:46 UTC, closed without merging