Add created_at as a FilterField to enable sorting in Document search
wagtail/wagtail pull request #12741
Opened 2024-12-29 17:15 UTC by Srishti-j18

Fixes #12627 

There was a bug when sorting the documents by their creation date in the search results.

Before:

https://github.com/user-attachments/assets/30c9fe7d-f207-4226-8582-2bb1b9996d94

After:

https://github.com/user-attachments/assets/55b16bac-1832-4d9f-b882-705759a079c3

2025-01-02 10:30 UTC, laymonage reviewed
Thanks! Could you add a test for this please?

2025-01-02 14:27 UTC, Srishti-j18 commented
Sure

2025-01-03 10:06 UTC, Srishti-j18 commented
Hi , I have added the test. could you please review it .

2025-01-07 14:15 UTC, laymonage requested changes

2025-01-07 14:15 UTC, laymonage commented on wagtail/documents/tests/test_search.py
> +        results = self.search_backend.search(None, models.Document)
I haven't run the test myself, but does this test actually fail if `FilterField("created_at")` was not added? I don't see any line in the test that suggests we're searching, filtering, or sorting by `created_at`. Not sure how this test is related to the bug/fix 🤔 

Also, I could replicate the bug in #12627 even without an Elasticsearch setup, so this test shouldn't rely on Elasticsearch. A better place to write the test might be in this test class: https://github.com/wagtail/wagtail/blob/7a59c9cc207c88ca07622163b428a43b90effc6c/wagtail/documents/tests/test_admin_views.py#L304 (or someplace else in that file)

2025-01-07 16:36 UTC, Srishti-j18 commented on wagtail/documents/tests/test_search.py
> +        results = self.search_backend.search(None, models.Document)
Ok , I'll look into it.

2025-01-10 11:18 UTC, Srishti-j18 commented
Hi @laymonage, I am stuck. Actually, I am not very good at writing tests. Could you please help me?

>Also, I could replicate the bug in https://github.com/wagtail/wagtail/issues/12627 even without an Elasticsearch setup, so this >test shouldn't rely on Elasticsearch. A better place to write the test might be in this test class:

Also, I don't quite understand the point you made about replicating the bug even without an Elasticsearch setup. I changed my branch to` main `to check the bug, and I only see the bug when searching for documents in the search feature.

https://github.com/user-attachments/assets/6e8b5535-3ecc-4e7c-8bbe-02fe68bf0828

Maybe I am not fully aware of Wagtail Elasticsearch. could you please clarify this for me?

2025-01-10 11:41 UTC, laymonage commented
> Also, I don't quite understand the point you made about replicating the bug even without an Elasticsearch setup. I changed my branch to`main`to check the bug, and I only see the bug when searching for documents in the search feature.
> 
> Maybe I am not fully aware of Wagtail Elasticsearch. could you please clarify this for me?

Wagtail's search mechanism supports different search backends: Elasticsearch, database (default), etc. See https://docs.wagtail.org/en/stable/topics/search/backends.html

Searching with elasticsearch requires you to run an Elasticsearch server, install the Python bindings, and configure it in the Django settings:
https://docs.wagtail.org/en/stable/topics/search/backends.html#elasticsearch-backend

The bakerydemo is not set up to use Elasticsearch by default, and the docker-wagtail-develop hasn't got an Elasticsearch setup either (https://github.com/wagtail/docker-wagtail-develop/issues/3).

If you did not do any Elasticsearch setup, then the bakerydemo will default to the database backend. This issue affects all search backends, not just Elasticsearch.

2025-01-11 18:40 UTC, Srishti-j18 commented
Thanks much, Sage! , for providing the details about the search backends. I have modified the test. Please review it..

2025-01-13 11:51 UTC, laymonage reviewed
Thanks @Srishti-j18, this is looking much better! I left a few comments, but I think they're pretty minor. I'll push them to the PR branch and merge it afterwards.

2025-01-13 11:51 UTC, laymonage commented on wagtail/documents/tests/test_admin_views.py
> +        self.assertEqual(documents, [old_doc, doc1, doc2])
To ensure the search works, we should create a document that doesn't have the word "good" in the title and make sure it doesn't show up in the results.

2025-01-13 11:51 UTC, laymonage commented on wagtail/documents/tests/test_admin_views.py
> +        self.assertTrue(documents[0], old_doc)
This should be `assertEqual`. The `self.assertEqual(documents, [old_doc, doc1, doc2])` a few lines above already ensures the first element is the `old_doc` though, so there's no need to check this

```suggestion
```

It would be more useful if we have another `get()` that uses the descending order (`-created_at`) to ensure it works too

2025-01-13 12:12 UTC, laymonage approved these changes

2025-01-13 12:13 UTC, merged

2025-01-13 18:11 UTC, Srishti-j18 commented on wagtail/documents/tests/test_admin_views.py
> +        self.assertTrue(documents[0], old_doc)
> It would be more useful if we have another get() that uses the descending order (-created_at) to ensure it works too

Ok, in future, I'll try to write tests for every possible case.