[RFC 54] Locale management UI
wagtail/wagtail pull request #6245
Opened 2020-07-20 11:34 UTC by kaedroho

2020-09-17 14:41 UTC, gasman requested changes
Looks pretty good - just a minor quibble about the use of `_editor_js.html` (and imports need fixing to placate isort).

2020-09-17 14:41 UTC, gasman commented on wagtail/locales/templates/wagtaillocales/create.html
> +    {% include "wagtailadmin/pages/_editor_js.html" %}
Is this needed?

2020-09-18 08:44 UTC, kaedroho commented on wagtail/locales/templates/wagtaillocales/create.html
> +    {% include "wagtailadmin/pages/_editor_js.html" %}
nope, removed!

2020-09-18 13:42 UTC, gasman commented
Looks like `wagtail.locales.utils.get_locale_usage` isn't playing well with [the one-off invalid model created in `TestSystemChecks`](https://github.com/wagtail/wagtail/blob/738003726900295328f263bfe91686026f70f596/wagtail/core/tests/test_translatablemixin.py#L142) - once that test has run, the model is returned in `get_translatable_models`, causing the subsequent query to fail as it doesn't have a table.

I'm thinking the best way around that is going to be either: find a way to un-register the invalid model after use (which looks a bit messy, involving fiddling around in internal properties of `AppConfig` and clearing the lru_cache on `apps.get_models`), or tweaking the test so that it temporarily modifies a real model from testapp.models rather than creating a new one.

2020-09-21 11:52 UTC, kaedroho commented
@gasman thanks! That issue is fixed now

2020-09-21 11:55 UTC, merged