New topic docs for internationalisation
wagtail/wagtail pull request #6436
Opened 2020-10-05 11:24 UTC by kaedroho

This PR adds new topic-level docs for internationalisation. It covers some explanation about the approach, a how-to guide for initial configuration and some smaller recipe level how to guides.

2020-10-05 12:05 UTC, tomdyson reviewed
Great job @kaedroho!

2020-10-05 12:05 UTC, tomdyson commented on docs/advanced_topics/i18n.rst
> +Next we need to configure the available languages, there are two settings
languages, there -> languages. There

2020-10-05 12:05 UTC, tomdyson commented on docs/advanced_topics/i18n.rst
> +Here is a basic example of how to add linkes between translations of a page.
linkes -> links

2020-10-05 12:05 UTC, tomdyson commented on docs/advanced_topics/i18n.rst
> +All page instnces in Wagtail have a ``.localized`` attribute which fetches the translation
instnces -> instances

2020-10-05 12:05 UTC, tomdyson commented on docs/advanced_topics/i18n.rst
> +onr of them might fit your use case better:
onr -> one

2020-10-05 12:05 UTC, tomdyson commented on docs/advanced_topics/i18n.rst
> +implementation as they use slightly different approches, so there's a chance that
suggest dropping 'there's a chance that'

2020-10-05 12:05 UTC, tomdyson commented on docs/advanced_topics/i18n.rst
> +This is a Django built in tag that gets info about the language of the translation.
built in -> built-in

2020-10-05 12:41 UTC, kaedroho commented on docs/advanced_topics/i18n.rst
> +Translations are linked together in the database so that translations
I don't either... It's amazing how differently things read sometimes the day after you wrote it!

2020-10-15 17:10 UTC, gasman requested changes
Great job! Really clear instructions and explanations here. Just a couple of formatting niggles...

2020-10-16 09:34 UTC, kaedroho commented
Thanks @gasman, issues fixed!

2020-10-16 09:40 UTC, gasman approved these changes

2020-10-16 12:36 UTC, merged