Add locale switchers to page edit, create and listing views
wagtail/wagtail pull request #6460
Opened 2020-10-13 17:14 UTC by kaedroho

This PR implements a new locale switcher component and adds it to the page edit, creation and listing views.

On the page explorer: it shows the language of the current page being explored. This is only hidden when exploring the root page.

![image](https://user-images.githubusercontent.com/1093808/95892995-42f08a00-0d7f-11eb-80d8-ccbcf42cf525.png)

![image](https://user-images.githubusercontent.com/1093808/95893034-4e43b580-0d7f-11eb-8233-a7ea8fd7a30d.png)

On page creation, it shows the translations of the parent page. Changing language here changes the parent page, unless it's the root page which is the only page that can have children in different locales:
![image](https://user-images.githubusercontent.com/1093808/95893180-81864480-0d7f-11eb-9592-bf9ac511d5b6.png)

On pag eedit, this switches between translations of the page
![image](https://user-images.githubusercontent.com/1093808/95893270-a5e22100-0d7f-11eb-8710-b26765d47e42.png)

If there are no translations the styling changes from a selector to an indicator (same in all other places too):
![image](https://user-images.githubusercontent.com/1093808/95893534-d88c1980-0d7f-11eb-83df-deaa8f2b892f.png)

2020-10-13 17:15 UTC, kaedroho commented
TODO:
 - [ ] Tests
 - [ ] Permission checks

2020-10-19 13:36 UTC, gasman requested changes
Looks good to me - just a suggestion to optimise the permission lookups.

2020-10-19 15:06 UTC, kaedroho commented on wagtail/admin/views/pages/edit.py
> +                    if translation.permissions_for_user(self.request.user).can_edit()
Fixed, thanks!

2020-10-19 15:08 UTC, gasman commented on wagtail/admin/views/pages/create.py
> +>>>>>>> 2be049548... Allow pages to be created in any locale at the root level
Please fix this merge conflict :-)

2020-10-19 15:27 UTC, kaedroho commented on wagtail/admin/views/pages/create.py
> +>>>>>>> 2be049548... Allow pages to be created in any locale at the root level
oops!

2020-10-19 15:30 UTC, kaedroho commented on wagtail/admin/views/pages/create.py
> +>>>>>>> 2be049548... Allow pages to be created in any locale at the root level
Fixed, thanks!

2020-10-19 15:42 UTC, gasman approved these changes

2020-10-19 19:15 UTC, merged