Remove max_length form embed url fields
wagtail/wagtail pull request #6502
Opened 2020-11-01 12:56 UTC by allcaps

This PR replaces the URL fields on embeds for an URL fields without `max_length`.

The custom replacement URL field is a subclass of `TextField` and applies the `URLValidator` and in forms uses the `form.URLField`.

* Do the tests still pass? YES
* Does the code comply with the style guide? YES
* For Python changes: Have you added tests to cover the new/fixed behaviour? YES
* For front-end changes: Did you test on all of Wagtail’s supported browsers? N/A
* For new features: Has the documentation been updated accordingly? N/A

2020-11-01 13:38 UTC, allcaps commented
> _mysql_exceptions.OperationalError: (1170, "BLOB/TEXT column 'url' used in key specification without a key length")
https://travis-ci.org/github/wagtail/wagtail/jobs/740595278

2020-11-01 16:06 UTC, ababic commented
Hey @allcaps,

Thank you for starting work on this. The above error is to be expected really. As noted on #1985, mysql has some limitations when it comes to the length of index values. 

In short, what we want to do is:

1. Add `hash = models.CharField(max_length=32, null=True)` as a new model field (and create a migration)
3. Add a reusable function to `wagtail.embeds.embeds` to take care of hashing, e.g.:
    ```
    from hashlib import md5

    get_embed_hash(url, max_width):
        h = md5()
        h.update(url.encode('utf-8'))
        h.update(max_width)
        return h.hexdigest() 
    ```
4. Update [`get_embed()`](https://github.com/wagtail/wagtail/blob/master/wagtail/embeds/embeds.py#L8) to create a `hash` from `url` and `max_width`, and use this to looking existing values, and in the `get_or_create()` method nearer to the end of the `get_embed()`.
5.  Write a data migration to populate the `hash` field value on all existing `Embed` objects, using `builk_update()` to do the saving in batches (e.g. https://github.com/wagtail/wagtail/pull/6164/files#diff-2cac7a6a3576444b76d1ae7c28cdba967ddc3938442e84a14c3d7f5d9d643898)
6. Update the hash field to:  `hash = models.CharField(max_length=32, unique=True)`
7. Change the `url` and `thumbnail_url` fields to use `models.TextField` instead of `models.URLField`(*)
8. Remove the  `unique_together` from the model `Meta`.
7. Generate a final migration.

(*) `Embed` instances are always created by Ajax requests, where there is no way of surfacing validation errors - so, having this validation at the model-level isn't useful. We might as well accept any old string value.

2020-11-01 20:54 UTC, allcaps commented
@ababic Thank you for your detailed plan. I did read your comment and was aware of your preferred solution.

Before I give your preferred solution a try, I wanted to try to swop out `unique_together` for custom code that would stay as close as possible to how unique together works. This is also the reason why I added the form validation. Not because it is needed in Wagtail or not, but because unique_together does raise validation errors in forms. I know it is redundant in the embed scenario. I'm happy to drop form related parts.

I broke MySQL on my dev env, so I'm abusing Travis. I'll fix my dev to keep the noice down.

2020-11-02 17:36 UTC, ababic reviewed
Hi @allcaps. Noticed a couple of bits here. In general - the one thing we lose with this approach is a DB index, which will have an impact on lookup speed at the database level. Maybe that's entirely acceptable though, given often embeds are really looked up from the DB.

2020-11-02 17:36 UTC, ababic commented on wagtail/embeds/models.py
> +        super().clean()
Might it be worth overriding `validate_unique()` instead of clean() here? https://github.com/django/django/blob/master/django/db/models/base.py#L1009

2020-11-02 17:36 UTC, ababic commented on wagtail/embeds/models.py
> +            raise error(_('Embed with this Url and Max width already exists.'))
Would suggest "Embed with this url and max_width value already exists."

2020-11-02 17:36 UTC, ababic commented on wagtail/embeds/models.py
> +    url = URLField()
As mentioned previously, we might as well use `TextField` here and drop the custom field/related tests

2020-11-02 17:36 UTC, ababic commented on wagtail/embeds/tests/test_embeds.py
> +        self.assertEqual(form.errors, {'__all__': ['Embed with this Url and Max width already exists.']})
Could this test be simplified to just call `full_clean()` on an Embed instance?

2020-11-02 17:36 UTC, ababic commented on wagtail/embeds/tests/test_embeds.py
> +        self.assertIsInstance(Embed._meta.get_field("thumbnail_url"), URLField)
This test can be safely removed, I think. It would be very odd indeed for Django to not respect our model field definitions.

2020-11-02 18:33 UTC, gasman requested changes
A problem with emulating unique_together with a validator function is that [the `get_or_create` call in `get_embed`](https://github.com/wagtail/wagtail/blob/330f0dde152ea23ae5072e03508a5d3c15b03bcb/wagtail/embeds/embeds.py#L42) relies on the unique_together constraint - internally Django's get_or_create implementation is more like "try to create but catch the integrity error". Since the embed fetch could take a second or more, there's a real possibility of a race condition where two calls to `get_embed` are made in close succession, they both fail the initial lookup, and end up creating a duplicate entry.

I'd also echo @ababic's comment re losing the database index. Based on https://stackoverflow.com/questions/7830091/django-does-unique-together-imply-db-index-true-in-the-same-way-that-foreignkey it's slightly unclear to me whether unique_together automatically gives you an index, or whether that's only the case for Postgres. If we _don't_ currently have an index in place, we should probably fix that...

I'd favour the hash-based method. I think that would also fix https://github.com/wagtail/wagtail/issues/1745#issuecomment-151131584, which has been open for far too long...

2020-11-02 23:19 UTC, allcaps commented
Okay, that settles it. Stubborn me is convinced. I'll implement the hash with an index plan.

2020-11-03 08:01 UTC, ababic commented
@allcaps stubbornness is underrated :) I'm glad we explored the options here.

2020-12-14 20:37 UTC, allcaps commented
Superseded by https://github.com/wagtail/wagtail/pull/6635

2020-12-14 20:37 UTC, closed without merging