Add Typo3 Theme
wagtail/wagtail pull request #6792
Opened 2021-02-05 10:50 UTC by allcaps

Thanks for contributing to Wagtail! 🎉

Before submitting, please review the contributor guidelines <https://docs.wagtail.io/en/latest/contributing/index.html> and check the following:

* Do the tests still pass? (https://docs.wagtail.io/en/latest/contributing/developing.html#testing)
* Does the code comply with the style guide? (Run `make lint` from the Wagtail root)
* For Python changes: Have you added tests to cover the new/fixed behaviour?
* For front-end changes: Did you test on all of Wagtail’s supported browsers? **Please list the exact versions you tested**.
* For new features: Has the documentation been updated accordingly?

2021-02-05 17:08 UTC, Stormheg commented
Known issue: some automatically generated docs are wrapped in quote blocks. [example](https://wagtail--6792.org.readthedocs.build/en/6792/reference/contrib/routablepage.html#module-wagtail.contrib.routable_page.models)

2021-02-05 23:37 UTC, thibaudcolas commented on .github/workflows/docs.yml
> +          pip install sphinx-typo3-theme==4.4.3
This dependency should be defined in setup.py, as well as `docs/requirements.txt`, and removed from here.

2021-02-05 23:37 UTC, thibaudcolas commented on docs/_static/css/custom.css
> +@-webkit-keyframes bounce {
We should remove this, no need to support Safari 8.

2021-02-05 23:37 UTC, thibaudcolas commented on docs/_static/css/custom.css
> +  -webkit-animation-duration: .5s;
Same for all of these `-webkit-` prefixed styles.

2021-02-05 23:37 UTC, thibaudcolas commented on docs/_templates/layout.html
> +    <meta name="docsearch:version" content="{{ version|striptags|e }}" />
Does this already have support for Algolia DocSearch? 🤔

2021-02-05 23:41 UTC, thibaudcolas commented on docs/_templates/footer.html
> +                    <li><a href="{{ theme_project_home|e }}" title="Home"><span>Home</span></a></li>
Could we remove all those `title` attributes? Realise this isn’t used currently but really these shouldn’t be there.

2021-02-05 23:41 UTC, thibaudcolas commented on docs/_templates/layout.html
> +{%- block linktags %}
I believe all of these are useless.

2021-02-05 23:41 UTC, thibaudcolas commented on docs/_templates/layout.html
> +    <script src="{{ pathto('_static/js/modernizr.min.js', 1) }}"></script>
We should remove this.

2021-02-05 23:41 UTC, thibaudcolas commented on docs/_templates/layout.html
> +<!-- UNIVERSE BAR END -->
We should remove that as well.

2021-02-05 23:41 UTC, thibaudcolas commented on docs/_templates/layout.html
> +                <!-- UNIVERSE BAR END -->
To remove?

2021-02-05 23:41 UTC, thibaudcolas commented on docs/_templates/layout.html
> +  {%- endif %}
To remove.

2021-02-05 23:47 UTC, thibaudcolas commented on docs/conf.py
> +    "project_repository": "https://github.com/wagtail/wagtail/"
```suggestion
    "project_repository": "https://github.com/wagtail/wagtail"
```

2021-02-05 23:47 UTC, thibaudcolas commented on docs/conf.py
> +    "logo_alt": "Wagtail logo",
```suggestion
    "logo_alt": "Wagtail",
```

2021-02-05 23:47 UTC, thibaudcolas commented on docs/conf.py
> +    "logo_title": "Wagtail Documentation",
Should be removed, `alt` is enough.

2021-02-06 00:00 UTC, thibaudcolas requested changes
Issues I spotted in the site’s output only:

- [ ] Edit on GitHub link is incorrect, "https://github.com/unused,%20deprecated/edit/unused,%20deprecated/Documentation/Localization.unused,%20deprecated/index.rst"
- [ ] Code snippets on https://wagtail--6792.org.readthedocs.build/en/6792/getting_started/index.html are impossible to read

2021-02-06 00:03 UTC, allcaps commented on docs/conf.py
> +    "logo_title": "Wagtail Documentation",
I also removed this from HTML.

2021-02-12 12:01 UTC, kaedroho commented
Thanks for this @allcaps!

Would it be possible to squash the commits, or split this into multiple PRs to make it easier to see what's going on?

2021-02-25 19:14 UTC, Stormheg commented
@kaedroho I've extracted the content changes here: https://github.com/wagtail/wagtail/pull/6835

2021-03-28 08:10 UTC, Stormheg commented
Since opening this pull request we have decided to create our own sphinx theme ([sphinx_wagtail_theme](https://github.com/wagtail/sphinx_wagtail_theme)) instead of trying to hack the typo3 theme to fit our needs - which is what this pull request is doing.

Content changes in this PR were merged seperately in https://github.com/wagtail/wagtail/pull/6835

Going to close this in favor of https://github.com/wagtail/wagtail/pull/6930

2021-03-28 08:10 UTC, closed without merging