make Page.current_workflow_state a cached_property
wagtail/wagtail pull request #6878
Opened 2021-03-05 00:06 UTC by femto113

Trying to diagnose general slowness with the page editor I noticed many identical queries being issued in a row of the form

```
SELECT "wagtailcore_workflowstate"."id", "wagtailcore_workflowstate"."page_id", "wagtailcore_workflowstate"."workflow_id", "wagtailcore_workflowstate"."status", "wagtailcore_workflowstate"."created_at", "wagtailcore_workflowstate"."requested_by_id", "wagtailcore_workflowstate"."current_task_state_id" FROM "wagtailcore_workflowstate" WHERE (("wagtailcore_workflowstate"."status" = 'in_progress' OR "wagtailcore_workflowstate"."status" = 'needs_changes') AND "wagtailcore_workflowstate"."page_id" = 105) LIMIT 21;
```

Which is generated by a query in `Page`'s `current_workflow_state` property.  This is compounded by the fact that the `current_workflow_task_state` property can reference it up to 4 times in a single call!  By making `current_workflow_state` a `@cached_property` the total number of queries is reduced dramatically.  There was also a very similar query used by the `workflow_in_progress` query, so that property has been rewritten to reuse the `current_workflow_state` rather than issuing its own query.

I don't see any obvious reason why this should break anything (assuming the page's workflowstate won't be changing in the middle of a request) and the core tests pass, but it's conceivable some explicit cache invalidation may need to be handled somewhere.

2021-03-05 09:56 UTC, gasman commented
Thanks @femto113! Looks like there are a few failing tests in the wagtail.admin module - could you take a look please?

2021-03-05 10:22 UTC, jacobtoppm requested changes
Thanks for contributing, I agree with optimising this! However, assuming that it won't change in the request cycle is incorrect: for example, performing a workflow action is something that you can do in a request, so at that point the cache does need to be invalidated, at the point you cancel, end, or start a workflow. I believe this is the cause of the test failures - once that's addressed, I would be happy to approve, since we did originally have this as a `cached_property` and it would be good to get that back!

2021-03-22 22:06 UTC, femto113 commented
I've only barely scratched the surface of the wagtail code (only enough to figure out why this particular slowness is happening) and don't have time at the moment to dig into this deep enough to fix the remaining tests.  Perhaps someone more familiar with the area can take this as inspiration.  If directly caching `current_workflow_state` proves to be overly complex perhaps some of the higher level properties that reference it could be more easily cached for a whole request.  There was some discussion of what paths are invoking this in #6876

2021-04-14 16:43 UTC, zerolab commented
Closing in favour of #6946. Thank you for your work on this @femto113

2021-04-14 16:43 UTC, closed without merging