6853 allow search user with custom fields
wagtail/wagtail pull request #6915
Opened 2021-03-14 22:44 UTC by y-martinez

Resolves: #6853 
With this PR, you can search users by custom fields using `search_fields`, the functionality is showing in the gif below.

- Add the `search_fields` to the custom user for use in the tests.
- Add the tests to verify the functionality.
- Add the code to search using `search_fields`

**Note**
The functionality works but developers can just override the list.html to show custom fields in the content.

**User 1**
![Screenshot from 2021-03-14 18-11-11](https://user-images.githubusercontent.com/6761059/111086280-a24ef380-84f1-11eb-8ca6-a9bbf323c1fd.png)

**User 2**
![Screenshot from 2021-03-14 18-10-39](https://user-images.githubusercontent.com/6761059/111086282-a4b14d80-84f1-11eb-96df-37b01a1638d5.png)

**User 3**
![Screenshot from 2021-03-14 18-10-11](https://user-images.githubusercontent.com/6761059/111086284-a549e400-84f1-11eb-8df2-ba99b4a74c76.png)

**Functionality**

https://user-images.githubusercontent.com/6761059/111086904-25be1400-84f5-11eb-8074-e24905f72280.mp4

2021-05-30 20:52 UTC, y-martinez commented
Is anyone to review this PR? :/

2021-06-17 15:07 UTC, favoyang commented
LGTB, wait for a core member to review.

2021-06-18 11:20 UTC, gasman requested changes
Hi @y-martinez - thanks for the PR, and sorry for the delay in reviewing.

It seems that you're using the `search_fields` definition intended for use with [the Wagtail search module](https://docs.wagtail.io/en/stable/topics/search/indexing.html), but in the end you're not actually using that module to do the searching - instead, you're doing your own ORM querying. I think this could cause problems with more complex indexing rules such as `RelatedFields`, which the ORM query doesn't account for. It also means that it won't be taking advantage of [more advanced search backends](https://docs.wagtail.io/en/stable/topics/search/backends.html) such as Elasticsearch or Postgres search.

I'd suggest a different approach: use [the `class_is_indexed` method](https://github.com/wagtail/wagtail/blob/74e3c1764f059fdbf98ffd92b774ad5e6c19dc68/wagtail/search/index.py#L133) to see if the user model is searchable through Wagtail search, and if so, perform the search [using the Wagtail search backend](https://docs.wagtail.io/en/stable/topics/search/indexing.html#indexing-custom-models). If not, fall back on the existing code that performs a plain ORM search on username / first_name / last_name / email.

2021-09-08 00:48 UTC, lb- commented
@y-martinez let us know with a comment if this is ready with the changes resolved, or if you need a hand.

2023-11-29 22:32 UTC, pcraciunoiu commented
Recently ran into this issue trying to fix email search for a case-insensitive email column using collation.

This is a blocker for email search in Wagtail, since I cannot add `email_deterministic` to fix it like for the Django admin. [Example article](https://adamj.eu/tech/2023/02/23/migrate-django-postgresql-ci-fields-case-insensitive-collation/#adjust-queries).

Anything I can do to work around this issue?

If not, any plans to fix this? Can I help rework it and get it merged ASAP?

Thanks!

2024-01-21 10:23 UTC, lb- commented
@pcraciunoiu  if you are up for it, we would love to see a new PR for this. Please review the comments/feedback above and also reference this PR and the issue it resolves when you raise a new one.

2024-01-23 01:52 UTC, pcraciunoiu commented
Thanks for the follow-up @lb-  (I didn't know you could end usernames with a `-`!)

I'll try and take a look at this over the next few weeks. No promises but I did peek at the PR changes and the feedback [from gasman](https://github.com/wagtail/wagtail/pull/6915#pullrequestreview-687303019), so it seems like the rework is mostly about using Wagtail's search which seems reasonable.

:crossed_fingers: that I find some time to PR a new changeset, I ended up using a regular email field and handling the case sensitivity in code, but I'd rather fix this and switch to DB level checks.

2024-02-02 05:18 UTC, pcraciunoiu commented
Alright, I managed to find a bit of time and merge `main` into this branch, resolve conflicts + address [the above comment](https://github.com/wagtail/wagtail/pull/6915#pullrequestreview-687303019).

I did not get a chance to test this yet, but I opened a draft PR: #11574

2024-02-03 00:33 UTC, pcraciunoiu commented
@lb- the PR is at a decent stage to review, but I did run into an issue when using the search backend, filtering for user.groups does not seem supported. Some guidance would be much appreciated.

2024-02-03 21:08 UTC, pcraciunoiu commented
I think I worked around the issue so all tests pass. I'm sure it's not perfect but it's ready to review!

2024-02-05 22:45 UTC, lb- commented
Closing in favour of newer PR https://github.com/wagtail/wagtail/pull/11574

2024-02-05 22:45 UTC, closed without merging