Compile ES6 to ES5 to fix IE11 support
wagtail/wagtail pull request #6968
Opened 2021-04-03 22:56 UTC by kaedroho

Partially fixes #6961

This mostly fixes IE11 support by compiling all ES6 Javascript in Wagtail tiself to ES5 using babel-loader. This is not a complete fix though as  ```telepath.js`` is still giving a syntax error, I think this is because the distributed version of ``telepath-unpack`` is in ES6.

2021-04-09 21:38 UTC, thibaudcolas requested changes
@kaedroho I don’t really see why this would be needed. tsc will transpile ES6+ JS to ES5 just fine – I can’t see any issues testing Wagtail v2.12 in IE11 as an example. You can see this by inspecting the JS bundles from the project, or trying `tsc` manually.

Trying the current `main` in IE11, the only issue I can see is that [telepath-unpack](https://github.com/wagtail/telepath-unpack/blob/f0d120599698a6edc9f3ce7506da6b13cb4c1099/index.js) throws JS syntax errors due to its use of `class` (among other things). This is to be expected, we don’t convert our dependencies, and generally the expectation is that all dependencies should be published as either ES5 CommonJS, or ES5 with ES modules.

2021-04-14 20:00 UTC, gasman commented
Have released an ES5-transpiled version of telepath-unpack as 0.0.3, and version bumped to that in 10d106ab43bd3fb67a1cd03237f9c246bdc1e2d7 - let me know if that's done the job...

2021-04-14 20:21 UTC, kaedroho commented
Nice one @gasman! Will check tomorrow morning

2021-04-19 16:09 UTC, gasman commented
Testing on IE11 against current main (with the telepath-unpack 0.0.3 upgrade), the only regression I can see is that adding a new rich text block to a streamfield results in a Draftail crash:

![Screenshot 2021-04-19 at 16 47 16](https://user-images.githubusercontent.com/85097/115265254-f66f7800-a12e-11eb-9746-4666d7857f37.png)

(This itself is fairly well hidden due to #5914 making the keyboard the only way to add blocks on IE11...)

Applying this PR doesn't fix that crash, so on the available evidence @thibaudcolas is correct that the telepath-unpack fix was the necessary one here.

2021-04-20 10:51 UTC, gasman commented
With the above error fixed in #7033, will close this on the assumption that recompilation isn't needed.

2021-04-20 10:51 UTC, closed without merging