7010 Add instructions on copying and aliasing pages to the editor's guide …
wagtail/wagtail pull request #7068
Opened 2021-04-21 20:50 UTC by vladutmd

Resolves #7010 

With this PR, adding a new page to the Editor's guide in the documentation regarding how to copy and create aliases to existing pages. I tried to follow the style of writing from other pages, let me know if there's anything I should change and/or add.

2021-04-21 21:01 UTC, zerolab commented
Rendered: https://wagtail--7068.org.readthedocs.build/en/7068/editor_manual/copying_aliasing_existing_pages.html

2021-04-24 15:44 UTC, jaap3 requested changes
Thank you so much for picking this up. I have some suggestions and fixed some typos. Feel free to ignore or partially apply some of the more extensive edits.

2021-04-24 15:44 UTC, jaap3 commented on docs/editor_manual/copying_aliasing_existing_pages.rst
> +* Once you change the information required, press *Copy this page* and the page will be successfully copied and appear in the Explorer page.
```suggestion
* Once you completed this form, press *Copy this page*. The page will then be copied and appear in the Explorer page.
```

2021-04-24 15:44 UTC, jaap3 commented on docs/editor_manual/copying_aliasing_existing_pages.rst
> +   :alt: Successful copying of the page resulting in it being available in an explorer page.
```suggestion
   :alt: Successful copying of a page results in it being available in the Explorer page.
```

2021-04-24 15:44 UTC, jaap3 commented on docs/editor_manual/copying_aliasing_existing_pages.rst
> +When copying a page, you also have the option to create an alias to it. Let's say you have a page about Brioche in the Breads section. At the same time, you might also want to have it in the Pastries
```suggestion
When copying a page, you also have the option to mark it as an alias. The content of an aliased page will stay in sync with the original. This is particularly useful when a page is required to available in multiple places.

For example, let's say you have a page about Brioche in the Breads section. You then want to also make this page available in the Pastries section. One way to do this is to create a copy of the Brioche page and change the parent page to the Pastries page. However you now need to remember to update this copy each time the original is modified. If a copy is marked as an alias Wagtail will do this for you each time a modification to the original page is published.
```

2021-04-24 15:44 UTC, jaap3 commented on docs/editor_manual/copying_aliasing_existing_pages.rst
> +Here is how you can create an alias to an existing page:
```suggestion
Here is how to create an alias to an existing page:
```

2021-04-24 15:44 UTC, jaap3 commented on docs/editor_manual/copying_aliasing_existing_pages.rst
> +* The first step is the same as it was for :ref:`copying-page-label`. When you hover over a page in an :doc:`Explorer page <finding_your_way_around/the_explorer_page>`, click on *More* and then *Copy
```suggestion
* The first step is the same as it is for :ref:`copying-page-label`. When you hover over a page in the :doc:`Explorer page <finding_your_way_around/the_explorer_page>`, click on *More* and then *Copy*.
```

2021-04-24 15:44 UTC, jaap3 commented on docs/editor_manual/copying_aliasing_existing_pages.rst
> +   :alt: Clicking the choose another page button during the copy page form in orderto change the parent of the copied page.
```suggestion
   :alt: Clicking the choose another page button during the copy page form in order to change the parent of the copied page.
```

2021-04-24 15:44 UTC, jaap3 commented on docs/editor_manual/copying_aliasing_existing_pages.rst
> +* Select and click on the new page to act as the parent page.
```suggestion
* Select and click on the desired parent page.
```

2021-04-24 15:44 UTC, jaap3 commented on docs/editor_manual/copying_aliasing_existing_pages.rst
> +   :alt: Selecting and clicking on a new page to act as the new parent page.
```suggestion
   :alt: Selecting and clicking the desired parent page.
```

2021-04-24 15:44 UTC, jaap3 commented on docs/editor_manual/copying_aliasing_existing_pages.rst
> +* Make sure the Alias checkbox is ticked. You can then complete the page aliasing by clicking on the *Copy this page* button.
```suggestion
* Make sure the *Alias* checkbox is ticked. 
* You can then complete the page aliasing by clicking on the *Copy this page* button.
```

2021-04-24 15:44 UTC, jaap3 commented on docs/editor_manual/copying_aliasing_existing_pages.rst
> +* The aliased page will then appear under the new parent page.
```suggestion
* The aliased page will then appear under the new parent in the Explorer.
```

2021-04-24 15:44 UTC, jaap3 commented on docs/editor_manual/copying_aliasing_existing_pages.rst
> +   :alt: The aliased page appearing under the new parent page.
```suggestion
   :alt: The aliased page appearing under the new parent page in the Explorer page.
```

2021-04-24 15:44 UTC, jaap3 commented on docs/editor_manual/copying_aliasing_existing_pages.rst
> +* If you try to edit the aliased page, you will get notified that it is an alias of another page and be offered two options: either to edit the original page (with changes appearing in both places) o
```suggestion
* When you try to edit the aliased page, you are notified that it is an alias of another page. You will then be offered two options: edit the original page (with changes appearing in both places) or convert the alias page into a regular page (i.e. a regular copy, not updated when the original changes).
```

2021-04-24 15:44 UTC, jaap3 commented on docs/editor_manual/copying_aliasing_existing_pages.rst
> +   :alt: Editing an alias page notifies it is an alias and offers to either edit the original page or change to a regular copy.
```suggestion
   :alt: Editing an alias page notifies it is an alias and offers to either edit the original page or change the alias to a regular page.
```

2021-04-28 15:51 UTC, vladutmd commented on docs/editor_manual/copying_aliasing_existing_pages.rst
> +When copying a page, you also have the option to create an alias to it. Let's say you have a page about Brioche in the Breads section. At the same time, you might also want to have it in the Pastries
```suggestion
When copying a page, you also have the option to mark it as an alias. The content of an aliased page will stay in sync with the original. This is particularly useful when a page is required to be available in multiple places.
For example, let's say you have a page about Brioche in the Breads section. You then want to also make this page available in the Pastries section. One way to do this is to create a copy of the Brioche page and change the parent page to the Pastries page. However you now need to remember to update this copy each time the original is modified. If a copy is marked as an alias Wagtail will do this for you each time a modification to the original page is published.
```

2021-04-28 15:54 UTC, vladutmd commented
Accepted the changes and fixed a typo, should be fine now :) thank you for the suggestions!

2021-05-06 09:41 UTC, vladutmd commented
What is the test that failed?

2021-05-06 10:05 UTC, zerolab commented
@vladutmd 

> docs/editor_manual/copying_aliasing_existing_pages.rst:58: D002 Trailing whitespace

2021-05-08 18:36 UTC, vladutmd commented
Sorry, must have missed that. All set!

2021-06-28 20:10 UTC, vladutmd commented
any updates on this making it in?

2021-07-06 08:13 UTC, zerolab commented
Hey @vladutmd,

Will aim to get this reviewed in the next few days with a view to getting it in.
Thank you for you contribution and sorry for the delayed response!

2021-07-06 19:45 UTC, zerolab commented
Merged in f54e7e1e416. Thank you very much for this @vladutmd

2021-07-06 19:45 UTC, closed without merging