Allow subclasses of PagesAPIViewSet override default Page model.
wagtail/wagtail pull request #7372
Opened 2021-07-26 11:17 UTC by hpoul

I wanted to create an API endpoint with custom filtering for a specific page type. I thought the easiest would be to subclass `PagesAPIViewSet` - the only problem is that it would always use `Page` object even when overriding `get_base_queryset` or setting the `model` attribute.

imho it is also sub-optimal that when no `type` GET parameter is given, it still dynamically looks up `wagtailcore.Page` - imho this created a completely unused code fragment, because i don't see how `page_models_from_string(request.GET.get('type', 'wagtailcore.Page'))` could possibly return an False/empty value in the current implementation.

2021-07-27 09:35 UTC, kaedroho requested changes
Thanks! Please could you add some tests? You could probably copy our existing page tests, point it a new test endpoint, and remove any tests that aren't relevant

2021-07-27 09:35 UTC, kaedroho commented on wagtail/api/v2/views.py
> +        queryset = self.model.objects.all().public().live()
This method is used to fetch children, ancestors, etc of the page as well, would filtering this prevent those related pages from showing up if they are not the same type?

Instead, I think we could change the below like that you've added to: ``models = models_type and page_models_from_string(models_type) or [self.model]``

2022-12-07 21:01 UTC, lb- commented
If you are still keen - go for it @Jordan-Rob

2023-09-13 11:56 UTC, NXPY123 commented
I'll look into this

2023-09-13 16:52 UTC, NXPY123 commented
Can't the following code:
```python
elif len(models) == 1:
            # If a single page type has been specified, swap out the Page-based queryset for one based on
            # the specific page model so that we can filter on any custom APIFields defined on that model
            return models[0].objects.filter(
                id__in=self.get_base_queryset().values_list("id", flat=True)
            )
```
be replaced with:
```python
elif len(models)==1:
            return self.get_base_queryset().type(model)
```

Shouldn't the results be the same?

2023-09-16 05:20 UTC, NXPY123 commented
@kaedroho are you talking about using the tests in the TestPageListing class in wagtail/wagtail/api/v2/tests/test_pages.py to test for a model type?

2023-09-17 11:29 UTC, lb- commented
Replaced by https://github.com/wagtail/wagtail/pull/10902

2023-09-17 11:29 UTC, closed without merging