Bulk actions - Refactor action registration
wagtail/wagtail pull request #7426
Opened 2021-08-11 12:29 UTC by KIRA009

This pr changes the way actions are registered, making the integration of bulk actions with modeladmin easier

2021-08-13 09:16 UTC, zerolab commented on wagtail/admin/views/bulk_action/utils.py
> +    for action_class in bulk_actions:
suggestion: fail loudly if the `action_class` is not a sublcass of `BulkAction`

2021-08-17 09:02 UTC, jacobtoppm requested changes
Looking good! A few suggested tweaks.

Additionally, I think it would be good to think about efficiency here. Currently we loop through all the bulk actions every time we want to find the list of actions for a model, or a specific action. It might be worth thinking about whether we can subdivide the bulk actions so future operations are a bit more efficient when we register them for the first time (see https://github.com/wagtail/wagtail/blob/main/wagtail/core/rich_text/feature_registry.py for a class that handles registration of a similar feature) - have a think about how you might do that?

2021-08-17 09:46 UTC, KIRA009 commented on wagtail/users/views/bulk_actions/delete.py
> +        if model is None:
>  we should fail loudly

I agree with this. The only case where `model` can be `None` is when its called from a management command, and the `model` argument is not added. I am not sure if we should assume the model from the `models` list, even if `len(models)` is 1

2021-08-24 08:38 UTC, jacobtoppm requested changes

2021-08-24 08:38 UTC, jacobtoppm commented on wagtail/users/views/bulk_actions/toggle_activity.py
> +            if len(cls.models) == 1:
This feels like this could end up in a lot of actions - maybe something to factor out to reduce the boilerplate a bit?

2021-08-24 08:38 UTC, jacobtoppm commented on wagtail/users/views/bulk_actions/toggle_activity.py
> +            if len(cls.models) == 1:
Additionally, does this need to go in a few more actions here? Feels like this should be applicable to more actions

2021-08-24 08:50 UTC, zerolab commented
@KIRA009 heads up, #7440 introduced a few conflicts.

2021-08-31 08:31 UTC, jacobtoppm approved these changes
Nice job! Looking great now you've made those final tweaks.

2021-08-31 08:32 UTC, merged