Notifications to active users only
wagtail/wagtail pull request #7510
Opened 2021-09-10 17:51 UTC by bwilliams3

Addresses issue #7506

2021-09-11 03:54 UTC, lb- commented on wagtail/admin/tests/pages/test_edit_page.py
> +
I think the linting is flagging this extra line here as an issue.

2021-09-11 03:54 UTC, lb- commented
@bwilliams3  thanks so much for taking the time to work through this problem, find the solution and also include unit tests.

There appears to be a small linting issue, you can see these issues if you run `make lint` in your terminal with the wagtail project open. See more info here https://docs.wagtail.io/en/stable/contributing/python_guidelines.html#pep8

```
./wagtail/admin/tests/pages/test_edit_page.py:2603:1: W391 blank line at end of file
```

2021-09-11 03:55 UTC, lb- requested changes
Just one minor linting issue to fix.

2021-09-11 04:15 UTC, lb- approved these changes

2021-09-11 04:16 UTC, merged

2021-09-11 04:18 UTC, lb- commented
@bwilliams3 I just fixed up that minor linting issue, validated this behaviour locally (before & after commits) and it works great.

I have pushed to your branch and this is now merged in, please check the contributors listing and let me know if you want your name listed differently.

Thanks again for taking the time to provide this fix, it is really appreciated!

2021-09-13 12:28 UTC, bwilliams3 commented
@lb- No problem and thanks for wrapping up that last fix for me -- appreciate it!