Add missing bind_to call to PreviewOnEdit, fixes #7537
wagtail/wagtail pull request #7538
Opened 2021-09-24 11:54 UTC by th3hamm0r

see #7537

2021-09-26 10:40 UTC, lb- requested changes
Hey @th3hamm0r this looks good in principle, I have checked your original issue and the comments there and I think it makes sense to add this.

However, it would be really great if you can take a bit more time to add some unit tests for this so that the behaviour does not get lost in the future.

You could do this by
* wagtail/admin/tests/pages/test_preview.py (adding a test here, within `TestPreview`
* see wagtail/admin/tests/test_edit_handlers.py -> TestPageEditHandlers.test_custom_edit_handler_form_class for an example of customising a Page's edit_handler temporarily for a test
* Remember to 'reset' the cached `get_edit_handler` method by copying the code from `clear_edit_handler` in that same edit handlers test file, you may not need the decorator approach but we do not want to pollute other tests

Please reach out if you get stuck, and thanks again for taking the time to investigate the root cause here.

2021-09-27 09:48 UTC, th3hamm0r commented
@lb- Thanks for your detailed guide, that helped a lot! :)

Some notes:
- I re-used the code of the existing tests in `TestPreview` to get working test quickly. There is also a `SecretPage` model in the testapp, which already uses a custom panel, which I could have used, but it was easier for me to reuse the lines from the other preview tests, which use the `EventPage`. That allowed me to reuse the defined `post_data` for example.
- I followed your hint to copy the `clear_edit_handler` decorator, but I think it would be a good point to extract it into a utility module. Since I'm too new to wagtail's test setup, I didn't fell confident enough to do that in the first place.
- Actually I don't fully understand, why the `test_custom_edit_handler_form_class` also sets the `edit_handler` before mocking it, so I left that out in my test. Hope I didn't miss something here. https://github.com/wagtail/wagtail/blob/27c3e7921a6c31664abf8587b491861e62f4e74c/wagtail/admin/tests/test_edit_handlers.py#L249

2021-09-27 21:12 UTC, lb- approved these changes

2021-09-27 21:13 UTC, lb- commented
@th3hamm0r looking great, for some reason the ` ci/circleci: backend — Your tests failed on CircleCI ` failed.
Looks like there needs to be a line break after ` import datetime`

```
ERROR: /home/circleci/project/wagtail/admin/tests/pages/test_preview.py Imports are incorrectly sorted and/or formatted.
--- /home/circleci/project/wagtail/admin/tests/pages/test_preview.py:before	2021-09-27 11:54:04.911275
+++ /home/circleci/project/wagtail/admin/tests/pages/test_preview.py:after	2021-09-27 11:55:38.731172
@@ -1,4 +1,5 @@
 import datetime
+
 from functools import wraps
 from unittest import mock
 
Skipped 956 files

Exited with code exit status 1


```

2021-09-27 21:14 UTC, lb- commented on wagtail/admin/tests/pages/test_preview.py
>  import datetime
```suggestion
import datetime

```

2021-09-27 22:17 UTC, merged

2021-09-27 22:18 UTC, lb- commented
@th3hamm0r thanks again, all merged in, really appreciate the time taken to add unit tests and investigate the other potential missing bind_to calls in the codebase.