Fixes #7241 and improves error visibility in high-contrast
wagtail/wagtail pull request #7663
Opened 2021-10-29 15:31 UTC by Wicked7000

This fixes the accessibility issue mentioned in #7241 and also fixes issue with error visibility in high-contrast mode (before this the message was white and indistinguishable from other text on the page)

Before:
![image](https://user-images.githubusercontent.com/1568832/139462618-32289701-8976-46a0-a93e-b17f4e4f5846.png)
![image](https://user-images.githubusercontent.com/1568832/139462475-40021f43-0e03-45c4-956f-630f50f03e26.png)

After:
![image](https://user-images.githubusercontent.com/1568832/139462157-3a493351-0d94-433d-a425-849272e40dca.png)
![image](https://user-images.githubusercontent.com/1568832/139462294-c2410920-dcdf-4e07-a397-e538372a57ae.png)

2021-11-01 15:44 UTC, nmorduch requested changes
Thanks for making this change! It looks great.

One request: I'd like to put all new hex colors in [variables.scss](https://github.com/wagtail/wagtail/blob/main/client/scss/settings/_variables.scss) for consistency, and ideally base them off of the existing colors. I would add something like the following in `variables.scss` (but simply moving the hex colors there would also work), then reference those colors here.

``` scss
$color-text-error: change-color($color-red, $saturation: 69, $lightness: 52);
$color-text-error-forced-color: change-color($color-red, $saturation: 100, $lightness: 50);
```

Let me know if any of that isn't clear enough, and I'm happy to clarify it :)

Sorry I missed the end of October for this, if when it's reviewed makes a difference! If you no longer have time to devote to this, let me know and I'd be happy to update the PR with this change.

2021-11-01 16:57 UTC, Wicked7000 commented
> Thanks for making this change! It looks great.
> 
> One request: I'd like to put all new hex colors in [variables.scss](https://github.com/wagtail/wagtail/blob/main/client/scss/settings/_variables.scss) for consistency, and ideally base them off of the existing colors. I would add something like the following in `variables.scss` (but simply moving the hex colors there would also work), then reference those colors here.
> 
> ```css-scss
> $color-text-error: change-color($color-red, $saturation: 69, $lightness: 52);
> $color-text-error-forced-color: change-color($color-red, $saturation: 100, $lightness: 50);
> ```
> 
> Let me know if any of that isn't clear enough, and I'm happy to clarify it :)
> 
> Sorry I missed the end of October for this, if when it's reviewed makes a difference! If you no longer have time to devote to this, let me know and I'd be happy to update the PR with this change.

No worries! I've updated to put the adjusted colours in the variables file.

I forced pushed (as I assume you'd likely want commit history to be 1 Commit per MR/Feature) so I can't mark the requested change as completed.

Let me know if there is any other additional changes needed!

2021-11-05 16:26 UTC, nmorduch commented
Looks good to me! Thank you! I'm going to ask that someone who knows more about the Windows high contrast setup review that aspect :)

2021-11-05 17:21 UTC, vsalvino commented
I can test out Windows High contrast stuff if needed... let me know what areas to hit (if you have any kind of check-list) and I'd be happy to help.

2021-11-06 23:34 UTC, Wicked7000 commented
> I can test out Windows High contrast stuff if needed... let me know what areas to hit (if you have any kind of check-list) and I'd be happy to help.

The main area I used for testing was by using the form shown in Settings -> Users -> Add a user 
Then clicking over to the roles tab without correctly filling out some or all fields and you should get the error notification to come up.

However I'm sure this is just one of many forms on the Wagtail admin page so I'm sure others can give pointers to others if needed to check over multiple form areas.

2021-11-19 15:52 UTC, vsalvino commented
Tested this out, error messages on the fields seem to be visible, always in red regardless of varying high contrast setting. The error banner at the top could probably use some visual treatment but is perfectly readable at least. Looks good to me overall.

Here is what I am seeing when making a page edit with error:

High Contrast \#1:

![image](https://user-images.githubusercontent.com/13453401/142651134-ff9cc39b-43c6-4319-a7de-ca9c5441b9ae.png)

High Contrast \#2:

![image](https://user-images.githubusercontent.com/13453401/142651208-d45ffef6-66fd-4eaf-bda0-46270555dad8.png)

High Contrast Black:
![image](https://user-images.githubusercontent.com/13453401/142650866-462d2770-2b42-4638-b711-14ce0573e39b.png)

High Contrast White:

![image](https://user-images.githubusercontent.com/13453401/142651300-f2b8c348-ab2d-46be-9724-da060efb3d42.png)

2021-11-19 16:02 UTC, vsalvino approved these changes

2022-01-13 06:45 UTC, thibaudcolas approved these changes
Thank you! Looks amazing, I’m very happy we get this in. Font icons are going away pretty soon (#6107), so we’ll need to switch this to SVGs, but this should be no problem when that happens.

2022-01-13 06:46 UTC, merged