[WIP] Prevent duplicate nested streamblocks to have duplicated UUIDs - Fix #7712
wagtail/wagtail pull request #7713
Opened 2021-11-17 08:32 UTC by fabienheureux

Fix #7712 

# TODO
- [ ] Provide description
- [ ] Write tests

2021-11-17 18:19 UTC, gasman requested changes
Thanks for looking into this @fabienheureux!
It's an important part of StreamField's design that each block type is only responsible for managing its own part of the data structure, and doesn't try to 'guess' how to step through its child objects based on their data type. That means the general pattern for this method ought to be something like getState or getValue - blocks that manage child blocks (e.g. StreamBlock, StructBlock and ListBlock [1]) should call a method on those child blocks to perform whatever manipulation is required.

This potentially means an addition to the block API, and we need to think quite carefully about what that addition should look like - it has to be something 'high-level' enough that it makes sense for any block to implement it without having to think about an internal detail of StreamBlock (so a method called 'fixUUIDs' or whatever would not be good).

The root problem here is that StreamBlock implements block duplication by calling `getState` on the child block and creating a new block with that state, on the assumption that it's always desirable for the copied block to exactly match the existing block's state. We now know that isn't true - we don't want the IDs in nested StreamBlocks to match.

I think the neatest way to address that is with a new method `getDuplicatedState()` that behaves like `getState`, but returns the state that we want a new copy of this block to have. For a simple block like CharBlock, `getDuplicatedState` would be identical to `getState` - and since we don't really want to have to go through _all_ existing blocks adding a new method, I suggest that we fall back on `getState` whenever `getDuplicatedState` isn't defined.

A container block like StructBlock would implement `getDuplicatedState` recursively, by calling `getDuplicatedState` on each child (falling back on `getState` if that's not defined) and building a data structure out of the results. StreamBlock would do the same, with the additional step of stripping out UUIDs (at its own top level only - the recursion would do the rest). Then, duplicateBlock would be changed to call `getDuplicatedState` instead of `getState`, and - I think - it would all fall into place from there.


[1] As of 2.15, we can add TypedTableBlock to that list. Unfortunately I don't think we'll be able to make this work for third-party container block types (do any exist?) without code changes.

2021-11-18 07:42 UTC, fabienheureux commented
Thanks a lot for your review/insight @gasman !
I will look into this, and try to get a better understanding of current StreamField frontend architecture before pushing new changes.

2021-11-18 09:10 UTC, jacobtoppm requested changes
I think new UUIDs should be generated on the frontend rather than simply being stripped out - commenting uses them to find the contentpath for the streamfield block, which sets out which block or field the comment is on (and I think it's reasonable to expect every block to have a unique path/uuid combo to track it in code - we might well use this elsewhere in the future).

2021-11-18 10:00 UTC, gasman commented
@jacobtoppm FWIW, I think the existing version of this code does the same thing - see the `childState.id = null;` line that's been removed here. Looks like bd606ab15cc847fec2d1666bbd9a87350192a7ee added client-side UUID generation, but only did it for insertions (or maybe I'm reading the code wrong, and `_getChildDataForInsertion` does actually get called on duplication further down the line).

2021-11-18 10:26 UTC, jacobtoppm commented
@gasman Good point! Clearly something we missed. But if we're revisiting this point, I would suggest doing client side id generation for duplication as well.

2022-09-06 06:48 UTC, fabienheureux commented
Closing as it was fixed in #9108

2022-09-06 06:48 UTC, closed without merging