Ensure bulk publish action picks up latest revisions
wagtail/wagtail pull request #7821
Opened 2022-01-04 17:46 UTC by gasman

Fixes #7690.

Also tweak the confirmation pages to show the draft title (via `get_admin_display_title`), to match the rest of the admin (because failing to do that looks particularly wrong when confirming the publish action).

2022-01-05 09:47 UTC, kaedroho requested changes
Changes here look good to me, but I think we need to also add a ``specific_deferred`` in somewhere so that custom implementations of `get_admin_display_title`` will be called.

Could probably add this to the queryset? (I think this is [here](https://github.com/wagtail/wagtail/blob/0d8ad857bf9bcf11fe64c1b814bb4040a54e5a8e/wagtail/admin/views/bulk_action/base_bulk_action.py#L51))

2022-01-05 12:42 UTC, gasman commented
@kaedroho Done!

2022-01-05 13:49 UTC, kaedroho approved these changes
Looks good to me, thanks!

2022-01-05 13:59 UTC, merged

2022-01-06 01:06 UTC, Scotchester commented
Thanks so much for the quick fix, @gasman and @kaedroho!