Revise SVG Icons to use Icons import or css where necessary
wagtail/wagtail pull request #8054
Opened 2022-02-28 23:00 UTC by stevedya

Replaced instances of $font-wagtail-icons being used for icons and left instances that would be overwritten by the 2022 page editor UI updates.

### Icons Replaced For:
** Help Blocks ** 
![Screen Shot 2022-02-28 at 3 47 27 PM](https://user-images.githubusercontent.com/25041665/156071306-1d682001-6fee-4603-8bf1-587635120fc8.png)

**  Header Search Field Icon found in: snippets / redirects / shared header / model admin pages **
![Screen Shot 2022-02-24 at 4 06 46 PM](https://user-images.githubusercontent.com/25041665/156071799-d66d6a67-6749-40e1-986b-c280ee6e19ec.png)

** Error message X icon on fields ** 
![Screen Shot 2022-02-22 at 10 53 50 AM](https://user-images.githubusercontent.com/25041665/156071849-362c6058-d9ec-4d07-84b2-6bcbff12761a.png)

** Checkboxes / Radio buttons **
![Screen Shot 2022-02-24 at 3 39 46 PM](https://user-images.githubusercontent.com/25041665/156071958-1d32b4d1-eddd-42a5-a3a5-5a409a21ce24.png)
![Screen Shot 2022-02-24 at 4 26 57 PM](https://user-images.githubusercontent.com/25041665/156071960-f3b70614-c126-4597-b558-288998c6b05f.png)

** Tags ** 
<img width="400" alt="Screen Shot 2022-02-23 at 11 22 31 PM" src="https://user-images.githubusercontent.com/25041665/156071990-bab0ea20-6069-4f77-bf9a-33cef024a939.png">

** Select locale in Page explorer header ** 
![Locale Select Icon](https://user-images.githubusercontent.com/25041665/156072110-ec0aa962-b204-428d-a2da-7946f15c0a91.png)

** Button long running spinner ** 
![Screen Shot 2022-02-28 at 3 56 42 PM](https://user-images.githubusercontent.com/25041665/156072257-af888e8d-8630-49bd-a2cc-3fac8a057962.png)

### Icons marked to be reformatted:
- Page editor Field blocks such as collapse, arrow down on Multifield panels, Date and View Icons on panels in editor settings panels
- Form fields with icons before text input (date, time, link)
- Date picker icons

2022-03-02 14:56 UTC, thibaudcolas commented
@stevedya thank you for providing screenshost! Can you fix the failing CI tests, and describe in your PR description how you’ve tested this so far (which browsers in particular)?

2022-03-02 18:26 UTC, stevedya commented on wagtail/admin/static_src/wagtailadmin/scss/layouts/page-editor.scss
> +          ); // UI Redesign: To be removed in page editor redesign
Good suggestion!

2022-03-02 20:51 UTC, stevedya commented
@thibaudcolas I have resolved that test now and just put a quick line about the browsers I've used to test. Let me know if there should be other tests taken for a PR of this magnitude 😄 . I'll re request review for now

2022-03-07 16:20 UTC, thibaudcolas requested changes
Looking good! With the exception of the listing changes, which unfortunately are still only partly there. I see you’ve re-added them in SVG, but they don’t update as expected based on the filtering status (we’d need to update the corresponding JS), and we’d need to update the tests as well.

Since this is all in separate files from the rest, I’ll revert those files back and merge the rest.

2022-03-07 17:05 UTC, thibaudcolas approved these changes
Tested with Firefox 97, Chrome 101, Safari 15.2. I’ve added separate line items for checkbox fixes only, since those are the only ones that will be different for end users. We’ll make a note about the icon implementation change once it’s completed throughout the admin.

2022-03-07 17:06 UTC, merged