Follow-up fixes from documentation parser switch (recommonmark -> MyST)
wagtail/wagtail pull request #8101
Opened 2022-03-10 08:32 UTC by thibaudcolas

Follow-up to #8084. Fixes #8099. There are a lot of assorted changes here. Here are the ones related to #8099:

- Installing our `docs` extras in CircleCI so issues like #8099 are picked up by CI tests
- Switching from jinjalint to curlylint to fix the actual dependency incompatibility issue

Since curlylint is a fork of jinjalint, it should work more or less the same as its predecessor for our current usage. Its usage of `attrs` (the dependency conflict in question) is very basic, so it supports all versions from 17 onwards.

And things I had picked up in #8084 but decided they weren’t worth waiting on:

- Adding spacing to fix the rendering issues with the new docs parser
- Switching to GFM Markdown tables rather than eval-rst for tables in Markdown documents

I have been investigating the spacing issue in https://github.com/executablebooks/MyST-Parser/issues/533, and it turns out it’s more complicated than initially thought, so I think we should go ahead with a CSS workaround even if inelegant.

---

I tested this all locally, but the real test here will be what happens in CircleCI and with our RTD build.

2022-03-10 08:41 UTC, thibaudcolas commented
[RTD build logs](https://readthedocs.org/projects/wagtail/builds/16321606/) are looking good. This is with sphinx 4.4.0, and docutils 0.17 it seems. CircleCI build logs looking good too.

2022-03-10 09:04 UTC, lb- requested changes
Should we update setup.py -> `"Sphinx>=1.5.2",`

As you noted in https://github.com/executablebooks/MyST-Parser/issues/533#issuecomment-1063457555 it looks like our usage of MyST bumps us up to Sphinx 3.1.* anyway?

2022-03-10 09:04 UTC, lb- commented on docs/contributing/documentation_guidelines.md
> +Only use tables when needed.
```suggestion
Only use tables when needed, using the [GitHub Flavored Markdown table syntax](https://github.github.com/gfm/#tables-extension-).
```

2022-03-10 09:06 UTC, lb- commented on docs/_static/css/custom.css
> +
We should probably adopt MyST Parser in our Wagtail Sphinx theme.

This way we can triage and add core styling for these issues.

https://github.com/executablebooks/MyST-Parser/issues/533
https://github.com/executablebooks/MyST-Parser/issues/534

2022-03-10 09:07 UTC, lb- commented on docs/_static/css/custom.css
> +
https://github.com/wagtail/sphinx_wagtail_theme/issues/133 created

2022-03-10 21:21 UTC, lb- approved these changes
As this is blocking others from building Wagtail, we can discuss the Sphinx version separately.

2022-03-10 21:23 UTC, lb- commented
Just rebasing this now @thibaudcolas

2022-03-10 21:29 UTC, lb- commented
@thibaudcolas  please do one more review of the rebase, just added the GFM markdown tables link to the docs and added release notes / upgrade considerations.

2022-03-11 15:21 UTC, thibaudcolas commented
Thank you @lb-! I agree it would be better to fix this at the theme level, but thought it’d be important to get this through _fast_. There is also a chance we could get this fixed in Sphinx or MyST if we can figure out where the issue comes from.

2022-03-11 15:21 UTC, merged