Add admin tag manager documentation to edit and delete tags
wagtail/wagtail pull request #8207
Opened 2022-03-25 21:41 UTC by amajai

Solution to #1220 .
Added admin tag manager solution to the documentation where you can set up admin tag interface to manage tags.

2022-03-30 22:38 UTC, lb- requested changes
Looking good, just a minor nitpick on the heading.

2022-03-30 22:38 UTC, lb- commented on docs/reference/pages/model_recipes.rst
> +----------------------
Maybe something a bit clearer might be better...

```
Managing tags with Wagtail's `ModelAdmin`
-----------------------------------------
```

2022-03-31 10:13 UTC, amajai reviewed
Thanks. Much clearer on describing the model recipe. Will change it right away.

2022-04-05 21:17 UTC, lb- approved these changes
looking great @amajai  - I have rested the code as documented locally and works really great!

I have pushed to your remote branch with a few tweaks in formatting and also the changelog/release notes entry.

I have added you as a contributor as `Abdulmajeed Isa` - please let me know if you want your name listed differently.

Thanks so much for taking the time to contribute to Wagtail!

2022-04-05 21:21 UTC, merged