Add support for merging cells in TableBlock.
wagtail/wagtail pull request #8278
Opened 2022-04-05 06:25 UTC by gareth-palmer

Handsontable has supports for merging table cells using the mergeCells
plugin but there currently is no support in Wagtail for storing which cells have
been merged or rendering them in the output template.

This change makes the client Javascript will now save which cells have been
merged and the output template will merge or hide cells.

- [x] Do the tests still pass?[^1]
- [x] Does the code comply with the style guide? 
    - [x] Run `make lint` from the Wagtail root. 
- [x] For Python changes: Have you added tests to cover the new/fixed behaviour?
- [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    - [ ] **Please list the exact browser and operating system versions you tested**:
    - [ ] **Please list which assistive technologies [^3] you tested**: 
- [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**. 

To test this change, create a add a TableBlock to a Page with with `mergeCells: True` in
the table options and include `mergeCells` in the `contextMenu` option, eg:

```
table_block = TableBlock(..., table_options={
  'mergeCells': True,
  'contextMenu': [
     ...,
     'mergeCells'
  ],
})
```

Edit the page, add some text to the cells then highlight multiple cells and select
'Merge Cells' from the context menu.

Publish the changes to the page the re-edit it. The table cells that were merged
should continue to be merged whereas without this change they would have
reverted back.

View a live version of the page, inspecting the HTML should show that cells that
have been merged have a `rowspan` and `colspan` attributes.

The Wagtail documentation does not mention the mergeCells feature but it does
link to the Handsontable documentation where it is shown.

2023-08-30 22:25 UTC, lb- requested changes
@gareth-palmer thanks for this, sorry you have not had a review for some time.

Would you be keen on pursuing this still?

The handson table code is unfortunately a bit fragile and had a round of bug fixes in the last few releases and this code has had some churn.

Additionally, the linting has been updated for some of the code in this file.

If you are able to rebase this and do a fresh round of validation it may be able to be reviewed.

2023-08-31 11:36 UTC, gareth-palmer commented
Hi @lb- , Thank you for reviewing this. I am still keen on pursing this change.

I will push a rebased version in a a day or so.

2023-09-01 11:02 UTC, gareth-palmer commented
I've pushed a rebased version now.

2023-09-06 12:06 UTC, gareth-palmer commented
This is the code and template I used to test the feature:
[test_table.py.txt](https://github.com/wagtail/wagtail/files/12537080/test_table.py.txt)
[test_table.html.txt](https://github.com/wagtail/wagtail/files/12537086/test_table.html.txt)

Screenshots show before and after merging:
![test_table](https://github.com/wagtail/wagtail/assets/10859998/52a7d4bd-dc82-41c4-b9e6-16929632adcc)
![test_table_merged](https://github.com/wagtail/wagtail/assets/10859998/e95e8a86-0154-4268-a30d-c495f7c202fa)

2023-09-06 20:24 UTC, lb- commented
Thank you. I've set this to needs review. 

@gasman - any thoughts?

I'll probably do a review but just wanted to get your eyes on this.

2023-09-07 22:01 UTC, lb- approved these changes
This works great, I did add docs as we already document all the other supported options. This was a small change so just did it on top of your PR.

Thank you for taking the time to do this, I will merge this in shortly.

Congrats on your first contribution to Wagtail!

2023-09-07 22:30 UTC, merged

2023-09-07 23:42 UTC, gareth-palmer commented
Thank you so much for your help in reviewing and getting this change merged @lb-!