Style comments as per design
wagtail/wagtail pull request #8345
Opened 2022-04-13 09:39 UTC by kaedroho

This PR increases the size of the comments and updates some colours to make them match the design closer.

It also updates the way comments are positioned, so they stick to the side panel on the X axis but follow the content on the Y axis

2022-04-13 12:10 UTC, jacobtoppm requested changes
Copy/pasted from Slack: What is this intended to look like at small screen sizes/mobile? Currently it's a bit weird, because the comments float over the fields, but you have the huge white panel covering basically the whole screen, so it's hard to see -which- fields, and if you minimise that, you can't see the comments any more.

[dex]
hmm i can imagine how we've got here. I think ideally at the point the white side panel overlays, it would go invisible and the comments would just float on top of the page, as they do now.

2022-04-13 14:22 UTC, phildexter commented
Just discussed this with @kaedroho and @gasman.

The specific mobile / small screen issue was actually brought in by a previous commit rather than this one. It's not good and we don't like it but we think we should probably think of a way to fix that independently of this PR.

So @jacobtoppm if you're ok with this then we're good for you to merge it and get it into the RC.

2022-04-13 14:31 UTC, jacobtoppm approved these changes

2022-04-13 23:15 UTC, gasman commented
This seems to be a step backwards for me - the comments overlap the edge of the side panel now.

Before:
![Screenshot 2022-04-14 at 00 12 27](https://user-images.githubusercontent.com/85097/163284807-54df70c1-3600-4103-bdf4-96b11ceae8c0.png)

With this PR:
![Screenshot 2022-04-14 at 00 11 29](https://user-images.githubusercontent.com/85097/163284827-71f88696-22e6-44e2-9ee7-0635ffa19a8b.png)

2022-04-14 08:42 UTC, kaedroho commented
@gasman Yep, that's how it is in the design. This hasn't been design reviewed though

2022-04-14 08:55 UTC, kaedroho commented
It's just been decided that comments won't use the new panel for 3.0, so I'll remove it

2023-04-17 23:58 UTC, merged

2023-04-17 23:58 UTC, thibaudcolas commented
…and merged! Target designs, rebased to be compatible with Wagtail 5.