clarify link conversion effect
wagtail/wagtail pull request #8375
Opened 2022-04-16 11:49 UTC by thijskramer

_Please check the following:_

- [X] Do the tests still pass?[^1]
- [X] Does the code comply with the style guide? 
    - [X] Run `make lint` from the Wagtail root. 

**Please describe additional details for testing this change**. 

While translating the untranslated strings of Wagtail 3.0-rc.1  in Transifex I found making a link more "robust" hard to understand. After a talk with @lb- on Slack we came to this change in wording.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)

2022-04-16 12:23 UTC, Scotchester requested changes
Thanks for this! The clarification is very helpful. Just one tiny suggestion.

2022-04-16 12:23 UTC, Scotchester commented on wagtail/admin/templates/wagtailadmin/chooser/confirm_external_to_internal.html
> +            if the underlying page changes its url.
```suggestion
            if the underlying page changes its URL.
```

2022-04-16 12:33 UTC, thijskramer commented on wagtail/admin/templates/wagtailadmin/chooser/confirm_external_to_internal.html
> +            if the underlying page changes its url.
Good suggestion, I've fixed it!

2022-04-17 22:00 UTC, lb- approved these changes
Thanks @thijskramer this is great!

2022-04-17 22:05 UTC, merged