Convert rst to md for ModelAdmin
wagtail/wagtail pull request #8443
Opened 2022-04-27 19:32 UTC by thoang43

_Please check the following:_

Since this is a conversion from rst to md. I am not sure which tests to be run.
- [ ] Do the tests still pass?[^1]
- [X] Does the code comply with the style guide? Documentation guide.
    - [ ] Run `make lint` from the Wagtail root. 
- [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
- [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    - [ ] **Please list the exact browser and operating system versions you tested**: MacOS, Chrome
    - [ ] **Please list which assistive technologies [^3] you tested**: 
- [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**. 

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

2022-04-27 22:20 UTC, vupham04 commented
Related #8383

2022-05-11 12:15 UTC, lb- commented
Thanks so much @vupham04 I will attempt to get this reviewed soon.

2022-05-12 10:49 UTC, lb- requested changes
@thoang43 thanks for taking the time to prepare this, it looks pretty good.
I have a few recommended fixes but in general - be sure to run `make clean` & `make html` to check for warnings, the main warnings introduced are for the heading level issues.

It looks like some heading levels were not correctly brought over to the MD files.


reference/contrib/modeladmin/index.md:38: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
reference/contrib/modeladmin/index.md:49: WARNING: Non-consecutive header level increase; H2 to H4 [myst.header]
reference/contrib/modeladmin/primer.md:16: WARNING: Non-consecutive header level increase; H2 to H5 [myst.header]
reference/contrib/modeladmin/primer.md:20: WARNING: Non-consecutive header level increase; H2 to H5 [myst.header]
reference/contrib/modeladmin/primer.md:31: WARNING: Non-consecutive header level increase; H2 to H5 [myst.header]
reference/contrib/modeladmin/primer.md:168: WARNING: Non-consecutive header level increase; H2 to H5 [myst.header]
reference/contrib/modeladmin/primer.md:207: WARNING: Non-consecutive header level increase; H2 to H5 [myst.header]
reference/contrib/modeladmin/primer.md:244: WARNING: Non-consecutive header level increase; H2 to H5 [myst.header]
reference/contrib/modeladmin/primer.md:317: WARNING: Non-consecutive header level increase; H2 to H5 [myst.header]

Also this error came up 
* reference/contrib/modeladmin/tips_and_tricks/reversing_urls.rst:134: WARNING: Failed to create a cross reference. A title or caption not found: modeladmin_url_helper_class - it could be that `docs/reference/contrib/modeladmin/tips_and_tricks/reversing_urls.rst` is not picking up the reference correctly for some reason.

Who should we put as the contributor on this, yourself or Amelia Dao (or both).
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/create_edit_delete_views.md
> +**NOTE:** `modeladmin` only provides 'create', 'edit' and 'delete' functionality for non page type models (i.e. models that do not extend `wagtailcore.models.Page`). If your model is a 'page type' mo
MIght be nice to put this into an admonition I think.

```
```{note}
...
```
```

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/primer.md
> +##### Add & edit forms are still defined by `panels` and `edit_handlers`
```suggestion
### Add & edit forms are still defined by `panels` and `edit_handlers`
```

Let's change this to heading level 3 - as it is within a heading level 2.

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/primer.md
> +##### Add & edit forms are still defined by `panels` and `edit_handlers`
```suggestion
### Add & edit forms are still defined by `panels` and `edit_handlers`
```

Let's change this to heading level 3 - as it is within a heading level 2.

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/primer.md
> +##### 'Page type' models need to be treated differently from other models
```suggestion
### 'Page type' models need to be treated differently from other models
```

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/primer.md
> +##### 'Page type' models need to be treated differently from other models
```suggestion
### 'Page type' models need to be treated differently from other models
```

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/primer.md
> +##### Wagtail's `ModelAdmin` class is 'modular'
```suggestion
### Wagtail's `ModelAdmin` class is 'modular'
```

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/primer.md
> +##### Wagtail's `ModelAdmin` class is 'modular'
```suggestion
### Wagtail's `ModelAdmin` class is 'modular'
```

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/primer.md
> +##### `ModelAdmin.url_helper_class`
```suggestion
### `ModelAdmin.url_helper_class`
```

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/primer.md
> +##### `ModelAdmin.url_helper_class`
```suggestion
### `ModelAdmin.url_helper_class`
```

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/primer.md
> +##### `ModelAdmin.permission_helper_class`
```suggestion
### `ModelAdmin.permission_helper_class`
```

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/primer.md
> +##### `ModelAdmin.permission_helper_class`
```suggestion
### `ModelAdmin.permission_helper_class`
```

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/primer.md
> +##### `ModelAdmin.button_helper_class`
```suggestion
### `ModelAdmin.button_helper_class`
```

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/primer.md
> +##### `ModelAdmin.button_helper_class`
```suggestion
### `ModelAdmin.button_helper_class`
```

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/primer.md
> +##### Using helpers in your custom views
```suggestion
### Using helpers in your custom views
```

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/primer.md
> +##### Using helpers in your custom views
```suggestion
### Using helpers in your custom views
```

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/index.md
> +#### Installation
```suggestion
### Installation
```

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/index.md
> +#### Installation
```suggestion
### Installation
```

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/index.md
> +#### How to use
```suggestion
### How to use
```

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/index.md
> +#### How to use
```suggestion
### How to use
```

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/index.md
> +##### A simple example
```suggestion
### A simple example
```

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/index.md
> +##### A simple example
```suggestion
### A simple example
```

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/index.md
> +##### A more complicated example
```suggestion
### A more complicated example
```

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/index.md
> +##### A more complicated example
```suggestion
### A more complicated example
```

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/index.md
> +##### Registering multiple classes in one `wagtail_hooks.py` file
```suggestion
### Registering multiple classes in one `wagtail_hooks.py` file
```

2022-05-12 10:49 UTC, lb- commented on docs/reference/contrib/modeladmin/index.md
> +##### Registering multiple classes in one `wagtail_hooks.py` file
```suggestion
### Registering multiple classes in one `wagtail_hooks.py` file
```

2022-05-16 01:01 UTC, thoang43 commented
Hi LB, thank you for all your suggestion. I believe the problem with reversing_urls.rst is that I did not convert that file yet. The jumping heading warning did show when I ran the make. Since I just naively turned all the title level from rst to markdown, the existed jumping heading in rst created these warnings. Do you want it to be the same with the old rst or change the new heading level? I will implement the note admonition as you suggested.

2022-05-17 06:40 UTC, vupham04 commented
@lb- hi, I have made the changes, but I do want to note that the old rst file has already jumped the heading so we just follow. But I think that this correct-formatted heading helps fix the cross reference error.

About the author, if possible, can you make @thoang43 as the main author, and I'm the co-author (Co-authored-by: Vu Pham <46913707+vupham04@users.noreply.github.com>)? Thank you

2022-05-17 08:30 UTC, lb- commented
Thanks @vupham04 - I'll take another look. 
Yeah it's a balance between fixing things while doing these kinds of changes but for something like heading levels it's good to clean it up.

2022-05-19 22:24 UTC, lb- approved these changes
Looking great, I have made some tweaks and converted the last page that was in this folder (reversing URLs).

Thanks so much for this @vupham04  & @thoang43

2022-05-19 22:32 UTC, merged