Header breadcrumb spacing fixes for #8471
wagtail/wagtail pull request #8491
Opened 2022-05-05 17:41 UTC by stevedya

## About
Addresses breadcrumb spacing issues mentioned in #8471. 
This PR moves header padding to the  `.row` class and adds a padding modifier for headers that don't contain `.row`. This allows the breadcrumbs to be be aligned separately of sibling header elements  

## Screenshots of changes

#### Desktop: inspect.html template being used with breadcrumbs

![Screen Shot 2022-05-11 at 3 38 35 PM](https://user-images.githubusercontent.com/25041665/167958579-cea14fd8-2248-4cd7-9965-54871f6db7c7.png)

#### Mobile: inspect.html template being used with breadcrumbs

![Screen Shot 2022-05-11 at 3 37 33 PM](https://user-images.githubusercontent.com/25041665/167958584-a9127fae-a232-4518-861a-fcda130ca922.png)

#### Mobile: home.html header (this header is unique to all others)
![Screen Shot 2022-05-11 at 3 01 59 PM](https://user-images.githubusercontent.com/25041665/167958587-a2285bb4-3010-4b9e-9ddf-e3168bc9a217.png)

#### Mobile: page explorer template being used with breadcrumbs
![Screen Shot 2022-05-11 at 2 52 45 PM](https://user-images.githubusercontent.com/25041665/167958589-d3dc225d-da60-4f71-aadb-e1ad151594b0.png)

### Browsers tested on 
Chrome 100, Safari 15.2, Firefox 99
Windows: Chrome 99

2022-05-06 16:44 UTC, stevedya commented on wagtail/admin/templates/wagtailadmin/home.html
> +        <div class="sm:w-ml-4">
This is the only header that needs this special padding. It's the ideal use case for a utility class

2022-05-10 16:14 UTC, thibaudcolas requested changes
@stevedya this looks like it’s creating more issues than it fixes as-is. I could spot three issues on different pages with this version:

Extra padding for "Move" page header:

![Screenshot 2022-05-10 at 16 48 53](https://user-images.githubusercontent.com/877585/167674141-b3fe4e29-6fad-44b2-9a4c-bc75398d25ca.png)

Extra padding for page listings on mobile viewports:

![Screenshot 2022-05-10 at 16 49 17](https://user-images.githubusercontent.com/877585/167674223-8b225b76-51ed-4a55-a1e6-99515d111129.png)

Mobile toggle overlapping with breadcrumb on mobile viewports:

![Screenshot 2022-05-10 at 17 00 23](https://user-images.githubusercontent.com/877585/167674270-47cf72c2-608f-44e6-ac0f-cad67c294338.png)

---

This is a very late change in the Wagtail 3.0 RC process, so I’d recommend doing much more minimal of a change if at all possible. If we can’t fix the original issue with a simple change, then this needs further work with the current approach.

- We shouldn’t make any attempt to fix the header wrapping at the odd 800-950px range in my opinion, unless it’s very straightforward. If so, let’s only do this in a separate PR, not mix it with the mandatory header/breadcrumb changes.
- Similarly I’ve extracted the branding and sidebar changes so they aren’t held up by this.

2022-05-11 22:41 UTC, stevedya commented
@thibaudcolas I've now made updates to this PR description and code to focus on the breadcrumbs issue specifically. Because of the way breadcrumbs are nested in the headers they were being affected by the padding so this PR's aim is to correct that as well as remove some interesting negative margins that were being applied before. 

When you get a chance could you take another look at this one?

2022-05-13 16:06 UTC, thibaudcolas approved these changes
Pretty happy with this now that we’ve refactored it in two commits – the first one doesn’t fix as much but should hopefully be enough for 3.0.

I’ll create a follow-up issue for us to work on headers further, though this should only be for UX consistency & visual refinement rather than fixing any obvious bugs.

2022-05-13 16:09 UTC, merged