Structblock child order
wagtail/wagtail pull request #8504
Opened 2022-05-09 22:50 UTC by ababic

_Please check the following:_

- [ ] Do the tests still pass?[^1]
- [ ] Does the code comply with the style guide? 
    - [ ] Run `make lint` from the Wagtail root. 
- [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
- [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    - [ ] **Please list the exact browser and operating system versions you tested**:
    - [ ] **Please list which assistive technologies [^3] you tested**: 
- [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**. 

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

2022-06-16 14:36 UTC, gasman requested changes
Thanks @ababic! This is definitely a worthwhile change - I'm sure the inheritance thing has come up a few times on the Slack support channel, and we haven't had a good answer for it.

Since `child_blocks` is already an OrderedDict (being cloned from the `base_blocks` definition that [DeclarativeSubBlocksMetaclass](https://github.com/wagtail/wagtail/blob/adc2ea6a865bc6d771bdbad33943fdc7c4362fec/wagtail/blocks/base.py#L479) sets up), I'd really like to see if we can "enforce" the desired ordering on `child_blocks` itself - that way we don't have to remember to always access it through the `sorted_child_blocks` property.

2022-06-17 08:25 UTC, ababic commented
Awesome. Thanks for taking a look @gasman! 

> Since child_blocks is already an OrderedDict (being cloned from the base_blocks definition that [DeclarativeSubBlocksMetaclass](https://github.com/wagtail/wagtail/blob/adc2ea6a865bc6d771bdbad33943fdc7c4362fec/wagtail/blocks/base.py#L479) sets up), I'd really like to see if we can "enforce" the desired ordering on child_blocks itself - that way we don't have to remember to always access it through the sorted_child_blocks property.

I've believe the last time I tried this approach, Django wanted to generate new migrations to take into account the order changes... introducing `sorted_child_blocks` felt like a simple enough way to avoid that, but I admit it isn't the ideal API.

2022-06-17 08:38 UTC, ababic commented
Thinking on this some more... another reason to avoid updating `child_blocks` directly is: We don't necessarily care about the order preferences for a specific block being inherited by subclasses. We're definitely talking edge-cases here, but If you specified `block_order = []` on a subclass, I imagine it could feel strange to see the `block_order` from the parent class still being respected.

2022-06-18 16:54 UTC, ababic commented
@gasman Have amended to modify `self.child_blocks` directly, but as mentioned above, it would be nice to allow developers to play with the block order without having to regenerate migrations. Maybe that's something that can be tackled separately, though. (Related: #4298)

2025-09-03 10:50 UTC, laymonage commented
This PR hasn't been active for a while, and we now have made StructBlocks always collapsible. I like the idea of this PR, but considering #2299 and the issue mentioned in this PR #7370 I think the next step is to not just allow customising the order of fields but also grouping specific fields so we can have "settings fields" without nesting another StructBlock and generating new migrations.

Thanks for starting this! I'll close this for now and hopefully someone will build on the idea to support the custom grouping.

2025-09-03 10:50 UTC, closed without merging