Removed modaladmin breadcrumbs
wagtail/wagtail pull request #8743
Opened 2022-06-24 12:33 UTC by PaarthAgarwal

Addresses 5th part of #8645 and #6904.
I have removed the breadcrumbs from modaladmin.
Added back to events list page button to compensate for breadcrumbs functionality.

Before:

![Screenshot from 2022-06-24 17-59-45](https://user-images.githubusercontent.com/86092410/175536277-2c7b93c5-2c3c-47ea-958e-52d46f28d508.png)
![Screenshot from 2022-06-24 18-00-24](https://user-images.githubusercontent.com/86092410/175536285-cf9a2316-89a5-4ad4-98df-14c68aa63cab.png)

 

After:

![Screenshot from 2022-06-24 17-53-57](https://user-images.githubusercontent.com/86092410/175535935-f0af82bb-8ec4-4959-871c-a4a0633c9708.png)
![Screenshot from 2022-06-24 17-54-18](https://user-images.githubusercontent.com/86092410/175535938-9a7ca5d7-7bec-49bd-87fb-ea768854dee9.png)
![Screenshot from 2022-06-24 17-54-59](https://user-images.githubusercontent.com/86092410/175535941-1e042541-ed7a-41fd-9e29-6c5b990903e4.png)

2022-06-25 12:23 UTC, lb- requested changes
looking good - just a few small tweaks suggested - so that we are good citizens of the codebase.

2022-06-25 12:23 UTC, lb- commented on wagtail/contrib/modeladmin/tests/test_page_modeladmin.py
> -class TestHeaderBreadcrumbs(TestCase, WagtailTestUtils):
Please add a new test in both test files that the back link exists and goes to the right location.

2022-06-25 12:23 UTC, lb- commented on wagtail/contrib/modeladmin/templates/modeladmin/choose_parent.html
> +            <p class="back"><a href="{{ view.index_url }}" class="icon icon-arrow-left">{% blocktrans trimmed with view.verbose_name as model_name %}Back to {{ model_name }} list{% endblocktrans %}</
While we are at it we should use the new svg icon markup (please update the same in the inspect view.

Rough code suggestion below, but not validated.
```suggestion
            <p class="back">
                <a href="{{ view.index_url }}">
                    {% blocktrans trimmed with view.verbose_name as model_name %}Back to {{ model_name }} list{% endblocktrans %}
                    <svg class="icon icon-arrow-right arrow_right_icon" aria-hidden="true">
                        <use href="#icon-arrow-right"></use>
                    </svg>
                </a>
            </p>
```

2022-06-28 06:02 UTC, lb- commented on wagtail/contrib/modeladmin/templates/modeladmin/choose_parent.html
> +            <p class="back"><a href="{{ view.index_url }}" class="icon icon-arrow-left">{% blocktrans trimmed with view.verbose_name as model_name %}Back to {{ model_name }} list{% endblocktrans %}</
leave is misaligned - let me know when the rest of this PR is good to review and we can get this in.

Please ask at stand-up tonight what is the best practice for using svg icons and to work around issues like this.

cc @thibaudcolas

2022-06-28 10:38 UTC, PaarthAgarwal commented
Ready for review

2022-06-28 12:16 UTC, lb- commented on wagtail/contrib/modeladmin/templates/modeladmin/choose_parent.html
> +                    <svg class="icon icon-arrow-left arrow_left_icon default" aria-hidden="true">
```suggestion
                    <svg class="icon default" aria-hidden="true">
```

`icon-arrow-left arrow_left_icon ` is not needed - this was the old approach, the `svg` element is now the icon.

2022-06-28 12:28 UTC, merged