Lock pages when they are scheduled for publishing
wagtail/wagtail pull request #8917
Opened 2022-07-28 19:30 UTC by kaedroho

This is to help make the UX of scheduled pages a bit nicer. The version of the page that's in draft is always the version that will be published by scheduled publishing.

2022-08-05 03:54 UTC, laymonage commented on wagtail/admin/views/pages/edit.py
> +                    )
FYI I was able to reduce a considerable amount of duplicated queries (around 5) by turning this into a cached property in `DraftStateMixin`, and using that here and in `get_message()`, which I think should be safe in these cases.

See https://github.com/wagtail/wagtail/pull/8901/commits/01711e631df64a23a82e5364786420bb2efa3914

2022-08-05 03:54 UTC, laymonage commented on wagtail/admin/tests/pages/test_edit_page.py
> +        with self.assertNumQueries(46):
With the above optimisation, we should be able to bring this to 41 (or maybe even keep it at 40 in this case).

2022-08-09 18:28 UTC, gasman requested changes
Very happy with the approach here! The introduction of Lock objects is a really neat way to connect business logic to the front-end messaging without things getting spaghetti-ish, and the reduction in queries is a really nice bonus too. Just some very minor niggles to sort.

2022-08-09 18:28 UTC, gasman commented on wagtail/admin/action_menu.py
> +            'locked_for_user' = True if the lock prevents the current user from editing the page
Do we guarantee that the context will always contain these variables? If so, they should be listed before "may also contain". If not, the code below needs to guard against them being missing with `context.get(...)`.

2022-08-09 18:28 UTC, gasman commented on wagtail/locks.py
> +            _("Page '{}' is locked and has been scheduled to go-live at {}"),
"go-live" shouldn't have a hyphen when used as a verb - it should be "go live".

2022-08-11 12:46 UTC, gasman commented
Merged (with suggested fixes applied) in e5dd080fce3cda19e61ce5e27adc436d334d747b.

2022-08-11 12:46 UTC, closed without merging