Different lock color when it's locked by current user
wagtail/wagtail pull request #8954
Opened 2022-08-06 15:56 UTC by mr-vaibh

The lock will turn orange indicating that that specific page is locked by the current user.

![image](https://user-images.githubusercontent.com/52421094/183256483-9a8edda4-209c-4b02-be6f-57b64aa703f0.png)

**NOTE: we can also add this line on the top "Golden locks are pages locked by YOU"**

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

2022-08-06 16:55 UTC, mr-vaibh commented
@zerolab please review my code

2022-08-06 22:54 UTC, lb- requested changes
@mr-vaibh thanks for updating this and raising a new PR. 

Please can you address the following items, it would be great to see this in but we need to ensure this is a robust solution. 

- [x] visual indication aside from colour is a must
- [x] unit tests and linting are failing, please review and fix up errors
- [x] update screenshots in PR description to align with the new changes
- [x] move the icon to use the icon template component
- [ ] move the `title` attribute to an inner span for the screen reader description OR use a tooltip for this description content (preferred)
- [x] use a colour that already exists in the colour variables - see colour.js

2022-08-06 22:54 UTC, lb- commented on wagtail/admin/templates/wagtailadmin/pages/listing/_locked_indicator.html
> +    ></span>
Can we adopt the new icons here

```
{% icon ... %}
```

Will mean some styling updates but will lead to a better experience and consistent icon rendering

2022-08-06 22:54 UTC, lb- commented on wagtail/admin/templates/wagtailadmin/pages/listing/_locked_indicator.html
> +    <span class="indicator locked-indicator {% if page.owner == request.user %}locked-indicator-owner{% endif %} icon icon-locked"
Instead of the `title` attribute - let's use an inner span.ghat has the class `w-sr-only` (this should E better supported for screen readers).

2022-08-06 22:54 UTC, lb- commented on wagtail/admin/tests/test_reports_views.py
> +
Would be good to add a test for the inverse scenario (if not already present)

2022-08-06 22:56 UTC, lb- commented
Also added a note that we should use a colour that already exists in the colour variables. 

As for the note about what the 'gold' means - preference would be to avoid doing that.

2022-08-06 22:57 UTC, lb- commented on wagtail/admin/templates/wagtailadmin/pages/listing/_locked_indicator.html
> +    <span class="indicator locked-indicator {% if page.owner == request.user %}locked-indicator-owner{% endif %} icon icon-locked"
An alternative approach would be to use a tooltip - this way we keep the ability to show the label for non screen readers without using title which is not supported on some mobiles. 

See the 'last updated' html for how this is done.

2022-09-05 23:36 UTC, lb- reviewed
@mr-vaibh I have opted to get this finished off so that we can merge it in, there were a few further issues with the PR as it was.

I know that it can be a bit frustrating to get some front-end changes working across multiple browsers, legacy code, high-contrast/accessibility considerations. Thanks for giving it a go and hope to see you submit more PRs in the future.

### Implementation Notes

Locked indicator was showing if the page owner was the current user not the locked by was current user. I also updated the wording, this is a hard one to phrase as we want to avoid the confusion that only you (the user) cannot edit, but rather it has been locked by editing by all users.

Kept the usage of `title` - this was already changing a lot and I wanted to keep this PR close to the original submission.

<img width="649" alt="Screen Shot 2022-09-06 at 9 06 26 am" src="https://user-images.githubusercontent.com/1396140/188520484-eb470e59-c241-4d3a-8a75-b550b3718f99.png">

I have also ensured that the inverted styles show correctly for users that may not be able to see differences in colour, and users on Windows high contrast mode.

FYI @Scotchester  / @anujaraj  

**before**

<img width="674" alt="Screen Shot 2022-09-06 at 9 05 08 am" src="https://user-images.githubusercontent.com/1396140/188520542-e264f0fe-4b3b-42de-872c-73f4a83453d8.png">

**after**

<img width="567" alt="Screen Shot 2022-09-06 at 9 06 14 am" src="https://user-images.githubusercontent.com/1396140/188520451-ebd6c21c-784b-486a-b059-24a6278c719e.png">

2022-09-05 23:44 UTC, lb- approved these changes

2022-09-06 00:20 UTC, merged