Draft: Adjust checkbox and radio label colours, remove margin on fields in g…
wagtail/wagtail pull request #9074
Opened 2022-08-24 05:01 UTC by stevedya

Addresses #9033. Form style design review fixes:

- [x]  Center-align fields within group permission tables
<img width="903" alt="Screen Shot 2022-08-23 at 10 58 28 PM" src="https://user-images.githubusercontent.com/25041665/186332860-7c4ce28b-8a38-4463-af82-d079242bf043.png">

- [x]  Checkbox & radio option label should be grey
<img width="272" alt="Screen Shot 2022-08-23 at 10 58 46 PM" src="https://user-images.githubusercontent.com/25041665/186332888-290f392c-c7a7-47c7-aaca-c008a1ef9c03.png">

- [x]  Spacing between error icon and message
<img width="854" alt="Screen Shot 2022-08-23 at 10 57 18 PM" src="https://user-images.githubusercontent.com/25041665/186332931-bf0857ac-5449-4734-8dbb-7db56b8db2f6.png">

- [ ]  Field row horizontal spacing **(need more guidance on this one)**

## Browsers tested on
Chrome 104 , Safari 15.6, Firefox 103

2022-08-30 13:26 UTC, gasman commented
@stevedya Is this ready for review, or still in draft?

2022-08-30 14:25 UTC, stevedya commented
@gasman this is ready for review yep!

2022-08-30 15:18 UTC, jacobtoppm requested changes
All looks good aside from the table alignment. It looks to me as though the checkboxes and the heading start are aligned, looking like left aligned rather than center?

2022-09-05 18:35 UTC, stevedya commented
> All looks good aside from the table alignment. It looks to me as though the checkboxes and the heading start are aligned, looking like left aligned rather than center?

@jacobtoppm oops sorry for the confusion, the purpose of this was to centre align them vertically. (The form inside the table cell had a margin bottom pushing it upwards)

2022-10-07 07:38 UTC, thibaudcolas approved these changes
All working as expected :)

2022-10-07 07:40 UTC, merged