Applied new design for delete buttons
wagtail/wagtail pull request #9153
Opened 2022-09-06 18:56 UTC by PaarthAgarwal

Fixes #3823.
I'm putting a PR fixing these inconsistencies:
Normal and hover state
![Screenshot from 2022-09-07 00-25-06](https://user-images.githubusercontent.com/86092410/188716260-c93621f7-84cf-4aa0-b358-c2418a21b156.png)

Delete image button after the fix:
![Screenshot from 2022-09-07 00-08-18](https://user-images.githubusercontent.com/86092410/188715927-e15194fa-bd3d-4177-86cf-59c5043fa60c.png)

Delete user button after the fix:
![Screenshot from 2022-09-07 00-08-53](https://user-images.githubusercontent.com/86092410/188715978-5aae8ed9-de49-4ec0-91a3-feca3a80c7cc.png)

The delete button in listings is supposed to be like that and has a styles over-ridding button.scss. Let me know if I should remove it to match our designs.

2022-09-06 22:14 UTC, lb- requested changes
@PaarthAgarwal  great start thank you, but there are still a bunch of gaps to resolve.

1. Assuming we are removing all `.button-secondary` in combination with no/serious - we should also remove these classes when they will do nothing - see https://docs.google.com/spreadsheets/d/1HX4VKAMjIQhL1aQ6hwMEihlPDkQPsi0ISOr3prwva3Y/edit#gid=0 for the list of classes in use currently.
2. When no / serious button is disabled - it still has a visible hover state - this should not happen. It looks like the disabled styles either lost (in the last refactor) or never had a hover override - please can you add that.
3. Remove `.no` override in dropdown legacy - client/scss/components/_dropdown.legacy.scss - and review these styles as it appears to be not working correctly
4. Yes please - can you ensure the listing styling adopts the new design. Remove (some, maybe all) of the .no override in listing client/scss/components/_listing.scss
5. `bicolor` - when applying `no` or `serious` to bicolor it does not work fully, maybe this is a non-issue but it would be good to see if there is a quick fix.
6. Confirm delete in comment overlay should have the no styling (see screenshot)

### Screenshots

#### comment delete confirmation

<img width="588" alt="Screen Shot 2022-09-07 at 8 00 12 am" src="https://user-images.githubusercontent.com/1396140/188748055-0566f85f-9773-4086-993a-4c016cde6a55.png">

#### bicolor when warning added

<img width="975" alt="Screen Shot 2022-09-07 at 8 11 52 am" src="https://user-images.githubusercontent.com/1396140/188749667-f8439c54-16ea-4b84-a195-3500f4ed89ed.png">

#### dropdown/dropup

<img width="907" alt="Screen Shot 2022-09-07 at 7 42 29 am" src="https://user-images.githubusercontent.com/1396140/188749688-9b99d908-6035-4c06-bc5f-943d662e27ba.png">

2022-09-06 22:16 UTC, lb- commented
@PaarthAgarwal  https://github.com/wagtail/wagtail/pull/9136 has been merged in - please rebase on top & fix conflicts - this should make the styling a bit easier to work with as there are a bunch of fixes in there.

2022-09-07 07:21 UTC, lb- commented
@PaarthAgarwal also the block delete (e.g. embed block) within draftail has issues.


<img width="423" alt="Screen Shot 2022-09-07 at 5 17 02 pm" src="https://user-images.githubusercontent.com/1396140/188814518-5cc1189c-c336-4e68-bd63-d5fb29832b92.png">

**Hover**

<img width="513" alt="Screen Shot 2022-09-07 at 5 16 58 pm" src="https://user-images.githubusercontent.com/1396140/188814531-78cc871c-4610-49d6-8f73-aa220d75302a.png">

2022-09-07 08:23 UTC, PaarthAgarwal commented
@lb- I think this is ready for another round of review.
Fixed all the above points except bicolour with no because there is no such use case at the moment plus, the bicolour button will be restyled soon like the delete button. So let's keep it as a future plan maybe?

2022-09-07 11:58 UTC, lb- approved these changes
This is working really well - found one minor issue in modeladmin listings and have fixed that on your branch. I will push up some refined release notes with added upgrade considerations.

Thanks so much for pushing through on this one @PaarthAgarwal  !

2022-09-07 12:11 UTC, merged

2022-09-13 11:50 UTC, PaarthAgarwal commented
The hover behaviour is broken.
![image](https://user-images.githubusercontent.com/86092410/189893363-8f799242-c7fb-4805-99bd-ff9530be1be1.png)
The background color for hover should be different than $color-button-no. 
Open a PR to fix it

2022-09-13 23:24 UTC, lb- commented
Thanks Paarth - I will review the fix https://github.com/wagtail/wagtail/pull/9191