Reference index
wagtail/wagtail pull request #9170
Opened 2022-09-08 12:45 UTC by kaedroho

This PR implments a new `ReferenceIndex` which records all references between models. This includes references from ForeignKeys, embeds/links in rich text and chooser blocks. The index is automatically updated on `post_save` and a `rebuild_references_index` management command is provided to rebuild it from scratch. The usage reports have been updated to use this index.

I have also removed the `WAGTAIL_USAGE_COUNT_ENABLED` setting, which was originally included to allow people to opt-in to usage count for performance reasons. Performance should be much better with the new approach so I think it should always be enabled.

2022-09-08 12:46 UTC, kaedroho commented on wagtail/models/__init__.py
> +def get_object_usage(obj):
Delete this

2022-09-08 12:48 UTC, kaedroho commented on wagtail/models/__init__.py
> +    path = models.TextField()
Probably split this into two separate path fields:

 - `model_path` (For example `body.my_block.my_field`) - Used to find details of the field the reference came from, without having to retrieve the original object
 - `content_path (For example `body.bdc70d8b-e7a2-4c2a-bf43-2a3e3fcbbe86.my_field`) - Used to permalink the user to the specific block/field that contains the reference

2022-09-23 18:45 UTC, gasman requested changes
Looking good! Still need to properly dig into the details of rich text and signal handlers, but here's some first-pass feedback in the meantime...

2022-09-23 18:45 UTC, gasman commented on wagtail/admin/templatetags/wagtailadmin_tags.py
> +    url_finder = AdminURLFinder(user)
I'm not really keen on us instantiating an `AdminURLFinder` on every item in the list - that's a lot of redundant reconstruction of lookup tables. More generally, I think creating a template tag for this is going to encourage more inefficient usage like this... Can we do the attaching of edit_url inside the view instead (using a single AdminURLFinder instance) and pass a tuple of (edit_url, reference) to the template?

2022-09-23 18:45 UTC, gasman commented on wagtail/management/commands/rebuild_references_index.py
> +                if not ReferenceIndex.model_is_indexible(model):
I think "indexable" would be the more conventional spelling.

2022-09-26 20:18 UTC, gasman reviewed
I'm happy with this! The way that rich text rewriters get split up into `embed_rules` and `reference_extractors` feels a tad messy, but not sure how we'd do something better without overhauling the existing API, which would be out of scope for this - and keeping rewriters as the single "source of truth" about what embedded entities mean is definitely a good thing.

Just dropping in a small suggestion for making this more extensible.

2022-09-27 14:00 UTC, gasman approved these changes

2022-09-27 16:19 UTC, gasman requested changes
Rebased at https://github.com/gasman/wagtail/tree/kaedroho-reference-index with some fixes to the tests...

Just realised we need to consider permissions on the usage view, so that we're not leaking information about objects that the user isn't meant to be able to see. Unfortunately, doing this rigorously probably requires a lot more work, given that different models have different business rules about what a user should see - it would probably call for AdminURLFinder to be the source of truth for that.

Things get even more complicated if we want to filter the references queryset (which we'd need to do to list just the permitted items, while keeping pagination correct) - it would probably need something similar to our logging setup, with distinct tables for different permission models...

As a minimal acceptable fix, I suggest we treat edit permission as a best approximation to "things that should be shown in the usage report":

* For the 'usage' view on a given source object, require edit permission on that object
* When outputting the listing, any item with a null edit_url should output something like "(Private image)" instead of the object's `str` representation.

2022-09-30 10:27 UTC, gasman commented
Thanks for adding the permission check @kaedroho!

Looks like we still need to address the other side - ensuring that the object listing doesn't show anything they're not supposed to see - but I'd be happy to merge this as is, and create a follow-up PR for that.

2022-09-30 13:19 UTC, gasman commented
Afraid I've found some new issues on final testing:

* The usage count on snippets is unstyled and missing margins:
![Screenshot 2022-09-30 at 14 15 27](https://user-images.githubusercontent.com/85097/193277939-61c9c18b-3bb1-42f8-8fdd-c4ef05e7eb56.png)

It probably makes sense for this to appear in the Status side panel (which currently only appears for snippets with revisioning or draft status enabled, but could be made always-on)

On Bakerydemo, after running `rebuild_references_index`, the "Japan" snippet is still showing 0 uses despite being referenced from the Anpan breads page - investigating now.

2022-09-30 13:41 UTC, gasman commented
> On Bakerydemo, after running rebuild_references_index, the "Japan" snippet is still showing 0 uses despite being referenced from the Anpan breads page - investigating now.

Got it - it's because `rebuild_references_index` is scanning the wagtailcore.Page model after breads.BreadPage. When retrieving the Anpan page as a plain Page, it naturally finds no references, and that empty list overwrites the real reference list that was stored under the same ID and content type.

2022-10-03 15:43 UTC, gasman commented
> Got it - it's because `rebuild_references_index` is scanning the wagtailcore.Page model after breads.BreadPage. When retrieving the Anpan page as a plain Page, it naturally finds no references, and that empty list overwrites the real reference list that was stored under the same ID and content type.

This could be fixed for pages in particular by ensuring that we only ever index the `specific` instance. However, we'd strongly prefer to avoid special-casing the Page model, since in all other respects this implementation is agnostic of any Wagtail models. Since it acts on all Django models unless explicitly opted-out, we ought to ensure it works for all models using multi-table inheritance, and in the general case there may not be a way of obtaining a specific instance from a basic one (other than by scanning all installed models to find subclasses and doing a database lookup for each one).

The bug could also be handled within the `rebuild_references_index` command by keeping track of the already-indexed model / pk pairs, and skipping the indexing of any objects that we've previously indexed under a more specific subclass. However, this bug could also surface elsewhere any time we trigger a reindex on a model instance that isn't the most specific subclass (for example, by retrieving a `Page` instance, updating its title, and saving).

I haven't fully figured out a comprehensive fix yet, but I suspect it might require us to store the content type of the source object as two distinct fields, one for the base model and one for the specific model that we actually ran `ReferenceIndex.create_or_update_for_object` against. Then, on any subsequent call to `ReferenceIndex.create_or_update_for_object`, potentially with an object in its less specific form, it's only allowed to overwrite records where the specific_content_type field corresponds to that object or a more general subclass. That way, any references relating to a field on a more specific subclass will be left alone. (Alternatively, `create_or_update_for_object` could be made to take into account the `model_path` field of ReferenceIndex, and skip over any records that refer to an unrecognised field on the assumption that it belongs to a more specific subclass - however, this risks leaving behind stale entries if the field in question has actually been dropped in a migration.)

2022-10-03 19:05 UTC, gasman commented
Another issue - it doesn't seem to be picking up document links in rich text. Tested by editing the FooterText snippet on bakerydemo to add a page link, document link and image, then running the following from the shell:

```
>>> from wagtail.models import ReferenceIndex
>>> from bakerydemo.base.models import FooterText
>>> ft = FooterText.objects.first()
>>> list(ReferenceIndex._extract_references_from_object(ft))
[(1, '61', 'body.', 'body.'), (2, '52', 'body.', 'body.')]
```
The two returned references correspond to the page and image - there is no reference returned for the document link.

2022-10-05 08:27 UTC, gasman commented
Superseded by #9279

2022-10-05 08:27 UTC, closed without merging