Make report titles sentence case consistently
wagtail/wagtail pull request #9183
Opened 2022-09-12 14:38 UTC by niqjohnson

Most report menu items ("Aging pages", "Site history", "Workflow tasks") are sentence case, with "Locked Pages" being the outlier in title case. This change makes all menu items consistently sentence case in the reports menu.

_Please check the following:_

-   [x] Do the tests still pass?[^1]
-   [x] Does the code comply with the style guide?
    -   [x] Run `make lint` from the Wagtail root.
-   [x] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [x] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [x] **Please list the exact browser and operating system versions you tested**:
    -   [x] **Please list which assistive technologies [^3] you tested**:
-   [x] For new features: Has the documentation been updated accordingly?

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

2022-09-12 20:39 UTC, lb- requested changes
@niqjohnson great find, thank you.

I think sometimes `Pages` (as in the `Page` class) gets used accidentally for the non-proper noun `pages` where it is just a set of pages.

This is confusing but I agree that these reports should refer to the non-proper noun.

Please can you update one additional item in the storybook file and also there is a reference to this report in the docs file that needs updating.

https://github.com/wagtail/wagtail/blob/6b238454359c7b9aeb412e095777c63ff3592d8c/docs/extending/adding_reports.md?plain=1#L4

2022-09-12 20:39 UTC, lb- commented on client/src/components/Sidebar/Sidebar.stories.tsx
> +            label: 'Locked pages',
There is another item on line ~407

2022-09-12 21:23 UTC, niqjohnson commented
@lb-, good catches. I sentence cased those other two instances in 7e3f087

2022-09-12 21:23 UTC, niqjohnson commented on client/src/components/Sidebar/Sidebar.stories.tsx
> +            label: 'Locked pages',
Fixed in 7e3f087

2022-09-15 20:45 UTC, lb- approved these changes
<img width="251" alt="Screen Shot 2022-09-16 at 6 44 02 am" src="https://user-images.githubusercontent.com/1396140/190505091-3eaf9d8b-acbc-481b-88fd-d65538988433.png">

This is looking great @niqjohnson  thank you for taking the time to put this PR up and respond to feedback.

I will get some changelog notes added and also add you to the contributors list and push up to your branch.

2022-09-15 21:04 UTC, lb- commented
Note - I have updated the historic changelog references to this report also.

2022-09-15 21:04 UTC, merged