double code remove in views.py, unuse able else conditions remove in locks.py and gettext_lazy remove because django4.0 is remove on this place use gettext
wagtail/wagtail pull request #9291
Opened 2022-10-06 16:22 UTC by ArslanDevPy

…locks.py and gettext_lazy remove because django4.0 is remove on this place use gettext

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

2022-10-06 16:47 UTC, gasman requested changes
Thanks for the PR @ArslanDevPy! Unfortunately these changes aren't valid, as detailed.

2022-10-06 16:47 UTC, gasman commented on wagtail/locks.py
> +        return user.pk != self.page.locked_by_id
This does not fit our preferred coding style - see https://github.com/wagtail/wagtail/pull/8734#discussion_r904991844.

2022-10-06 16:47 UTC, gasman commented on wagtail/views.py
> +    form = PasswordViewRestrictionForm(instance=restriction, request.POST or None)
This change makes the code more difficult to follow. The bound form (with `request.POST` passed) and the unbound one serve different purposes, so it's appropriate to keep the two versions separate.

2022-10-06 16:47 UTC, closed without merging

2022-10-07 20:12 UTC, ArslanDevPy commented
Thank you for taking time out to review my changes, ill follow the mentioned :)