Fixes wagtail/wagtail#9350
wagtail/wagtail pull request #9356
Opened 2022-10-13 21:23 UTC by Lovelyfin00

Fixes issue wagtail/wagtail#9350

![image](https://user-images.githubusercontent.com/38161296/195713376-7e7854d3-e627-44d9-8029-2f1b5db2b01f.png)

2022-10-15 22:59 UTC, lb- commented on client/scss/components/_workflow-timeline.scss
> +      background: Canvas;
If possible - can this change be split to a different PR - I know the change is small but it's best if one PR can solve one problem.

2022-10-15 23:01 UTC, lb- commented on client/scss/layouts/_login.scss
> +      border: 5px solid transparent;
Just a thought. Should we use `outline` instead. This is not a focusable element so the outline won't be used here. Outline also helps for avoiding additional content size changes. 

https://developer.mozilla.org/en-US/docs/Web/CSS/outline

2022-10-19 05:41 UTC, Lovelyfin00 commented
@lb- 
I've checked the link you sent and outline is basically for focusable elements like input element. Since I can't use outline here, should i reduce the size of the border or is the style transparent not good?

2022-10-19 05:43 UTC, Lovelyfin00 commented
But I tested it with outline solid and this is how it looks in light mode

![image](https://user-images.githubusercontent.com/38161296/196606583-e918b0dc-554b-4520-9263-6796e72afed7.png)

Then this is how it looks in dark mode

![image](https://user-images.githubusercontent.com/38161296/196606756-fe506895-d62b-4204-a8b5-19496014f5a2.png)

2022-10-19 10:08 UTC, lb- requested changes
@Lovelyfin00  I think there has been some confusion with our chat on slack.

I recommended that we put the transparent background on the `content-wrapper` but not using the forced colours at all.

This way we get a simpler solution and no risk of 'shifting' of content size due to the border not existing on the non-forced colors mode variant.

Are you able to remove the forced colours mode on line 70 to 72 and then add.

```
      border: 5px solid transparent;
```

in place of line 54 - then see if it works in normal, plus light & dark high contrast mode. My understanding is that Windows will read there is a border and change the colour to the suitable colour based on the mode.

If this does not work we can discuss a different solution.

Hope that makes sense.

2022-10-19 10:09 UTC, lb- commented
I think we can resolve the icon in a different PR - feel free to raise a new issue for this problem though with some screenshots.

2022-10-19 11:48 UTC, Lovelyfin00 commented
@lb- 
I uploaded these screenshots before I chatted you up.
I've made the necessary changes as we discussed.

Screenshot for light mode 
![image](https://user-images.githubusercontent.com/38161296/196682399-b4b2299e-f48e-4b91-b260-bc28a287bff0.png)


Screenshot for dark mode

![image](https://user-images.githubusercontent.com/38161296/196682459-d80674a7-9f00-47c9-b13a-acec67950efa.png)

2022-10-19 22:12 UTC, lb- commented
Awesome - will aim to do another review if no one else gets to it before me

2022-10-20 12:49 UTC, lb- approved these changes
Thanks @Lovelyfin00  a few rounds but we got there - thanks for sticking at it.

This is a much more simpler solution and works great.

### Screenshots
<img width="684" alt="Screen Shot 2022-10-20 at 10 49 11 pm" src="https://user-images.githubusercontent.com/1396140/196953216-c95d8c8c-dabd-40af-b3e6-164d894a5b1e.png">
<img width="687" alt="Screen Shot 2022-10-20 at 10 49 00 pm" src="https://user-images.githubusercontent.com/1396140/196953235-064b5922-f403-499b-8640-e650b9317b1f.png">

2022-10-20 13:01 UTC, merged