Improve grammar, spelling, and punctuation in Extending Wagtail section
wagtail/wagtail pull request #9373
Opened 2022-10-15 20:09 UTC by albinazs

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

2022-10-16 09:53 UTC, lb- commented
@albinazs  curious - what was the tool? It seems to be pretty solid.

2022-10-17 01:02 UTC, gasman requested changes
Thanks @albinazs! Most of these changes look good, but there are a few I'm not sure about.

2022-10-17 01:02 UTC, gasman commented on docs/extending/rich_text_internals.md
> +Typically, a rich text widget also receives a `features` list, passed from either `RichTextField` / `RichTextBlock` or the `features` option in `WAGTAILADMIN_RICH_TEXT_EDITORS`, which defines the fea
There doesn't seem to be any real consensus about whether "opt in to" or "opt into" is correct, but "opt in to" seems to be more common and there are convincing grammatical arguments in favour of it (https://english.stackexchange.com/questions/422848/opt-into-vs-opt-in-to, https://forum.wordreference.com/threads/opt-in-or-opt-into.3560327/) - I think we should keep it.

```suggestion
Typically, a rich text widget also receives a `features` list, passed from either `RichTextField` / `RichTextBlock` or the `features` option in `WAGTAILADMIN_RICH_TEXT_EDITORS`, which defines the features available in that instance of the editor (see [rich text features](rich_text_features)). To opt in to supporting features, set the attribute `accepts_features = True` on your widget class; the widget constructor will then receive the feature list as a keyword argument `features`.
```

2022-10-17 18:22 UTC, albinazs commented
Dear @lb-, I used Grammarly. It highlights possible mistakes in grammar, spelling, and punctuation. After that, I check all suggestions and make a final decision. I can check other docs as well.

Dear @gasman, your knowledge of the context is certainly better than mine:) I accepted all the suggestions - they do make sense. PR is updated accordingly.

2022-10-19 20:41 UTC, thibaudcolas approved these changes
Thank you @albinazs! It seems you’ve addressed everything flagged by @gasman so I’ll merge this now. Some of the changes on commas seem a bit arbitrary to me 😅 but there are plenty of typos too that I’m happy to see fixed.

2022-10-19 20:41 UTC, merged