Update _workflow-tasks.scss - Changed font-size from px to rem
wagtail/wagtail pull request #9490
Opened 2022-10-26 09:26 UTC by IvyJeptoo

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

2022-10-26 09:44 UTC, IvyJeptoo commented
@thibaudcolas kindly review my PR

2022-10-26 23:55 UTC, thibaudcolas requested changes
@IvyJeptoo I think this needs a bit more work! Also make sure to:

- Describe what you’ve done. It looks like you submitted this pull request without describing your change, nor following any of our template
- Describe how you’ve tested this so far, and why you chose to make the changes you did.
- Add screenshots. In particular I want you to share what this looks like with a non-default font size set in the browser.

2022-10-26 23:55 UTC, thibaudcolas commented on client/scss/components/_workflow-tasks.scss
> +  $task-width: 7.313rem;
This seems off, should be `7.3125rem`. Could you make sure to remove all rounding you’ve done in this file? We don’t want this change to visually alter the appearance of the component.

2022-10-26 23:55 UTC, thibaudcolas commented on client/scss/components/_workflow-tasks.scss
> +    border-radius: 0.313rem;
I don’t see why we would want the border width or radius to change depending on the font size. Could you explain why you did this?

2022-10-26 23:55 UTC, thibaudcolas commented on client/scss/components/_workflow-tasks.scss
> +  $task-height: 3.5rem;
I’m surprised we’d want to do this in `rem`. Isn’t that going to break the layout?

2022-10-26 23:55 UTC, thibaudcolas commented on client/scss/components/_workflow-tasks.scss
> +    padding-inline-end: 0.563rem;
This (and changing the `margin`) below. Also seems superfluous to me. It’d change the layout quite a lot of if we make everything bigger based on the font size?

2022-10-27 08:42 UTC, closed without merging

2022-10-27 11:27 UTC, lb- commented
@IvyJeptoo  - is everything OK - it looks like you deleted/closed this PR.

2022-10-28 06:53 UTC, IvyJeptoo commented
@lb- I deleted it so that i could make changes. I have opened another PR. thank you for the concern