Fixes wrong sizing for dropdown buttons
wagtail/wagtail pull request #9500
Opened 2022-10-26 15:19 UTC by Theresa-o

Fixing wrong sizing for dropdown buttons
https://github.com/wagtail/wagtail/issues/9476

BEFORE IMAGE

![wagissues9476error](https://user-images.githubusercontent.com/62052443/198063239-cdb607e9-6267-405c-8c10-df0b43a2933c.jpg)

AFTER IMAGE

![wagissues9476fontgood](https://user-images.githubusercontent.com/62052443/198060001-0c6a1a0d-6825-4951-9dc0-4f6cf0efc746.PNG)

2022-10-26 15:31 UTC, zerolab commented
This is a good step in the right direction.
My worry is that it is a fairly sweeping change: https://github.com/wagtail/wagtail/pull/9500/files#diff-f1e2635932247d8f5b667a1f93b41e4f1f8018ed33905e4a0d20ad00dc92e3f4R107-R112

Would be good to get an idea on the usages of `.dropdown` across the admin with `<a>`, `input[type='submit']`, `input[type='reset']`, `input[type='button']` and `<button>` element.

The styleguide could be a good place to check (admin > styleguide, in bakerydemo)

2022-10-26 16:35 UTC, Theresa-o commented
Ok, I would check this and revert.

Thank you for taking the time.

2022-10-27 10:47 UTC, Theresa-o commented
@zerolab Heads up, this is going to be a conversation with a  lot of images, please bear with me as I'd like to explain in details my thought process😀

I have seen the styleguide and specifically the guide that explains the guide for buttons a, seen below;

![wagissues94761styleguide](https://user-images.githubusercontent.com/62052443/198258318-c3dbf69a-d61e-4d5f-8f8c-2f9a8219574c.PNG)

I perused 😀 the places where the dropdown codes was used and noticed that the dropdown for these were skewed as seen below; (With the original code)

![wagissues94761locked](https://user-images.githubusercontent.com/62052443/198259110-d366f50f-3b1d-4a8c-bd00-781a78c76b64.PNG)

![wagissues94761sitehistory](https://user-images.githubusercontent.com/62052443/198259134-69d577b2-0949-4e95-b621-66c4f8903140.PNG)

![wagissues94761workflow](https://user-images.githubusercontent.com/62052443/198259151-39445d87-495f-4011-899b-5d2cb667c183.PNG)

![wagissues94761workflowtask](https://user-images.githubusercontent.com/62052443/198259167-0d6ce3f9-6a6b-4265-9097-0c5a05c72f7c.PNG)

The solution to make sure that the dropdowns button is equal is by the editing the below code;

https://github.com/wagtail/wagtail/blob/main/client/scss/components/_dropdown.legacy.scss#L114
    a,
    input[type='submit'],
    input[type='reset'],
    input[type='button'],
    .button,
    button {
      font-size: 1.06em;
    }

https://github.com/wagtail/wagtail/blob/main/client/scss/components/_button.scss
    .icon-wrapper {
      width: 18%;

This is the result for all affected buttons below after making the changes ;

![wagissues94761agingpagesgood](https://user-images.githubusercontent.com/62052443/198263673-9ade7914-6ac0-4f0d-96cc-a98b5c0a1823.PNG)

![wagissues94761lockedgood](https://user-images.githubusercontent.com/62052443/198263700-00ba9e38-f027-4aaa-95c7-97803a76c946.PNG)

![wagissues94761sitehistorygood](https://user-images.githubusercontent.com/62052443/198263712-117e721b-2424-42a2-9d22-17fe50644fde.PNG)

![wagissues94761workflowgood](https://user-images.githubusercontent.com/62052443/198263731-4ecf8af3-92d4-4c7e-b245-830d7f411fc3.PNG)

![wagissues94761workflowtaskgood](https://user-images.githubusercontent.com/62052443/198263746-821fb71a-42a8-431f-965c-3bb85b06bfed.PNG)

Please let me know what your thoughts are before I push this.

Thank you.

2022-10-28 10:14 UTC, zerolab commented
@lb- @thibaudcolas this is one for the UI team

2022-10-31 09:50 UTC, thibaudcolas requested changes
Thank you for giving this a go @Theresa-o! This seems to work as expected in a few cases but changing the width will have unintended consequences, and I think we can arrive at a simpler solution.

2022-10-31 09:50 UTC, thibaudcolas commented on client/scss/components/_button.scss
> +      width: 18%;
This would be problematic because then the icon width is dependent on the button width.

```suggestion
      width: 3em;
```

2022-10-31 09:50 UTC, thibaudcolas commented on client/scss/components/_dropdown.legacy.scss
> +      font-size: 1.06em;
I think we could just remove this `font-size` definition! No point in redefining this if there’s already a definition that matches what we’re after.

```suggestion
```

2022-10-31 16:32 UTC, laymonage commented
Hi @Theresa-o, sorry to close this but as @thibaudcolas mentioned, we decided to go ahead with a simpler solution in #9551 to avoid unintended changes in other areas. I hope you can find other issues to work on!

2022-10-31 16:32 UTC, closed without merging