Note about running 'make html'
wagtail/wagtail pull request #9559
Opened 2022-11-01 00:37 UTC by DokuaAsiedu

Created a note callout to address issue #9540: _make is not recognized as an internal or external command, operable program or batch file_

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

2022-11-04 13:28 UTC, DokuaAsiedu commented
@lb- Could you have a look at this pr I made in reference to the [comment](https://github.com/wagtail/wagtail/issues/9540#issuecomment-1295522737) you left on issue #9540

2022-11-06 04:28 UTC, lb- requested changes
Looking great. Just some recommendations for refinements. Thanks!

2022-11-06 04:28 UTC, lb- commented on docs/contributing/developing.md
> +Wagtail continues to update our documentation but development on Windows is not as documented as we would like it to be. We recommend setting up on a local virtual machine using our already available
```suggestion
Documentation for development on Windows has some gaps and should be considered a work in progress. We recommend setting up on a local virtual machine using our already available scripts, [docker-wagtail-develop](https://github.com/wagtail/docker-wagtail-develop) or [vagrant-wagtail-develop](https://github.com/wagtail/vagrant-wagtail-develop)
```

2022-11-06 04:28 UTC, lb- commented on docs/contributing/developing.md
> +If you are happy working on Windows, you will need to have the `make` utility installed in order to run commands associated with it. You can use Windows Powershell to install a package manager like [
```suggestion
If you are confident with Python and Node development on Windows and wish to proceed here are some helpful tips.

We recommend [Chocolatey](https://chocolatey.org/install) for managing packages in Windows. Once Chocolatey is installed you can then install the  [`make`](https://community.chocolatey.org/packages/make) utility in order to run common build and development commands.
```

Just trying to re-work this a bit to be less dense but also take you through discrete steps. Installing Chocolatey first and then make second.

2022-11-06 04:28 UTC, lb- commented on docs/contributing/developing.md
> +```sh
```suggestion
```doscon
```

As per https://docs.wagtail.org/en/stable/contributing/documentation_guidelines.html#when-using-console-terminal-code-blocks

Using `doscon` is our preferred approach for windows console/shell.

2022-11-07 13:15 UTC, DokuaAsiedu commented
> Looking great. Just some recommendations for refinements. Thanks!

I've committed the suggestions you made. Could you please have a look at it again?

2022-11-09 11:22 UTC, lb- approved these changes
This is looking great, I will get this merged in shortly, thanks for taking on the feedback.

2022-11-09 11:24 UTC, DokuaAsiedu commented
> This is looking great, I will get this merged in shortly, thanks for taking on the feedback.

Thanks for also giving the feedback 😊

2022-11-09 11:32 UTC, merged