Added JSDOC for initDismissibles.ts  for #9495
wagtail/wagtail pull request #9597
Opened 2022-11-03 21:17 UTC by Yekasumah

I added JSDOC to the updateDismissibles and initDismissibles functions in the initDismissibles.ts files. I was able to create a new branch that didn't have any of my previously committed changes, thanks to your guidelines. As for the tests, somehow it's still failing and I'm still working on it to fix the error causing it to fail.

2022-11-06 11:57 UTC, Yekasumah commented
Hi @lb-, I have added the unit tests in the recent commit. Please review.

2022-11-08 08:09 UTC, lb- requested changes
A few recommendations for changes. This is looking really great so far. 

Unit tests look pretty solid also - well done.

2022-11-08 08:09 UTC, lb- commented on client/src/includes/initDismissibles.ts
> +import { WAGTAIL_CONFIG } from '../config/wagtailConfig'
Check you have run the formatter I think there should be a line break here 

`npm run format`

2022-11-08 08:09 UTC, lb- commented on client/src/includes/initDismissibles.ts
> + * element initialized by initDismissibles
```suggestion
 * element initialised by initDismissibles
```

2022-11-16 10:30 UTC, lb- commented
@Yekasumah - checking in on this - are you still able to work through the review feedback?

2022-11-16 12:35 UTC, Yekasumah commented
@lb- 
Yes I have been able to do it. I’ll push the changes to the pr now.

2022-11-17 08:03 UTC, lb- approved these changes
@Yekasumah thanks so much for this, I will push up a bit of a refinement to the unit tests that resolve some of the comments but just wanted to let you know for context.

In general, these unit tests could be much simpler and I have just revised to the bare minimum. I wanted to thank you for being thorough but for now just a small basic suite is all we need.

Also, we do not need to write unit tests in TypeScript but I realise that was not clarified anywhere - sorry fo the confusion with that but thanks for taking the time to get it working anyway.

I really appreciate you contributing this clean up and thanks again.

2022-11-17 08:21 UTC, merged

2022-11-18 15:46 UTC, Yekasumah commented on client/src/includes/initDismissibles.ts
> + * @param wagtailConfig {WagTailConfig}
Okay , thanks.

2022-11-18 15:46 UTC, Yekasumah commented on client/src/includes/initDismissibles.ts
> -
Thanks

2022-11-18 15:48 UTC, Yekasumah commented on client/src/includes/initDismissibles.test.ts
> +const mockFetch = jest.fn(() =>
Oh yeah, you’re right

2022-11-18 15:53 UTC, Yekasumah commented
Hi @lb- , Thank you very much. I really appreciate your patience with this issue. Also thanks for giving me the opportunity to work on this, I learnt a lot. Prior to now I had not much knowledge about writing unit tests. Now with your corrections and guidance, I’ll be able to improve and get better. Thank you very much, I really enjoyed working on this.

2022-11-18 21:28 UTC, lb- commented
Thanks for the reply @Yekasumah - you have done well here and it's hard to know where to draw the line sometimes with unit tests. 

I hope it was fun! 

Please let me know if you are happy with just `Yekasumah` as your name in the contributors list or if you want a full name listed. 

Have a great weekend

2022-11-20 22:29 UTC, Yekasumah commented
Hi @lb-, Yes it was very much fun. Yes, I'm very much happy with Yekasumah, it's the short form of my name Onyeka Asumah. Thank You.

2022-11-21 22:22 UTC, lb- commented
Awesome I will leave the name as is then.