Fix restrict global y documents and images to certain types
wagtail/wagtail pull request #9860
Opened 2023-01-09 05:22 UTC by salty-ivy

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

addresses https://github.com/wagtail/wagtail/issues/1285

2023-01-09 09:50 UTC, gasman commented
Thanks for picking this up @salty-ivy!

Just wondering what the reasoning is for putting this validation on the AbstractImage model, rather than inside `wagtail.images.fields.WagtailImageField` as in #9796? This means there'll be two different bits of code checking extensions, which is something we really want to avoid for maintainability.

2023-01-09 12:21 UTC, salty-ivy commented
@gasman  i have changed the approach, not its all set !

2023-01-09 12:58 UTC, salty-ivy commented
All good to go. lemme know if there's any suggestions

2023-01-09 17:11 UTC, gasman requested changes
Thanks @salty-ivy! Just some small tweaks and I think this will be good to go.

2023-01-09 17:15 UTC, laymonage commented on wagtail/images/tests/test_admin_views.py
> +
This feels like including implementation detail in the tests. Since the string won't change anyway, maybe it's better to just hardcode it?

2023-01-09 17:15 UTC, laymonage commented on wagtail/images/tests/test_admin_views.py
> +            f"Not a supported image format. Supported formats: {SUPPORTED_FORMATS_TEXT}.",
```suggestion
            "Not a supported image format. Supported formats: GIF, JPG, JPEG, PNG, WEBP.",
```

2023-01-09 17:41 UTC, salty-ivy commented
@gasman, @laymonage  thanks for the review changes are done!

2023-01-12 12:48 UTC, salty-ivy commented
@gasman could review this one, at your ease it's almost complete to be finalized. Thank you

2023-01-17 09:24 UTC, laymonage approved these changes
Nice one, thanks!

2023-01-27 11:16 UTC, gasman approved these changes

2023-01-30 14:46 UTC, closed without merging