Ran Prettier On PR#9893
wagtail/wagtail pull request #9927
Opened 2023-01-20 04:34 UTC by Aym-n

_Please check the following:_

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

**Please describe additional details for testing this change**.

[^1]: [Development Testing](https://docs.wagtail.org/en/latest/contributing/developing.html#testing)
[^2]: [Browser and device support](https://docs.wagtail.org/en/latest/contributing/developing.html#browser-and-device-support)
[^3]: [Accessibility Target](https://docs.wagtail.org/en/latest/contributing/developing.html#accessibility-targets)

2023-01-20 04:43 UTC, Aym-n commented
@Scotchester Can you please review this PR?

2023-01-20 21:44 UTC, lb- requested changes
@Aym-n thank you for taking the time to investigate this.

These styles fix for small devices (stop the content from overflowing to the left), but actually breaks the intended behaviour of the content overflowing the TOC container on large devices.

## Screenshots

Left is this PR, Right is current state - see on mobile it looks better but on larger devices it is now too thin.

**Small**
<img width="1048" alt="Screen Shot 2023-01-21 at 7 40 59 am" src="https://user-images.githubusercontent.com/1396140/213810632-649aea1b-f833-404c-b81e-6954563b319d.png">


**Large**
<img width="1960" alt="Screen Shot 2023-01-21 at 7 41 51 am" src="https://user-images.githubusercontent.com/1396140/213810601-ffe04ee9-c992-4c4e-87a3-efb813de7aec.png">

2023-01-20 21:44 UTC, lb- commented on docs/_static/css/docsearch.overrides.css
> +span#algolia-autocomplete-listbox-0 {
```suggestion
#algolia-autocomplete-listbox-0 {
```

No need to scope to the span here

2023-01-21 07:16 UTC, Aym-n commented
@lb- Should i use css media queries to apply the `#algolia-autocomplete-listbox-0` style rules only for mobile devices?

2023-01-21 09:18 UTC, lb- commented
Good idea. Thanks @Aym-n

2023-01-21 13:35 UTC, Aym-n commented
@lb-  do i need to change anything else? is this issue resolved?

2023-02-04 06:04 UTC, lb- commented
Still on my radar. Looks like you have accidentally included some other commits. I've triggered the runner though.

2023-02-16 09:40 UTC, lb- approved these changes
I have isolated the commit that fixes the issue and validated it works as expected, thank you @Aym-n  - I will merge this in.

A note for next time, have a read of our WIP new contributors guide for some additional tips for getting a good PR ready.

One key item is to create a branch on your repo for your changes, it will help you manage the fixes in isolation of the `main` branch.

https://github.com/wagtail/wagtail/issues/10070

2023-02-16 09:48 UTC, merged