moving collection_id from index view to add view in doc/image upload
wagtail/wagtail pull request #9934
Opened 2023-01-21 20:04 UTC by salty-ivy

-   [ ] Do the tests still pass?[^1]
-   [ ] Does the code comply with the style guide?
    -   [ ] Run `make lint` from the Wagtail root.
-   [ ] For Python changes: Have you added tests to cover the new/fixed behaviour?
-   [ ] For front-end changes: Did you test on all of Wagtail’s supported environments?[^2]
    -   [ ] **Please list the exact browser and operating system versions you tested**:
    -   [ ] **Please list which assistive technologies [^3] you tested**:
-   [ ] For new features: Has the documentation been updated accordingly?

deals with issue https://github.com/wagtail/wagtail/issues/7160
refactors / rebased along with https://github.com/wagtail/wagtail/pull/7810

2023-02-19 04:45 UTC, lb- commented
@salty-ivy  this works great - thanks for taking the time to explain this. Did some quick manual testing and it's looking good.

Are you still ok to add some unit tests for this new functionality (checking the right params exist in the HTML response). We want to ensure this behaviour gets preserved if something changes.

2023-02-19 04:45 UTC, lb- requested changes
As per comment above - needs tests.

2023-02-19 04:51 UTC, salty-ivy commented
Cool, would add tests 👍

2023-02-19 07:35 UTC, salty-ivy commented
@lb-  i guess i have written a that test already? to check the existence of right params, let me know if there's something else
or may be i misinterpreted ?

2023-02-19 08:46 UTC, lb- commented
I looked but must have missed them already in. 

`wagtail/documents/tests/test_admin_views.py` etc

I'll take another look - sorry for the confusion.

2023-02-21 10:48 UTC, lb- approved these changes
I have added another four unit tests to this as it was not testing the images multiple add page nor the links in the image/docs listings.

Other than that, looks great and tested all scenarios and they work well.

Thanks for taking the time to close this out @salty-ivy  and thanks for the original work here @bmihelac

I'll rebase, push, test the CI and merge.

2023-02-21 10:48 UTC, lb- commented on wagtail/documents/templates/wagtaildocs/multiple/add.html
> +                                <option value="{{ pk|unlocalize }}" {% if pk|unlocalize == selected_collection_id %}selected{% endif %}>
```suggestion
                                <option value="{{ pk|unlocalize }}"{% if pk|unlocalize == selected_collection_id %} selected{% endif %}>
```

Just a small nitpick in these ones, if you include the 'space' in the if statement we wont get an extra bit of whitespace when the value is not true.

2023-02-21 10:55 UTC, salty-ivy commented
Thanks @lb- , sorry for the trouble, would try to be extra cautious with the tests ;)

2023-02-21 11:48 UTC, lb- commented
@salty-ivy  no issues - once I have checked out the code & rebased, often I end up finding it easier to quickly add any gaps. I think it's awesome what you have done - really appreciated the help here.

2023-02-21 11:48 UTC, merged